# EDA

## Import package

In [1]:
import numpy as np
import pandas as pd
import os
import seaborn as sns
import matplotlib.pyplot as plt

pd.set_option("display.max_rows", 500)

## Load raw data

In [2]:
from google.colab import drive

drive.mount("/content/gdrive")

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [3]:
raw_data = pd.read_csv("/content/gdrive/My Drive/Capstone/1.Datasets/crsp_stock_2023.csv")

<ipython-input-3-c42377433bbb>:1: DtypeWarning: Columns (5,9,18,22,24,49,57) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data = pd.read_csv('/content/gdrive/My Drive/Capstone/1.Datasets/crsp_stock_2023.csv')

In [4]:
# os.listdir('/content/gdrive/MyDrive/Capstone')

## Raw Data Overview

In [5]:
raw_data

,PERMNO,date,NAMEENDT,SHRCD,EXCHCD,SICCD,NCUSIP,TICKER,COMNAM,SHRCLS,...,CFACPR,CFACSHR,OPENPRC,NUMTRD,RETX,vwretd,vwretx,ewretd,ewretx,sprtrn
0,10026,2023-01-03,NaN,11.0,3.0,2052,46603210,JJSF,J & J SNACK FOODS CORP,NaN,...,1.0,1.0,150.14000,3627.0,0.011823,-0.003934,-0.003996,0.005062,0.005023,-0.004001
1,10026,2023-01-04,NaN,11.0,3.0,2052,46603210,JJSF,J & J SNACK FOODS CORP,NaN,...,1.0,1.0,151.52000,2367.0,-0.001716,0.009553,0.009515,0.018657,0.018640,0.007539
2,10026,2023-01-05,NaN,11.0,3.0,2052,46603210,JJSF,J & J SNACK FOODS CORP,NaN,...,1.0,1.0,150.32001,2510.0,-0.010713,-0.010970,-0.011108,-0.004115,-0.004159,-0.011646
3,10026,2023-01-06,NaN,11.0,3.0,2052,46603210,JJSF,J & J SNACK FOODS CORP,NaN,...,1.0,1.0,150.89999,5521.0,0.020321,0.022257,0.022239,0.017645,0.017629,0.022841
4,10026,2023-01-09,NaN,11.0,3.0,2052,46603210,JJSF,J & J SNACK FOODS CORP,NaN,...,1.0,1.0,152.14000,3466.0,-0.019851,0.001059,0.000930,0.007190,0.007168,-0.000768
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2354825,93436,2023-12-22,NaN,11.0,3.0,9999,88160R10,TSLA,TESLA INC,NaN,...,1.0,1.0,256.76001,972876.0,-0.007701,0.002440,0.002372,0.007676,0.007387,0.001660
2354826,93436,2023-12-26,NaN,11.0,3.0,9999,88160R10,TSLA,TESLA INC,NaN,...,1.0,1.0,254.49001,954492.0,0.016116,0.005218,0.005199,0.009674,0.009299,0.004232
2354827,93436,2023-12-27,NaN,11.0,3.0,9999,88160R10,TSLA,TESLA INC,NaN,...,1.0,1.0,258.35001,1050000.0,0.018822,0.001995,0.001807,0.005276,0.004907,0.001430
2354828,93436,2023-12-28,NaN,11.0,3.0,9999,88160R10,TSLA,TESLA INC,NaN,...,1.0,1.0,263.66000,1170000.0,-0.031594,-0.000108,-0.000295,0.002042,0.001428,0.000370
2354829,93436,2023-12-29,NaN,11.0,3.0,9999,88160R10,TSLA,TESLA INC,NaN,...,1.0,1.0,255.10001,1060000.0,-0.018564,-0.004045,-0.004084,-0.007480,-0.007546,-0.002826

In [6]:
raw_data["date"].nunique()

250

In [7]:
raw_data.columns

Index(['PERMNO', 'date', 'NAMEENDT', 'SHRCD', 'EXCHCD', 'SICCD', 'NCUSIP',
       'TICKER', 'COMNAM', 'SHRCLS', 'TSYMBOL', 'NAICS', 'PRIMEXCH', 'TRDSTAT',
       'SECSTAT', 'PERMCO', 'ISSUNO', 'HEXCD', 'HSICCD', 'CUSIP', 'DCLRDT',
       'DLAMT', 'DLPDT', 'DLSTCD', 'NEXTDT', 'PAYDT', 'RCRDDT', 'SHRFLG',
       'HSICMG', 'HSICIG', 'DISTCD', 'DIVAMT', 'FACPR', 'FACSHR', 'ACPERM',
       'ACCOMP', 'SHRENDDT', 'NWPERM', 'DLRETX', 'DLPRC', 'DLRET', 'TRTSCD',
       'NMSIND', 'MMCNT', 'NSDINX', 'BIDLO', 'ASKHI', 'PRC', 'VOL', 'RET',
       'BID', 'ASK', 'SHROUT', 'CFACPR', 'CFACSHR', 'OPENPRC', 'NUMTRD',
       'RETX', 'vwretd', 'vwretx', 'ewretd', 'ewretx', 'sprtrn'],
      dtype='object')

In [8]:
raw_data.isnull().any()

PERMNO      False
date        False
NAMEENDT     True
SHRCD        True
EXCHCD       True
SICCD        True
NCUSIP       True
TICKER       True
COMNAM       True
SHRCLS       True
TSYMBOL      True
NAICS        True
PRIMEXCH     True
TRDSTAT      True
SECSTAT      True
PERMCO      False
ISSUNO      False
HEXCD       False
HSICCD       True
CUSIP       False
DCLRDT       True
DLAMT        True
DLPDT        True
DLSTCD       True
NEXTDT       True
PAYDT        True
RCRDDT       True
SHRFLG       True
HSICMG       True
HSICIG       True
DISTCD       True
DIVAMT       True
FACPR        True
FACSHR       True
ACPERM       True
ACCOMP       True
SHRENDDT     True
NWPERM       True
DLRETX       True
DLPRC        True
DLRET        True
TRTSCD       True
NMSIND       True
MMCNT        True
NSDINX       True
BIDLO        True
ASKHI        True
PRC          True
VOL          True
RET          True
BID          True
ASK          True
SHROUT       True
CFACPR       True
CFACSHR      True
OPENPRC      True
NUMTRD       True
RETX         True
vwretd      False
vwretx      False
ewretd      False
ewretx      False
sprtrn      False
dtype: bool

In [9]:
raw_data.describe()

,PERMNO,SHRCD,EXCHCD,NAICS,PERMCO,ISSUNO,HEXCD,DLAMT,DLSTCD,SHRFLG,...,SHROUT,CFACPR,CFACSHR,OPENPRC,NUMTRD,vwretd,vwretx,ewretd,ewretx,sprtrn
count,2.354830e+06,2.354772e+06,2.354772e+06,2.346296e+06,2.354830e+06,2.354830e+06,2.354830e+06,10296.000000,10296.000000,288527.000000,...,2.354031e+06,2.354031e+06,2.354031e+06,2.287667e+06,1.031357e+06,2.354830e+06,2.354830e+06,2.354830e+06,2.354830e+06,2.354830e+06
mean,3.967125e+04,3.415518e+01,2.785394e+00,4.769922e+05,4.627058e+04,1.010269e+06,2.785810e+00,1.361681,127.537296,0.032316,...,1.005429e+05,9.852322e-01,9.843638e-01,9.538534e+01,7.507964e+03,9.048003e-04,8.320577e-04,5.035500e-04,4.158311e-04,9.035951e-04
std,3.089432e+04,2.855473e+01,1.225037e+00,1.036311e+05,1.618287e+04,8.285303e+06,1.219591e+00,7.891986,97.143633,0.235257,...,3.638872e+05,2.240760e-01,2.216899e-01,5.340813e+03,3.565591e+04,8.306060e-03,8.302471e-03,9.008969e-03,9.000405e-03,8.235812e-03
min,1.002600e+04,1.000000e+01,-1.000000e+00,1.113200e+05,5.000000e+00,0.000000e+00,1.000000e+00,0.000000,100.000000,0.000000,...,5.000000e+00,2.500000e-05,2.500000e-05,4.900000e-03,0.000000e+00,-2.045700e-02,-2.047400e-02,-2.303200e-02,-2.313200e-02,-2.004100e-02
25%,1.781600e+04,1.100000e+01,1.000000e+00,4.245900e+05,3.914700e+04,0.000000e+00,1.000000e+00,0.000000,100.000000,0.000000,...,5.500000e+03,1.000000e+00,1.000000e+00,7.360000e+00,1.510000e+02,-3.977000e-03,-4.033000e-03,-6.119000e-03,-6.171000e-03,-4.194000e-03
50%,2.200300e+04,1.200000e+01,3.000000e+00,5.259900e+05,5.428600e+04,0.000000e+00,3.000000e+00,0.000000,100.000000,0.000000,...,2.497000e+04,1.000000e+00,1.000000e+00,2.097000e+01,9.290000e+02,9.190000e-04,8.170000e-04,3.020000e-04,2.570000e-04,8.520000e-04
75%,7.823600e+04,7.300000e+01,4.000000e+00,5.259900e+05,5.677900e+04,7.731800e+04,4.000000e+00,0.000000,100.000000,0.000000,...,7.900450e+04,1.000000e+00,1.000000e+00,4.122000e+01,5.604000e+03,6.503000e-03,6.455000e-03,6.891000e-03,6.865000e-03,6.304000e-03
max,9.343600e+04,7.500000e+01,5.000000e+00,9.281100e+05,5.975300e+04,9.999508e+07,5.000000e+00,229.000000,591.000000,2.000000,...,1.584241e+07,1.000000e+01,1.000000e+01,5.635490e+05,2.630000e+06,2.283500e-02,2.263900e-02,3.113600e-02,3.088100e-02,2.284100e-02

In [10]:
raw_data["TRDSTAT"].value_counts()

TRDSTAT
A    2353311
S       1206
X        255
Name: count, dtype: int64

In [11]:
raw_data.groupby("TICKER")["DLPDT"].value_counts(dropna=False)

TICKER  DLPDT
A       NaN           250
AA      NaN           250
AAA     NaN           250
AAAU    NaN           250
AAC     NaN           213
                     ...
ZYME    NaN           250
ZYNE    NaN           195
        2023-10-11      1
ZYXI    NaN           250
ZZZ     NaN             2
Name: count, Length: 11324, dtype: int64

In [12]:
raw_data[raw_data["TICKER"] == "ZYNE"]["DLPDT"]

350321           NaN
350322           NaN
350323           NaN
350324           NaN
350325           NaN
350326           NaN
350327           NaN
350328           NaN
350329           NaN
350330           NaN
350331           NaN
350332           NaN
350333           NaN
350334           NaN
350335           NaN
350336           NaN
350337           NaN
350338           NaN
350339           NaN
350340           NaN
350341           NaN
350342           NaN
350343           NaN
350344           NaN
350345           NaN
350346           NaN
350347           NaN
350348           NaN
350349           NaN
350350           NaN
350351           NaN
350352           NaN
350353           NaN
350354           NaN
350355           NaN
350356           NaN
350357           NaN
350358           NaN
350359           NaN
350360           NaN
350361           NaN
350362           NaN
350363           NaN
350364           NaN
350365           NaN
350366           NaN
350367           NaN
350368           NaN
350369           NaN
350370           NaN
350371           NaN
350372           NaN
350373           NaN
350374           NaN
350375           NaN
350376           NaN
350377           NaN
350378           NaN
350379           NaN
350380           NaN
350381           NaN
350382           NaN
350383           NaN
350384           NaN
350385           NaN
350386           NaN
350387           NaN
350388           NaN
350389           NaN
350390           NaN
350391           NaN
350392           NaN
350393           NaN
350394           NaN
350395           NaN
350396           NaN
350397           NaN
350398           NaN
350399           NaN
350400           NaN
350401           NaN
350402           NaN
350403           NaN
350404           NaN
350405           NaN
350406           NaN
350407           NaN
350408           NaN
350409           NaN
350410           NaN
350411           NaN
350412           NaN
350413           NaN
350414           NaN
350415           NaN
350416           NaN
350417           NaN
350418           NaN
350419           NaN
350420           NaN
350421           NaN
350422           NaN
350423           NaN
350424           NaN
350425           NaN
350426           NaN
350427           NaN
350428           NaN
350429           NaN
350430           NaN
350431           NaN
350432           NaN
350433           NaN
350434           NaN
350435           NaN
350436           NaN
350437           NaN
350438           NaN
350439           NaN
350440           NaN
350441           NaN
350442           NaN
350443           NaN
350444           NaN
350445           NaN
350446           NaN
350447           NaN
350448           NaN
350449           NaN
350450           NaN
350451           NaN
350452           NaN
350453           NaN
350454           NaN
350455           NaN
350456           NaN
350457           NaN
350458           NaN
350459           NaN
350460           NaN
350461           NaN
350462           NaN
350463           NaN
350464           NaN
350465           NaN
350466           NaN
350467           NaN
350468           NaN
350469           NaN
350470           NaN
350471           NaN
350472           NaN
350473           NaN
350474           NaN
350475           NaN
350476           NaN
350477           NaN
350478           NaN
350479           NaN
350480           NaN
350481           NaN
350482           NaN
350483           NaN
350484           NaN
350485           NaN
350486           NaN
350487           NaN
350488           NaN
350489           NaN
350490           NaN
350491           NaN
350492           NaN
350493           NaN
350494           NaN
350495           NaN
350496           NaN
350497           NaN
350498           NaN
350499           NaN
350500           NaN
350501           NaN
350502           NaN
350503           NaN
350504           NaN
350505           NaN
350506           NaN
350507           NaN
350508           NaN
350509           NaN
350510           NaN
350511           NaN
350512           NaN
350513           NaN
350514    2023-10-11
350515           NaN
350516           NaN
Name: DLPDT, dtype: object

## Data Selection

In [13]:
selected_variables = [
    "PERMNO",
    "date",
    "CUSIP",
    "COMNAM",
    "TICKER",
    "NAICS",
    "PRIMEXCH",
    "RET",
    "DLPDT",
    "TRDSTAT",
]
selected_data = raw_data[selected_variables]
selected_data

,PERMNO,date,CUSIP,COMNAM,TICKER,NAICS,PRIMEXCH,RET,DLPDT,TRDSTAT
0,10026,2023-01-03,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,0.011823,NaN,A
1,10026,2023-01-04,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,-0.001716,NaN,A
2,10026,2023-01-05,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,-0.010713,NaN,A
3,10026,2023-01-06,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,0.020321,NaN,A
4,10026,2023-01-09,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,-0.019851,NaN,A
...,...,...,...,...,...,...,...,...,...,...
2354825,93436,2023-12-22,88160R10,TESLA INC,TSLA,336110.0,Q,-0.007701,NaN,A
2354826,93436,2023-12-26,88160R10,TESLA INC,TSLA,336110.0,Q,0.016116,NaN,A
2354827,93436,2023-12-27,88160R10,TESLA INC,TSLA,336110.0,Q,0.018822,NaN,A
2354828,93436,2023-12-28,88160R10,TESLA INC,TSLA,336110.0,Q,-0.031594,NaN,A
2354829,93436,2023-12-29,88160R10,TESLA INC,TSLA,336110.0,Q,-0.018564,NaN,A

In [14]:
selected_data.isnull().any()

PERMNO      False
date        False
CUSIP       False
COMNAM       True
TICKER       True
NAICS        True
PRIMEXCH     True
RET          True
DLPDT        True
TRDSTAT      True
dtype: bool

In [15]:
print(
    "Check on columns having missing values:\n",
    selected_data.isna().sum()[selected_data.isna().sum() > 0],
)
print(
    "Check on columns having null values:\n",
    selected_data.isnull().sum()[selected_data.isnull().sum() > 0],
)

Check on columns having missing values:
 COMNAM           58
TICKER          563
NAICS          8534
PRIMEXCH         58
RET            2104
DLPDT       2353953
TRDSTAT          58
dtype: int64
Check on columns having null values:
 COMNAM           58
TICKER          563
NAICS          8534
PRIMEXCH         58
RET            2104
DLPDT       2353953
TRDSTAT          58
dtype: int64

In [16]:
see_selected_data = selected_data.groupby("CUSIP")["TICKER"].value_counts(dropna=False).reset_index()
see_selected_data

          CUSIP TICKER  count
0      00032Q10   AADI    250
1      00036020   AAON    250
2      00036110    AIR    250
3      00037520    ABB     97
4      00038020   ABCM    234
...         ...    ...    ...
10552  Y8897Y23   TOPS    250
10553  Y8900D10   TORO    206
10554  Y9233510   USEA    250
10555  Y9390M10    VFS     96
10556  Y9530810    WVE    250

[10557 rows x 3 columns]

In [17]:
see_selected_data.loc[see_selected_data["TICKER"].isnull() == 1].sort_values(by="count")

          CUSIP TICKER  count
187    00704R10    NaN      1
7557   76550410    NaN      1
7989   82455M10    NaN      1
8076   82932V40    NaN      1
8091   83006G10    NaN      1
8117   83204U50    NaN      1
8234   85227J10    NaN      1
8238   85237B10    NaN      1
8360   87124110    NaN      1
8800   89992410    NaN      1
9367   93465C10    NaN      1
9709   G0447T10    NaN      1
9793   G2104U10    NaN      1
9825   G2677P10    NaN      1
10512  Y1R80M10    NaN      1
9910   G3937M10    NaN      1
9926   G3R39B10    NaN      1
9959   G4594M10    NaN      1
9998   G5084H10    NaN      1
10036  G5500B10    NaN      1
10078  G6169A10    NaN      1
10137  G6S38M10    NaN      1
10156  G7244A10    NaN      1
10217  G8275910    NaN      1
10257  G8923U10    NaN      1
10305  G9520U10    NaN      1
10312  G9821810    NaN      1
10318  G9834A10    NaN      1
10420  M7518J10    NaN      1
9914   G3959D10    NaN      1
6266   63945M10    NaN      1
7378   74767N10    NaN      1
3505   36466210    NaN      1
678    03770N10    NaN      1
781    04541A10    NaN      1
1051   09062820    NaN      1
1333   12021E10    NaN      1
1579   15486W10    NaN      1
3323   34551020    NaN      1
6255   63903R10    NaN      1
3520   36870C10    NaN      1
4013   42805010    NaN      1
4267   4576JP10    NaN      1
10543  Y708VV10    NaN      1
4424   45828J10    NaN      1
6079   60458C10    NaN      1
6072   60317010    NaN      1
5893   56270V10    NaN      1
5881   56066710    NaN      1
4422   45828E10    NaN      1
5828   55317F10    NaN      1
5590   52168R10    NaN      1
5519   50172T10    NaN      1
10033  G5479G10    NaN      2
9956   G4513910    NaN      2
513    02369M10    NaN      2
406    02072L28    NaN      2
2944   31772T10    NaN      9
3559   37519U10    NaN     12
5784   54570M20    NaN     13
981    07317Q10    NaN     35
2743   30053M20    NaN     36
3810   38942Q20    NaN     52
382    01861F10    NaN     95
6221   63011A10    NaN    250

In [18]:
selected_data[selected_data["CUSIP"] == "42709650"].sort_values(by="date")

,PERMNO,date,CUSIP,COMNAM,TICKER,NAICS,PRIMEXCH,RET,DLPDT,TRDSTAT
2124068,90731,2023-01-03,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.006051,NaN,A
2124069,90731,2023-01-04,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.024812,NaN,A
2124070,90731,2023-01-05,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.011739,NaN,A
2124071,90731,2023-01-06,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.005939,NaN,A
2124072,90731,2023-01-09,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.004428,NaN,A
2124073,90731,2023-01-10,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.012602,NaN,A
2124074,90731,2023-01-11,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.013514,NaN,A
2124075,90731,2023-01-12,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.014074,NaN,A
2124076,90731,2023-01-13,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.002922,NaN,A
2124077,90731,2023-01-17,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.017582,NaN,A
2124078,90731,2023-01-18,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.00432,NaN,A
2124079,90731,2023-01-19,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.020789,NaN,A
2124080,90731,2023-01-20,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.01757,NaN,A
2124081,90731,2023-01-23,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.025899,NaN,A
2124082,90731,2023-01-24,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.007013,NaN,A
2124083,90731,2023-01-25,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.007062,NaN,A
2124084,90731,2023-01-26,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.015647,NaN,A
2124085,90731,2023-01-27,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.016106,NaN,A
2124086,90731,2023-01-30,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.024811,NaN,A
2124087,90731,2023-01-31,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.00424,NaN,A
2124088,90731,2023-02-01,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.018297,NaN,A
2124089,90731,2023-02-02,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.031099,NaN,A
2124090,90731,2023-02-03,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.010724,NaN,A
2124091,90731,2023-02-06,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.006098,NaN,A
2124092,90731,2023-02-07,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.002045,NaN,A
2124093,90731,2023-02-08,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.015646,NaN,A
2124094,90731,2023-02-09,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.013822,NaN,A
2124095,90731,2023-02-10,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.002102,NaN,A
2124096,90731,2023-02-13,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.013343,NaN,A
2124097,90731,2023-02-14,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.053361,NaN,A
2124098,90731,2023-02-15,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.007895,NaN,A
2124099,90731,2023-02-16,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.0,NaN,A
2124100,90731,2023-02-17,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.076923,NaN,A
2124101,90731,2023-02-21,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.040025,NaN,A
2124102,90731,2023-02-22,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.002566,NaN,A
2124103,90731,2023-02-23,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.008317,NaN,A
2124104,90731,2023-02-24,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.006345,NaN,A
2124105,90731,2023-02-27,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.009458,NaN,A
2124106,90731,2023-02-28,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.01624,NaN,A
2124107,90731,2023-03-01,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.004444,NaN,A
2124108,90731,2023-03-01,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.004444,NaN,A
2124109,90731,2023-03-02,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.007232,NaN,A
2124110,90731,2023-03-03,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.003916,NaN,A
2124111,90731,2023-03-06,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.013761,NaN,A
2124112,90731,2023-03-07,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.00905,NaN,A
2124113,90731,2023-03-08,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.003914,NaN,A
2124114,90731,2023-03-09,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.094303,NaN,A
2124115,90731,2023-03-10,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.111352,NaN,A
2124116,90731,2023-03-13,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.059398,NaN,A
2124117,90731,2023-03-14,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.033737,NaN,A
2124118,90731,2023-03-15,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.032636,NaN,A
2124119,90731,2023-03-16,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.042388,NaN,A
2124120,90731,2023-03-17,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.012448,NaN,A
2124121,90731,2023-03-20,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.004202,NaN,A
2124122,90731,2023-03-21,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.04557,NaN,A
2124123,90731,2023-03-22,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.018563,NaN,A
2124124,90731,2023-03-23,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.001645,NaN,A
2124125,90731,2023-03-24,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.022988,NaN,A
2124126,90731,2023-03-27,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.032905,NaN,A
2124127,90731,2023-03-28,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.008547,NaN,A
2124128,90731,2023-03-29,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.004623,NaN,A
2124129,90731,2023-03-30,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.003834,NaN,A
2124130,90731,2023-03-31,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.007698,NaN,A
2124131,90731,2023-04-03,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.007758,NaN,A
2124132,90731,2023-04-04,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.020015,NaN,A
2124133,90731,2023-04-05,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.018853,NaN,A
2124134,90731,2023-04-06,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.0,NaN,A
2124135,90731,2023-04-10,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.008807,NaN,A
2124136,90731,2023-04-11,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.004039,NaN,A
2124137,90731,2023-04-12,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.001609,NaN,A
2124138,90731,2023-04-13,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.021687,NaN,A
2124139,90731,2023-04-14,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.007862,NaN,A
2124140,90731,2023-04-17,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.031696,NaN,A
2124141,90731,2023-04-18,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.009217,NaN,A
2124142,90731,2023-04-19,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.013954,NaN,A
2124143,90731,2023-04-20,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.019878,NaN,A
2124144,90731,2023-04-21,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.013261,NaN,A
2124145,90731,2023-04-24,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.0,NaN,A
2124146,90731,2023-04-25,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.0,NaN,A
2124147,90731,2023-04-26,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.00077,NaN,A
2124148,90731,2023-04-27,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.015408,NaN,A
2124149,90731,2023-04-28,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.004552,NaN,A
2124150,90731,2023-05-01,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.003021,NaN,A
2124151,90731,2023-05-02,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.011364,NaN,A
2124152,90731,2023-05-03,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.010728,NaN,A
2124153,90731,2023-05-04,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.02866,NaN,A
2124154,90731,2023-05-05,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.044657,NaN,A
2124155,90731,2023-05-08,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.038931,NaN,A
2124156,90731,2023-05-09,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.022043,NaN,A
2124157,90731,2023-05-10,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.021037,NaN,A
2124158,90731,2023-05-11,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.000736,NaN,A
2124159,90731,2023-05-12,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.017673,NaN,A
2124160,90731,2023-05-15,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.032984,NaN,A
2124161,90731,2023-05-15,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.032984,NaN,A
2124162,90731,2023-05-16,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.016529,NaN,A
2124163,90731,2023-05-17,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.022918,NaN,A
2124164,90731,2023-05-18,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.005228,NaN,A
2124165,90731,2023-05-19,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.034918,NaN,A
2124166,90731,2023-05-22,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.012204,NaN,A
2124167,90731,2023-05-23,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.002907,NaN,A
2124168,90731,2023-05-24,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.015306,NaN,A
2124169,90731,2023-05-25,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.012922,NaN,A
2124170,90731,2023-05-26,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.023388,NaN,A
2124171,90731,2023-05-30,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.022853,NaN,A
2124172,90731,2023-05-31,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.020989,NaN,A
2124173,90731,2023-06-01,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.009682,NaN,A
2124174,90731,2023-06-02,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.006849,NaN,A
2124175,90731,2023-06-05,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.004762,NaN,A
2124176,90731,2023-06-06,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.00677,NaN,A
2124177,90731,2023-06-07,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.012777,NaN,A
2124178,90731,2023-06-08,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.001328,NaN,A
2124179,90731,2023-06-09,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.016578,NaN,A
2124180,90731,2023-06-12,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.006743,NaN,A
2124181,90731,2023-06-13,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.006028,NaN,A
2124182,90731,2023-06-14,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.013316,NaN,A
2124183,90731,2023-06-15,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.005398,NaN,A
2124184,90731,2023-06-16,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.008725,NaN,A
2124185,90731,2023-06-20,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.014218,NaN,A
2124186,90731,2023-06-21,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.007555,NaN,A
2124187,90731,2023-06-22,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.019377,NaN,A
2124188,90731,2023-06-23,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.004234,NaN,A
2124189,90731,2023-06-26,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.000709,NaN,A
2124190,90731,2023-06-27,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.014164,NaN,A
2124191,90731,2023-06-28,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.015363,NaN,A
2124192,90731,2023-06-29,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.017882,NaN,A
2124193,90731,2023-06-30,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.0,NaN,A
2124194,90731,2023-07-03,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.004054,NaN,A
2124195,90731,2023-07-05,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.004038,NaN,A
2124196,90731,2023-07-06,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.001341,NaN,A
2124197,90731,2023-07-07,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.010738,NaN,A
2124198,90731,2023-07-10,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.015936,NaN,A
2124199,90731,2023-07-11,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.01634,NaN,A
2124200,90731,2023-07-12,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.011576,NaN,A
2124201,90731,2023-07-13,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.013986,NaN,A
2124202,90731,2023-07-14,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.004389,NaN,A
2124203,90731,2023-07-17,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.010612,NaN,A
2124204,90731,2023-07-18,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.000618,NaN,A
2124205,90731,2023-07-19,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.017284,NaN,A
2124206,90731,2023-07-20,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.012136,NaN,A
2124207,90731,2023-07-21,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.0043,NaN,A
2124208,90731,2023-07-24,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.011009,NaN,A
2124209,90731,2023-07-25,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.00363,NaN,A
2124210,90731,2023-07-26,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.00425,NaN,A
2124211,90731,2023-07-27,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.011487,NaN,A
2124212,90731,2023-07-28,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.014679,NaN,A
2124213,90731,2023-07-31,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.01085,NaN,A
2124214,90731,2023-08-01,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.011926,NaN,A
2124215,90731,2023-08-02,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.001179,NaN,A
2124216,90731,2023-08-03,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.005297,NaN,A
2124217,90731,2023-08-04,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.039227,NaN,A
2124218,90731,2023-08-07,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.015211,NaN,A
2124219,90731,2023-08-08,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.052164,NaN,A
2124220,90731,2023-08-09,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.000585,NaN,A
2124221,90731,2023-08-10,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.003515,NaN,A
2124222,90731,2023-08-11,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.001168,NaN,A
2124223,90731,2023-08-14,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.001166,NaN,A
2124224,90731,2023-08-15,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.008757,NaN,A
2124225,90731,2023-08-16,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.001178,NaN,A
2124227,90731,2023-08-17,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.011176,NaN,A
2124226,90731,2023-08-17,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.011176,NaN,A
2124228,90731,2023-08-18,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.004899,NaN,A
2124229,90731,2023-08-21,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.009141,NaN,A
2124230,90731,2023-08-22,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.024758,NaN,A
2124231,90731,2023-08-23,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.013622,NaN,A
2124232,90731,2023-08-24,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.003054,NaN,A
2124233,90731,2023-08-25,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.00674,NaN,A
2124234,90731,2023-08-28,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.005478,NaN,A
2124235,90731,2023-08-29,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.000612,NaN,A
2124236,90731,2023-08-30,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.01286,NaN,A
2124237,90731,2023-08-31,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.005441,NaN,A
2124238,90731,2023-09-01,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.004863,NaN,A
2124239,90731,2023-09-05,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.018937,NaN,A
2124240,90731,2023-09-06,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.014321,NaN,A
2124241,90731,2023-09-07,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.001895,NaN,A
2124242,90731,2023-09-08,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.006936,NaN,A
2124243,90731,2023-09-11,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.015654,NaN,A
2124244,90731,2023-09-12,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.008015,NaN,A
2124245,90731,2023-09-13,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.011187,NaN,A
2124246,90731,2023-09-14,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.000615,NaN,A
2124247,90731,2023-09-15,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.013513,NaN,A
2124248,90731,2023-09-18,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.001818,NaN,A
2124249,90731,2023-09-19,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.00425,NaN,A
2124250,90731,2023-09-20,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.003628,NaN,A
2124251,90731,2023-09-21,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.021687,NaN,A
2124252,90731,2023-09-22,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.0117,NaN,A
2124253,90731,2023-09-25,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.006086,NaN,A
2124254,90731,2023-09-26,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.022989,NaN,A
2124255,90731,2023-09-27,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.011765,NaN,A
2124256,90731,2023-09-28,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.012852,NaN,A
2124257,90731,2023-09-29,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.007855,NaN,A
2124258,90731,2023-10-02,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.020097,NaN,A
2124259,90731,2023-10-03,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.02051,NaN,A
2124260,90731,2023-10-04,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.0,NaN,A
2124261,90731,2023-10-05,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.003807,NaN,A
2124262,90731,2023-10-06,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.011465,NaN,A
2124263,90731,2023-10-09,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.015113,NaN,A
2124264,90731,2023-10-10,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.008685,NaN,A
2124265,90731,2023-10-11,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.0,NaN,A
2124266,90731,2023-10-12,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.000615,NaN,A
2124267,90731,2023-10-13,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.006154,NaN,A
2124268,90731,2023-10-16,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.016099,NaN,A
2124269,90731,2023-10-17,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.008531,NaN,A
2124270,90731,2023-10-18,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.020897,NaN,A
2124271,90731,2023-10-19,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.005022,NaN,A
2124272,90731,2023-10-20,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.011987,NaN,A
2124273,90731,2023-10-23,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.027459,NaN,A
2124274,90731,2023-10-24,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.018385,NaN,A
2124275,90731,2023-10-25,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.020632,NaN,A
2124276,90731,2023-10-26,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.007242,NaN,A
2124277,90731,2023-10-27,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.013725,NaN,A
2124278,90731,2023-10-30,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.00994,NaN,A
2124279,90731,2023-10-31,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.010499,NaN,A
2124280,90731,2023-11-01,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.028571,NaN,A
2124281,90731,2023-11-02,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.016414,NaN,A
2124282,90731,2023-11-03,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.014286,NaN,A
2124283,90731,2023-11-06,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.007561,NaN,A
2124284,90731,2023-11-07,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.013133,NaN,A
2124285,90731,2023-11-08,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.008238,NaN,A
2124286,90731,2023-11-09,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.006285,NaN,A
2124287,90731,2023-11-10,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.013915,NaN,A
2124288,90731,2023-11-13,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.000624,NaN,A
2124290,90731,2023-11-14,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.013092,NaN,A
2124289,90731,2023-11-14,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.013092,NaN,A
2124291,90731,2023-11-15,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.006341,NaN,A
2124292,90731,2023-11-16,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.017643,NaN,A
2124293,90731,2023-11-17,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.003849,NaN,A
2124294,90731,2023-11-20,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.002556,NaN,A
2124295,90731,2023-11-21,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.017846,NaN,A
2124296,90731,2023-11-22,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.009085,NaN,A
2124297,90731,2023-11-24,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,0.006431,NaN,A
2124298,90731,2023-11-27,42709650,HERCULES CAPITAL INC,HTGC,523910.0,N,-0.003195,NaN,A

## Data Filter

### Filter Tickers by TRDSTAT

In [19]:
selected_data["TRDSTAT"].value_counts()

TRDSTAT
A    2353311
S       1206
X        255
Name: count, dtype: int64

In [20]:
# Filter the data to keep rows where TRDSTAT is 'A' or 'H'
filtered_data_1 = selected_data[selected_data["TRDSTAT"].isin(["A", "H"])]

# Display the filtered data
filtered_data_1

,PERMNO,date,CUSIP,COMNAM,TICKER,NAICS,PRIMEXCH,RET,DLPDT,TRDSTAT
0,10026,2023-01-03,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,0.011823,NaN,A
1,10026,2023-01-04,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,-0.001716,NaN,A
2,10026,2023-01-05,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,-0.010713,NaN,A
3,10026,2023-01-06,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,0.020321,NaN,A
4,10026,2023-01-09,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,-0.019851,NaN,A
...,...,...,...,...,...,...,...,...,...,...
2354825,93436,2023-12-22,88160R10,TESLA INC,TSLA,336110.0,Q,-0.007701,NaN,A
2354826,93436,2023-12-26,88160R10,TESLA INC,TSLA,336110.0,Q,0.016116,NaN,A
2354827,93436,2023-12-27,88160R10,TESLA INC,TSLA,336110.0,Q,0.018822,NaN,A
2354828,93436,2023-12-28,88160R10,TESLA INC,TSLA,336110.0,Q,-0.031594,NaN,A
2354829,93436,2023-12-29,88160R10,TESLA INC,TSLA,336110.0,Q,-0.018564,NaN,A

In [21]:
filtered_data_1["TRDSTAT"].value_counts()

TRDSTAT
A    2353311
Name: count, dtype: int64

In [22]:
# Original tickers
original_tickers = selected_data["TICKER"].unique()

# # Filter the data to keep rows where TRDSTAT is 'A' or 'H'
# filtered_data = selected_data[selected_data['TRDSTAT'].isin(['A', 'H'])]

# Filtered tickers
filtered_tickers = filtered_data_1["TICKER"].unique()

# Identify tickers that were dropped
dropped_tickers = set(original_tickers) - set(filtered_tickers)

# Display the dropped tickers
print("Tickers that were dropped:")
print(dropped_tickers)

Tickers that were dropped:
{'SVA', 'QIWI', 'YNDX'}

In [23]:
original_tickers.shape

(10452,)

In [24]:
filtered_tickers.shape

(10449,)

In [25]:
filtered_data_1.isnull().any()

PERMNO      False
date        False
CUSIP       False
COMNAM      False
TICKER       True
NAICS        True
PRIMEXCH    False
RET          True
DLPDT        True
TRDSTAT     False
dtype: bool

In [26]:
see_filtered_data_1 = filtered_data_1.groupby("CUSIP")["TICKER"].value_counts(dropna=False).reset_index()
see_filtered_data_1

          CUSIP TICKER  count
0      00032Q10   AADI    250
1      00036020   AAON    250
2      00036110    AIR    250
3      00037520    ABB     97
4      00038020   ABCM    234
...         ...    ...    ...
10485  Y8897Y23   TOPS    250
10486  Y8900D10   TORO    206
10487  Y9233510   USEA    250
10488  Y9390M10    VFS     96
10489  Y9530810    WVE    250

[10490 rows x 3 columns]

In [27]:
see_filtered_data_1.loc[see_filtered_data_1["TICKER"].isnull() == 1].sort_values(by="count")

         CUSIP TICKER  count
6192  63011A10    NaN    250

In [28]:
filtered_data_1[filtered_data_1["CUSIP"] == "38942Q20"].sort_values(by="date")

,PERMNO,date,CUSIP,COMNAM,TICKER,NAICS,PRIMEXCH,RET,DLPDT,TRDSTAT
874549,19833,2023-01-03,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,0.140000,NaN,A
874550,19833,2023-01-04,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,0.140351,NaN,A
874551,19833,2023-01-05,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.030771,NaN,A
874552,19833,2023-01-06,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,0.015875,NaN,A
874553,19833,2023-01-09,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,0.000156,NaN,A
874554,19833,2023-01-10,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.015935,NaN,A
874555,19833,2023-01-11,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,0.017622,NaN,A
874556,19833,2023-01-12,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,0.053042,NaN,A
874557,19833,2023-01-13,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,0.037037,NaN,A
874558,19833,2023-01-17,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,0.042857,NaN,A
874559,19833,2023-01-18,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.049726,NaN,A
874560,19833,2023-01-19,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.018308,NaN,A
874561,19833,2023-01-20,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,0.056828,NaN,A
874562,19833,2023-01-23,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.003335,NaN,A
874563,19833,2023-01-24,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,0.003904,NaN,A
874564,19833,2023-01-25,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,0.041522,NaN,A
874565,19833,2023-01-26,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.035067,NaN,A
874566,19833,2023-01-27,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.060246,NaN,A
874567,19833,2023-01-30,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.036906,NaN,A
874568,19833,2023-01-31,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,0.043969,NaN,A
874569,19833,2023-02-01,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,0.038169,NaN,A
874570,19833,2023-02-02,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.007043,NaN,A
874571,19833,2023-02-03,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.072776,NaN,A
874572,19833,2023-02-06,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.016677,NaN,A
874573,19833,2023-02-07,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,0.011358,NaN,A
874574,19833,2023-02-08,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,0.061538,NaN,A
874575,19833,2023-02-09,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,0.018986,NaN,A
874576,19833,2023-02-10,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.009671,NaN,A
874577,19833,2023-02-13,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.055149,NaN,A
874578,19833,2023-02-14,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,0.048792,NaN,A
874579,19833,2023-02-15,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.018406,NaN,A
874580,19833,2023-02-16,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.062454,NaN,A
874581,19833,2023-02-17,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.011811,NaN,A
874582,19833,2023-02-21,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,0.004622,NaN,A
874583,19833,2023-02-22,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.014911,NaN,A
874584,19833,2023-02-23,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.010306,NaN,A
874585,19833,2023-02-24,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.027986,NaN,A
874586,19833,2023-02-27,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.045865,NaN,A
874587,19833,2023-02-28,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.035088,NaN,A
874588,19833,2023-03-01,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,0.009273,NaN,A
874589,19833,2023-03-02,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.000901,NaN,A
874590,19833,2023-03-03,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,0.048684,NaN,A
874591,19833,2023-03-06,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,0.031465,NaN,A
874592,19833,2023-03-07,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.033006,NaN,A
874593,19833,2023-03-08,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,0.016894,NaN,A
874594,19833,2023-03-09,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.067808,NaN,A
874595,19833,2023-03-10,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.018003,NaN,A
874596,19833,2023-03-13,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.054630,NaN,A
874597,19833,2023-03-14,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.040157,NaN,A
874598,19833,2023-03-15,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,0.036735,NaN,A
874599,19833,2023-03-16,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.023425,NaN,A
874600,19833,2023-03-17,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.112276,NaN,A
874601,19833,2023-03-20,38942Q20,GRAYBUG VISION INC,GRAY,339112.0,Q,-0.107953,NaN,A
874602,19833,2023-03-21,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.150909,NaN,A
874603,19833,2023-03-22,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.071880,NaN,A
874604,19833,2023-03-23,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.037447,NaN,A
874605,19833,2023-03-24,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.009726,NaN,A
874606,19833,2023-03-27,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.001751,NaN,A
874607,19833,2023-03-28,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.038596,NaN,A
874608,19833,2023-03-29,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.087591,NaN,A
874661,19833,2023-06-14,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,C,NaN,A
874662,19833,2023-06-15,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.078767,NaN,A
874663,19833,2023-06-16,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.065056,NaN,A
874664,19833,2023-06-20,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.047714,NaN,A
874665,19833,2023-06-21,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.226430,NaN,A
874666,19833,2023-06-22,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.041939,NaN,A
874667,19833,2023-06-23,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.067606,NaN,A
874668,19833,2023-06-26,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.014924,NaN,A
874669,19833,2023-06-27,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.279991,NaN,A
874670,19833,2023-06-28,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.009302,NaN,A
874671,19833,2023-06-29,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.117511,NaN,A
874672,19833,2023-06-30,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.173196,NaN,A
874673,19833,2023-07-03,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.019950,NaN,A
874674,19833,2023-07-05,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.130687,NaN,A
874675,19833,2023-07-06,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.099829,NaN,A
874676,19833,2023-07-07,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.035000,NaN,A
874677,19833,2023-07-10,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.044041,NaN,A
874678,19833,2023-07-11,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.024390,NaN,A
874679,19833,2023-07-12,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.070833,NaN,A
874680,19833,2023-07-13,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.040208,NaN,A
874681,19833,2023-07-14,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.005405,NaN,A
874682,19833,2023-07-17,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.051630,NaN,A
874683,19833,2023-07-18,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.055556,NaN,A
874684,19833,2023-07-19,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.012558,NaN,A
874685,19833,2023-07-20,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.002521,NaN,A
874686,19833,2023-07-21,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.030556,NaN,A
874687,19833,2023-07-24,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.029650,NaN,A
874688,19833,2023-07-25,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.061111,NaN,A
874689,19833,2023-07-26,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.029586,NaN,A
874690,19833,2023-07-27,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.005718,NaN,A
874691,19833,2023-07-28,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.010029,NaN,A
874692,19833,2023-07-31,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.009901,NaN,A
874693,19833,2023-08-01,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.062857,NaN,A
874694,19833,2023-08-02,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.006098,NaN,A
874695,19833,2023-08-03,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.040491,NaN,A
874696,19833,2023-08-04,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.007353,NaN,A
874697,19833,2023-08-07,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.040178,NaN,A
874698,19833,2023-08-08,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.010465,NaN,A
874699,19833,2023-08-09,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.060648,NaN,A
874700,19833,2023-08-10,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.046512,NaN,A
874701,19833,2023-08-11,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.003628,NaN,A
874702,19833,2023-08-14,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.020838,NaN,A
874703,19833,2023-08-15,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.015625,NaN,A
874704,19833,2023-08-16,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.013538,NaN,A
874705,19833,2023-08-17,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.016843,NaN,A
874706,19833,2023-08-18,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.020337,NaN,A
874707,19833,2023-08-21,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.003632,NaN,A
874708,19833,2023-08-22,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.034097,NaN,A
874709,19833,2023-08-23,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.010819,NaN,A
874710,19833,2023-08-24,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.016897,NaN,A
874711,19833,2023-08-25,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.015625,NaN,A
874712,19833,2023-08-28,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.009524,NaN,A
874713,19833,2023-08-29,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.006378,NaN,A
874714,19833,2023-08-30,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.038122,NaN,A
874715,19833,2023-08-31,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.009900,NaN,A
874716,19833,2023-09-01,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.053834,NaN,A
874717,19833,2023-09-05,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.038671,NaN,A
874718,19833,2023-09-06,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.051780,NaN,A
874719,19833,2023-09-07,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.030769,NaN,A
874720,19833,2023-09-08,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.071642,NaN,A
874721,19833,2023-09-11,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.033762,NaN,A
874722,19833,2023-09-12,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.021866,NaN,A
874723,19833,2023-09-13,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.001613,NaN,A
874724,19833,2023-09-14,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.024390,NaN,A
874725,19833,2023-09-15,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.047619,NaN,A
874726,19833,2023-09-18,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.009063,NaN,A
874727,19833,2023-09-19,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.022390,NaN,A
874728,19833,2023-09-20,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.138710,NaN,A
874729,19833,2023-09-21,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.029963,NaN,A
874730,19833,2023-09-22,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.040000,NaN,A
874731,19833,2023-09-25,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.018977,NaN,A
874732,19833,2023-09-26,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.018624,NaN,A
874733,19833,2023-09-27,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.047727,NaN,A
874734,19833,2023-09-28,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.013015,NaN,A
874735,19833,2023-09-29,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.025824,NaN,A
874736,19833,2023-10-02,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.063734,NaN,A
874737,19833,2023-10-03,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.003815,NaN,A
874738,19833,2023-10-04,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.002200,NaN,A
874739,19833,2023-10-05,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.041916,NaN,A
874740,19833,2023-10-06,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.037500,NaN,A
874741,19833,2023-10-09,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.047619,NaN,A
874742,19833,2023-10-10,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.078512,NaN,A
874743,19833,2023-10-11,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.010986,NaN,A
874744,19833,2023-10-12,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.107474,NaN,A
874745,19833,2023-10-13,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.043683,NaN,A
874746,19833,2023-10-16,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.047569,NaN,A
874747,19833,2023-10-17,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.000000,NaN,A
874748,19833,2023-10-18,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.040409,NaN,A
874749,19833,2023-10-19,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.191751,NaN,A
874750,19833,2023-10-20,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.010811,NaN,A
874751,19833,2023-10-23,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.048128,NaN,A
874752,19833,2023-10-24,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.011236,NaN,A
874753,19833,2023-10-25,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.159091,NaN,A
874754,19833,2023-10-26,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.049020,NaN,A
874755,19833,2023-10-27,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.042056,NaN,A
874756,19833,2023-10-30,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.049283,NaN,A
874757,19833,2023-10-31,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.059789,NaN,A
874758,19833,2023-11-01,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.022727,NaN,A
874759,19833,2023-11-02,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.102325,NaN,A
874760,19833,2023-11-03,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.202532,NaN,A
874761,19833,2023-11-06,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.122842,NaN,A
874762,19833,2023-11-07,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.015562,NaN,A
874763,19833,2023-11-08,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.110803,NaN,A
874764,19833,2023-11-09,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.127424,NaN,A
874765,19833,2023-11-10,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.070984,NaN,A
874766,19833,2023-11-13,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.007825,NaN,A
874767,19833,2023-11-14,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.000500,NaN,A
874768,19833,2023-11-15,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.031516,NaN,A
874769,19833,2023-11-16,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.041479,NaN,A
874770,19833,2023-11-17,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.035714,NaN,A
874771,19833,2023-11-20,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.102184,NaN,A
874772,19833,2023-11-21,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.011010,NaN,A
874773,19833,2023-11-22,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.022654,NaN,A
874774,19833,2023-11-24,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.065475,NaN,A
874775,19833,2023-11-27,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.048442,NaN,A
874776,19833,2023-11-28,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.172805,NaN,A
874777,19833,2023-11-29,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.031401,NaN,A
874778,19833,2023-11-30,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.034913,NaN,A
874779,19833,2023-12-01,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.052988,NaN,A
874780,19833,2023-12-04,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.160327,NaN,A
874781,19833,2023-12-05,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.043030,NaN,A
874782,19833,2023-12-06,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.015107,NaN,A
874783,19833,2023-12-07,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.001475,NaN,A
874784,19833,2023-12-08,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.149188,NaN,A
874785,19833,2023-12-11,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.138818,NaN,A
874786,19833,2023-12-12,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.101493,NaN,A
874787,19833,2023-12-13,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.083056,NaN,A
874788,19833,2023-12-14,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.021472,NaN,A
874789,19833,2023-12-15,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.034483,NaN,A
874790,19833,2023-12-18,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.064513,NaN,A
874791,19833,2023-12-19,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.042303,NaN,A
874792,19833,2023-12-20,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.022962,NaN,A
874793,19833,2023-12-21,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.032433,NaN,A
874794,19833,2023-12-22,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.027490,NaN,A
874795,19833,2023-12-26,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.016393,NaN,A
874796,19833,2023-12-27,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.033333,NaN,A
874797,19833,2023-12-28,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,0.010345,NaN,A
874798,19833,2023-12-29,38942Q20,CALCIMEDICA INC,CALC,339112.0,Q,-0.023891,NaN,A

### Filtered Tickers by DLPDT

In [29]:
filtered_data_1.groupby("TICKER")["DLPDT"].value_counts(dropna=False)

TICKER  DLPDT
A       NaN           250
AA      NaN           250
AAA     NaN           250
AAAU    NaN           250
AAC     NaN           213
                     ...
ZYME    NaN           250
ZYNE    NaN           195
        2023-10-11      1
ZYXI    NaN           250
ZZZ     NaN             2
Name: count, Length: 11321, dtype: int64

In [30]:
filtered_data_1[filtered_data_1["TICKER"] == "ZYNE"]["DLPDT"]

350321           NaN
350322           NaN
350323           NaN
350324           NaN
350325           NaN
350326           NaN
350327           NaN
350328           NaN
350329           NaN
350330           NaN
350331           NaN
350332           NaN
350333           NaN
350334           NaN
350335           NaN
350336           NaN
350337           NaN
350338           NaN
350339           NaN
350340           NaN
350341           NaN
350342           NaN
350343           NaN
350344           NaN
350345           NaN
350346           NaN
350347           NaN
350348           NaN
350349           NaN
350350           NaN
350351           NaN
350352           NaN
350353           NaN
350354           NaN
350355           NaN
350356           NaN
350357           NaN
350358           NaN
350359           NaN
350360           NaN
350361           NaN
350362           NaN
350363           NaN
350364           NaN
350365           NaN
350366           NaN
350367           NaN
350368           NaN
350369           NaN
350370           NaN
350371           NaN
350372           NaN
350373           NaN
350374           NaN
350375           NaN
350376           NaN
350377           NaN
350378           NaN
350379           NaN
350380           NaN
350381           NaN
350382           NaN
350383           NaN
350384           NaN
350385           NaN
350386           NaN
350387           NaN
350388           NaN
350389           NaN
350390           NaN
350391           NaN
350392           NaN
350393           NaN
350394           NaN
350395           NaN
350396           NaN
350397           NaN
350398           NaN
350399           NaN
350400           NaN
350401           NaN
350402           NaN
350403           NaN
350404           NaN
350405           NaN
350406           NaN
350407           NaN
350408           NaN
350409           NaN
350410           NaN
350411           NaN
350412           NaN
350413           NaN
350414           NaN
350415           NaN
350416           NaN
350417           NaN
350418           NaN
350419           NaN
350420           NaN
350421           NaN
350422           NaN
350423           NaN
350424           NaN
350425           NaN
350426           NaN
350427           NaN
350428           NaN
350429           NaN
350430           NaN
350431           NaN
350432           NaN
350433           NaN
350434           NaN
350435           NaN
350436           NaN
350437           NaN
350438           NaN
350439           NaN
350440           NaN
350441           NaN
350442           NaN
350443           NaN
350444           NaN
350445           NaN
350446           NaN
350447           NaN
350448           NaN
350449           NaN
350450           NaN
350451           NaN
350452           NaN
350453           NaN
350454           NaN
350455           NaN
350456           NaN
350457           NaN
350458           NaN
350459           NaN
350460           NaN
350461           NaN
350462           NaN
350463           NaN
350464           NaN
350465           NaN
350466           NaN
350467           NaN
350468           NaN
350469           NaN
350470           NaN
350471           NaN
350472           NaN
350473           NaN
350474           NaN
350475           NaN
350476           NaN
350477           NaN
350478           NaN
350479           NaN
350480           NaN
350481           NaN
350482           NaN
350483           NaN
350484           NaN
350485           NaN
350486           NaN
350487           NaN
350488           NaN
350489           NaN
350490           NaN
350491           NaN
350492           NaN
350493           NaN
350494           NaN
350495           NaN
350496           NaN
350497           NaN
350498           NaN
350499           NaN
350500           NaN
350501           NaN
350502           NaN
350503           NaN
350504           NaN
350505           NaN
350506           NaN
350507           NaN
350508           NaN
350509           NaN
350510           NaN
350511           NaN
350512           NaN
350513           NaN
350514    2023-10-11
350515           NaN
350516           NaN
Name: DLPDT, dtype: object

In [31]:
# Identify tickers that have a non-null DLPDT (i.e., delisted)
delisted_tickers = filtered_data_1[filtered_data_1["DLPDT"].notna()]["TICKER"].unique()

# Filter out rows with these delisted tickers
filtered_data_2 = filtered_data_1[~filtered_data_1["TICKER"].isin(delisted_tickers)]

# Display the filtered data
filtered_data_2.groupby("TICKER")["DLPDT"].value_counts(dropna=False)

TICKER  DLPDT
A       NaN      250
AA      NaN      250
AAA     NaN      250
AAAU    NaN      250
AACG    NaN      250
                ...
ZVSA    NaN      250
ZWS     NaN      250
ZYME    NaN      250
ZYXI    NaN      250
ZZZ     NaN        2
Name: count, Length: 9574, dtype: int64

In [32]:
# TICKER == ZYNE has been removed from filtered_data_2
filtered_data_2[filtered_data_2["TICKER"] == "ZYNE"]

Empty DataFrame
Columns: [PERMNO, date, CUSIP, COMNAM, TICKER, NAICS, PRIMEXCH, RET, DLPDT, TRDSTAT]
Index: []

In [33]:
filtered_data_2.isnull().any()

PERMNO      False
date        False
CUSIP       False
COMNAM      False
TICKER       True
NAICS        True
PRIMEXCH    False
RET          True
DLPDT        True
TRDSTAT     False
dtype: bool

In [34]:
print(
    "Check on columns having missing values:\n",
    filtered_data_2.isna().sum()[filtered_data_2.isna().sum() > 0],
)
print(
    "Check on columns having null values:\n",
    filtered_data_2.isnull().sum()[filtered_data_2.isnull().sum() > 0],
)

Check on columns having missing values:
 TICKER        250
NAICS        8042
RET            94
DLPDT     2239398
dtype: int64
Check on columns having null values:
 TICKER        250
NAICS        8042
RET            94
DLPDT     2239398
dtype: int64

## Imputation for Missing Values

### TIKCER

In [35]:
see_filtered_data_2 = filtered_data_2.groupby("CUSIP")["TICKER"].value_counts(dropna=False).reset_index()
see_filtered_data_2

         CUSIP TICKER  count
0     00032Q10   AADI    250
1     00036020   AAON    250
2     00036110    AIR    250
3     00037520    ABB     97
4     00039J10   YEAR    250
...        ...    ...    ...
9593  Y8897Y23   TOPS    250
9594  Y8900D10   TORO    206
9595  Y9233510   USEA    250
9596  Y9390M10    VFS     96
9597  Y9530810    WVE    250

[9598 rows x 3 columns]

In [36]:
see_filtered_data_2.loc[see_filtered_data_2["TICKER"].isnull() == 1].sort_values(by="count")

         CUSIP TICKER  count
5704  63011A10    NaN    250

In [37]:
filtered_data_2[filtered_data_2["CUSIP"] == "63011A10"]["TICKER"].value_counts(dropna=False)

TICKER
NaN    250
Name: count, dtype: int64

In [38]:
filtered_data_2[filtered_data_2["CUSIP"] == "63011A10"]["COMNAM"].value_counts(dropna=False)

COMNAM
NANO LABS LTD    250
Name: count, dtype: int64

In [39]:
filtered_data_2.groupby("CUSIP")["TICKER"].value_counts(dropna=False)

CUSIP     TICKER
00032Q10  AADI      250
00036020  AAON      250
00036110  AIR       250
00037520  ABB        97
00039J10  YEAR      250
                   ...
Y8897Y23  TOPS      250
Y8900D10  TORO      206
Y9233510  USEA      250
Y9390M10  VFS        96
Y9530810  WVE       250
Name: count, Length: 9598, dtype: int64

In [40]:
# Count the number of unique CUSIPs
num_unique_cusip = filtered_data_2["CUSIP"].nunique()
print(f"Number of unique CUSIPs: {num_unique_cusip}")

# Count the number of unique TICKERs
num_unique_ticker = filtered_data_2["TICKER"].nunique()
print(f"Number of unique TICKERs: {num_unique_ticker}")

# Check for multiple TICKERs for the same CUSIP
cusip_ticker_count = filtered_data_2.groupby("CUSIP")["TICKER"].nunique()
multiple_ticker_cusips = cusip_ticker_count[cusip_ticker_count > 1]
print("CUSIPs with multiple TICKERs:")
print(multiple_ticker_cusips)

# Check the number of missing TICKER values
num_missing_ticker = filtered_data_2["TICKER"].isna().sum()
print(f"Number of missing TICKER values: {num_missing_ticker}")

# Display rows with missing TICKER values
missing_ticker_rows = filtered_data_2[filtered_data_2["TICKER"].isna()]
print("Rows with missing TICKER values:")
print(missing_ticker_rows)

Number of unique CUSIPs: 9415
Number of unique TICKERs: 9574
CUSIPs with multiple TICKERs:
CUSIP
00258Y10    2
00445F10    2
00547W30    2
00773710    2
00773J20    2
00791X10    2
00792J10    2
00810J10    2
00894010    2
01861F10    2
01933010    2
02157E10    2
02157G10    2
02369M10    2
02871910    2
03073E10    2
03635R20    2
05479K10    2
06682J10    2
08774B10    2
08892910    2
09073Q20    2
09174P10    2
09610B10    2
14167R10    2
14216R10    2
14292210    2
15713L10    2
17166A10    2
17240630    2
19200310    2
19200A20    2
19393910    2
19423L52    2
20460L10    2
20678X10    2
22002T10    2
22444110    2
22890A20    2
23248B10    2
25282810    2
26205E10    2
26922B70    2
27877D10    2
27888N40    3
28504610    2
28657F10    2
29337E10    2
29350E10    2
29415V10    2
29604W20    2
29758410    2
32070310    2
33738R73    2
33773810    2
34392810    2
35473M10    2
35473P64    2
3622AW10    2
37229T50    2
37892P10    2
38747R60    2
38942Q20    2
40378310    2
41586410    2
43270520    2
44267T10    2
45095810    2
45694810    2
45765Y20    2
45784G10    2
46125A10    2
46137V22    2
46137V27    2
46137V28    2
46137V29    2
46137V31    2
46137V32    2
46137V33    2
46137V34    2
46137V36    2
46137V37    2
46137V38    2
46137V63    2
46137V68    2
46137V69    2
46137V71    2
46137Y60    2
46138E10    2
46138G88    2
46138J77    2
46428753    2
46434V31    2
46489V10    2
46641Q24    2
46641Q44    2
46641Q87    2
47714H10    2
48208F10    2
48844520    2
50094610    2
51655R10    2
51680620    2
52328E10    2
53656G49    2
53681K10    2
55328R10    2
55826T10    2
56146T10    2
57313410    2
58600110    2
58938110    2
59564R70    2
60739N10    2
60743G10    2
62459N10    2
62733310    2
62886E10    2
62898810    2
62956D20    2
63910B10    2
64107A10    2
64135M10    2
65488A10    2
67021W10    2
67054R10    2
67644C10    2
68270C10    2
68572M10    2
68621T10    2
69037010    2
69121K10    2
69369110    2
70021530    2
71404610    2
74280R30    2
74349W10    2
74933X30    2
75989230    2
76009N10    2
78643B50    2
80688210    2
81621210    2
81663L20    2
84445C10    2
84753T10    2
84757T10    2
86804F30    2
87169M10    2
87250W30    2
87256C10    2
87654510    2
88636479    2
88636481    2
88675P10    2
89157D10    2
89680M10    2
91060H10    2
91071010    2
91864C10    2
92337210    2
92535C10    2
92790A20    2
92838F10    2
98147510    2
98400V10    2
98873Q10    2
G0136H10    2
G1144D12    2
G3223R10    2
G3997320    2
G4289N20    2
G5280710    2
G6055H15    2
G6360J10    2
G6S34K10    2
G7606H10    2
G8572710    2
G9411M10    2
G9831X10    2
G9TY5A10    2
M7517R10    2
Name: TICKER, dtype: int64
Number of missing TICKER values: 250
Rows with missing TICKER values:
         PERMNO        date     CUSIP         COMNAM TICKER     NAICS  \
1401928   23234  2023-01-03  63011A10  NANO LABS LTD    NaN  334413.0
1401929   23234  2023-01-04  63011A10  NANO LABS LTD    NaN  334413.0
1401930   23234  2023-01-05  63011A10  NANO LABS LTD    NaN  334413.0
1401931   23234  2023-01-06  63011A10  NANO LABS LTD    NaN  334413.0
1401932   23234  2023-01-09  63011A10  NANO LABS LTD    NaN  334413.0
1401933   23234  2023-01-10  63011A10  NANO LABS LTD    NaN  334413.0
1401934   23234  2023-01-11  63011A10  NANO LABS LTD    NaN  334413.0
1401935   23234  2023-01-12  63011A10  NANO LABS LTD    NaN  334413.0
1401936   23234  2023-01-13  63011A10  NANO LABS LTD    NaN  334413.0
1401937   23234  2023-01-17  63011A10  NANO LABS LTD    NaN  334413.0
1401938   23234  2023-01-18  63011A10  NANO LABS LTD    NaN  334413.0
1401939   23234  2023-01-19  63011A10  NANO LABS LTD    NaN  334413.0
1401940   23234  2023-01-20  63011A10  NANO LABS LTD    NaN  334413.0
1401941   23234  2023-01-23  63011A10  NANO LABS LTD    NaN  334413.0
1401942   23234  2023-01-24  63011A10  NANO LABS LTD    NaN  334413.0
1401943   23234  2023-01-25  63011A10  NANO LABS LTD    NaN  334413.0
1401944   23234  2023-01-26  63011A10  NANO LABS LTD    NaN  334413.0
1401945   23234  2023-01-27  63011A10  NANO LABS LTD    NaN  334413.0
1401946   23234  2023-01-30  63011A10  NANO LABS LTD    NaN  334413.0
1401947   23234  2023-01-31  63011A10  NANO LABS LTD    NaN  334413.0
1401948   23234  2023-02-01  63011A10  NANO LABS LTD    NaN  334413.0
1401949   23234  2023-02-02  63011A10  NANO LABS LTD    NaN  334413.0
1401950   23234  2023-02-03  63011A10  NANO LABS LTD    NaN  334413.0
1401951   23234  2023-02-06  63011A10  NANO LABS LTD    NaN  334413.0
1401952   23234  2023-02-07  63011A10  NANO LABS LTD    NaN  334413.0
1401953   23234  2023-02-08  63011A10  NANO LABS LTD    NaN  334413.0
1401954   23234  2023-02-09  63011A10  NANO LABS LTD    NaN  334413.0
1401955   23234  2023-02-10  63011A10  NANO LABS LTD    NaN  334413.0
1401956   23234  2023-02-13  63011A10  NANO LABS LTD    NaN  334413.0
1401957   23234  2023-02-14  63011A10  NANO LABS LTD    NaN  334413.0
1401958   23234  2023-02-15  63011A10  NANO LABS LTD    NaN  334413.0
1401959   23234  2023-02-16  63011A10  NANO LABS LTD    NaN  334413.0
1401960   23234  2023-02-17  63011A10  NANO LABS LTD    NaN  334413.0
1401961   23234  2023-02-21  63011A10  NANO LABS LTD    NaN  334413.0
1401962   23234  2023-02-22  63011A10  NANO LABS LTD    NaN  334413.0
1401963   23234  2023-02-23  63011A10  NANO LABS LTD    NaN  334413.0
1401964   23234  2023-02-24  63011A10  NANO LABS LTD    NaN  334413.0
1401965   23234  2023-02-27  63011A10  NANO LABS LTD    NaN  334413.0
1401966   23234  2023-02-28  63011A10  NANO LABS LTD    NaN  334413.0
1401967   23234  2023-03-01  63011A10  NANO LABS LTD    NaN  334413.0
1401968   23234  2023-03-02  63011A10  NANO LABS LTD    NaN  334413.0
1401969   23234  2023-03-03  63011A10  NANO LABS LTD    NaN  334413.0
1401970   23234  2023-03-06  63011A10  NANO LABS LTD    NaN  334413.0
1401971   23234  2023-03-07  63011A10  NANO LABS LTD    NaN  334413.0
1401972   23234  2023-03-08  63011A10  NANO LABS LTD    NaN  334413.0
1401973   23234  2023-03-09  63011A10  NANO LABS LTD    NaN  334413.0
1401974   23234  2023-03-10  63011A10  NANO LABS LTD    NaN  334413.0
1401975   23234  2023-03-13  63011A10  NANO LABS LTD    NaN  334413.0
1401976   23234  2023-03-14  63011A10  NANO LABS LTD    NaN  334413.0
1401977   23234  2023-03-15  63011A10  NANO LABS LTD    NaN  334413.0
1401978   23234  2023-03-16  63011A10  NANO LABS LTD    NaN  334413.0
1401979   23234  2023-03-17  63011A10  NANO LABS LTD    NaN  334413.0
1401980   23234  2023-03-20  63011A10  NANO LABS LTD    NaN  334413.0
1401981   23234  2023-03-21  63011A10  NANO LABS LTD    NaN  334413.0
1401982   23234  2023-03-22  63011A10  NANO LABS LTD    NaN  334413.0
1401983   23234  2023-03-23  63011A10  NANO LABS LTD    NaN  334413.0
1401984   23234  2023-03-24  63011A10  NANO LABS LTD    NaN  334413.0
1401985   23234  2023-03-27  63011A10  NANO LABS LTD    NaN  334413.0
1401986   23234  2023-03-28  63011A10  NANO LABS LTD    NaN  334413.0
1401987   23234  2023-03-29  63011A10  NANO LABS LTD    NaN  334413.0
1401988   23234  2023-03-30  63011A10  NANO LABS LTD    NaN  334413.0
1401989   23234  2023-03-31  63011A10  NANO LABS LTD    NaN  334413.0
1401990   23234  2023-04-03  63011A10  NANO LABS LTD    NaN  334413.0
1401991   23234  2023-04-04  63011A10  NANO LABS LTD    NaN  334413.0
1401992   23234  2023-04-05  63011A10  NANO LABS LTD    NaN  334413.0
1401993   23234  2023-04-06  63011A10  NANO LABS LTD    NaN  334413.0
1401994   23234  2023-04-10  63011A10  NANO LABS LTD    NaN  334413.0
1401995   23234  2023-04-11  63011A10  NANO LABS LTD    NaN  334413.0
1401996   23234  2023-04-12  63011A10  NANO LABS LTD    NaN  334413.0
1401997   23234  2023-04-13  63011A10  NANO LABS LTD    NaN  334413.0
1401998   23234  2023-04-14  63011A10  NANO LABS LTD    NaN  334413.0
1401999   23234  2023-04-17  63011A10  NANO LABS LTD    NaN  334413.0
1402000   23234  2023-04-18  63011A10  NANO LABS LTD    NaN  334413.0
1402001   23234  2023-04-19  63011A10  NANO LABS LTD    NaN  334413.0
1402002   23234  2023-04-20  63011A10  NANO LABS LTD    NaN  334413.0
1402003   23234  2023-04-21  63011A10  NANO LABS LTD    NaN  334413.0
1402004   23234  2023-04-24  63011A10  NANO LABS LTD    NaN  334413.0
1402005   23234  2023-04-25  63011A10  NANO LABS LTD    NaN  334413.0
1402006   23234  2023-04-26  63011A10  NANO LABS LTD    NaN  334413.0
1402007   23234  2023-04-27  63011A10  NANO LABS LTD    NaN  334413.0
1402008   23234  2023-04-28  63011A10  NANO LABS LTD    NaN  334413.0
1402009   23234  2023-05-01  63011A10  NANO LABS LTD    NaN  334413.0
1402010   23234  2023-05-02  63011A10  NANO LABS LTD    NaN  334413.0
1402011   23234  2023-05-03  63011A10  NANO LABS LTD    NaN  334413.0
1402012   23234  2023-05-04  63011A10  NANO LABS LTD    NaN  334413.0
1402013   23234  2023-05-05  63011A10  NANO LABS LTD    NaN  334413.0
1402014   23234  2023-05-08  63011A10  NANO LABS LTD    NaN  334413.0
1402015   23234  2023-05-09  63011A10  NANO LABS LTD    NaN  334413.0
1402016   23234  2023-05-10  63011A10  NANO LABS LTD    NaN  334413.0
1402017   23234  2023-05-11  63011A10  NANO LABS LTD    NaN  334413.0
1402018   23234  2023-05-12  63011A10  NANO LABS LTD    NaN  334413.0
1402019   23234  2023-05-15  63011A10  NANO LABS LTD    NaN  334413.0
1402020   23234  2023-05-16  63011A10  NANO LABS LTD    NaN  334413.0
1402021   23234  2023-05-17  63011A10  NANO LABS LTD    NaN  334413.0
1402022   23234  2023-05-18  63011A10  NANO LABS LTD    NaN  334413.0
1402023   23234  2023-05-19  63011A10  NANO LABS LTD    NaN  334413.0
1402024   23234  2023-05-22  63011A10  NANO LABS LTD    NaN  334413.0
1402025   23234  2023-05-23  63011A10  NANO LABS LTD    NaN  334413.0
1402026   23234  2023-05-24  63011A10  NANO LABS LTD    NaN  334413.0
1402027   23234  2023-05-25  63011A10  NANO LABS LTD    NaN  334413.0
1402028   23234  2023-05-26  63011A10  NANO LABS LTD    NaN  334413.0
1402029   23234  2023-05-30  63011A10  NANO LABS LTD    NaN  334413.0
1402030   23234  2023-05-31  63011A10  NANO LABS LTD    NaN  334413.0
1402031   23234  2023-06-01  63011A10  NANO LABS LTD    NaN  334413.0
1402032   23234  2023-06-02  63011A10  NANO LABS LTD    NaN  334413.0
1402033   23234  2023-06-05  63011A10  NANO LABS LTD    NaN  334413.0
1402034   23234  2023-06-06  63011A10  NANO LABS LTD    NaN  334413.0
1402035   23234  2023-06-07  63011A10  NANO LABS LTD    NaN  334413.0
1402036   23234  2023-06-08  63011A10  NANO LABS LTD    NaN  334413.0
1402037   23234  2023-06-09  63011A10  NANO LABS LTD    NaN  334413.0
1402038   23234  2023-06-12  63011A10  NANO LABS LTD    NaN  334413.0
1402039   23234  2023-06-13  63011A10  NANO LABS LTD    NaN  334413.0
1402040   23234  2023-06-14  63011A10  NANO LABS LTD    NaN  334413.0
1402041   23234  2023-06-15  63011A10  NANO LABS LTD    NaN  334413.0
1402042   23234  2023-06-16  63011A10  NANO LABS LTD    NaN  334413.0
1402043   23234  2023-06-20  63011A10  NANO LABS LTD    NaN  334413.0
1402044   23234  2023-06-21  63011A10  NANO LABS LTD    NaN  334413.0
1402045   23234  2023-06-22  63011A10  NANO LABS LTD    NaN  334413.0
1402046   23234  2023-06-23  63011A10  NANO LABS LTD    NaN  334413.0
1402047   23234  2023-06-26  63011A10  NANO LABS LTD    NaN  334413.0
1402048   23234  2023-06-27  63011A10  NANO LABS LTD    NaN  334413.0
1402049   23234  2023-06-28  63011A10  NANO LABS LTD    NaN  334413.0
1402050   23234  2023-06-29  63011A10  NANO LABS LTD    NaN  334413.0
1402051   23234  2023-06-30  63011A10  NANO LABS LTD    NaN  334413.0
1402052   23234  2023-07-03  63011A10  NANO LABS LTD    NaN  334413.0
1402053   23234  2023-07-05  63011A10  NANO LABS LTD    NaN  334413.0
1402054   23234  2023-07-06  63011A10  NANO LABS LTD    NaN  334413.0
1402055   23234  2023-07-07  63011A10  NANO LABS LTD    NaN  334413.0
1402056   23234  2023-07-10  63011A10  NANO LABS LTD    NaN  334413.0
1402057   23234  2023-07-11  63011A10  NANO LABS LTD    NaN  334413.0
1402058   23234  2023-07-12  63011A10  NANO LABS LTD    NaN  334413.0
1402059   23234  2023-07-13  63011A10  NANO LABS LTD    NaN  334413.0
1402060   23234  2023-07-14  63011A10  NANO LABS LTD    NaN  334413.0
1402061   23234  2023-07-17  63011A10  NANO LABS LTD    NaN  334413.0
1402062   23234  2023-07-18  63011A10  NANO LABS LTD    NaN  334413.0
1402063   23234  2023-07-19  63011A10  NANO LABS LTD    NaN  334413.0
1402064   23234  2023-07-20  63011A10  NANO LABS LTD    NaN  334413.0
1402065   23234  2023-07-21  63011A10  NANO LABS LTD    NaN  334413.0
1402066   23234  2023-07-24  63011A10  NANO LABS LTD    NaN  334413.0
1402067   23234  2023-07-25  63011A10  NANO LABS LTD    NaN  334413.0
1402068   23234  2023-07-26  63011A10  NANO LABS LTD    NaN  334413.0
1402069   23234  2023-07-27  63011A10  NANO LABS LTD    NaN  334413.0
1402070   23234  2023-07-28  63011A10  NANO LABS LTD    NaN  334413.0
1402071   23234  2023-07-31  63011A10  NANO LABS LTD    NaN  334413.0
1402072   23234  2023-08-01  63011A10  NANO LABS LTD    NaN  334413.0
1402073   23234  2023-08-02  63011A10  NANO LABS LTD    NaN  334413.0
1402074   23234  2023-08-03  63011A10  NANO LABS LTD    NaN  334413.0
1402075   23234  2023-08-04  63011A10  NANO LABS LTD    NaN  334413.0
1402076   23234  2023-08-07  63011A10  NANO LABS LTD    NaN  334413.0
1402077   23234  2023-08-08  63011A10  NANO LABS LTD    NaN  334413.0
1402078   23234  2023-08-09  63011A10  NANO LABS LTD    NaN  334413.0
1402079   23234  2023-08-10  63011A10  NANO LABS LTD    NaN  334413.0
1402080   23234  2023-08-11  63011A10  NANO LABS LTD    NaN  334413.0
1402081   23234  2023-08-14  63011A10  NANO LABS LTD    NaN  334413.0
1402082   23234  2023-08-15  63011A10  NANO LABS LTD    NaN  334413.0
1402083   23234  2023-08-16  63011A10  NANO LABS LTD    NaN  334413.0
1402084   23234  2023-08-17  63011A10  NANO LABS LTD    NaN  334413.0
1402085   23234  2023-08-18  63011A10  NANO LABS LTD    NaN  334413.0
1402086   23234  2023-08-21  63011A10  NANO LABS LTD    NaN  334413.0
1402087   23234  2023-08-22  63011A10  NANO LABS LTD    NaN  334413.0
1402088   23234  2023-08-23  63011A10  NANO LABS LTD    NaN  334413.0
1402089   23234  2023-08-24  63011A10  NANO LABS LTD    NaN  334413.0
1402090   23234  2023-08-25  63011A10  NANO LABS LTD    NaN  334413.0
1402091   23234  2023-08-28  63011A10  NANO LABS LTD    NaN  334413.0
1402092   23234  2023-08-29  63011A10  NANO LABS LTD    NaN  334413.0
1402093   23234  2023-08-30  63011A10  NANO LABS LTD    NaN  334413.0
1402094   23234  2023-08-31  63011A10  NANO LABS LTD    NaN  334413.0
1402095   23234  2023-09-01  63011A10  NANO LABS LTD    NaN  334413.0
1402096   23234  2023-09-05  63011A10  NANO LABS LTD    NaN  334413.0
1402097   23234  2023-09-06  63011A10  NANO LABS LTD    NaN  334413.0
1402098   23234  2023-09-07  63011A10  NANO LABS LTD    NaN  334413.0
1402099   23234  2023-09-08  63011A10  NANO LABS LTD    NaN  334413.0
1402100   23234  2023-09-11  63011A10  NANO LABS LTD    NaN  334413.0
1402101   23234  2023-09-12  63011A10  NANO LABS LTD    NaN  334413.0
1402102   23234  2023-09-13  63011A10  NANO LABS LTD    NaN  334413.0
1402103   23234  2023-09-14  63011A10  NANO LABS LTD    NaN  334413.0
1402104   23234  2023-09-15  63011A10  NANO LABS LTD    NaN  334413.0
1402105   23234  2023-09-18  63011A10  NANO LABS LTD    NaN  334413.0
1402106   23234  2023-09-19  63011A10  NANO LABS LTD    NaN  334413.0
1402107   23234  2023-09-20  63011A10  NANO LABS LTD    NaN  334413.0
1402108   23234  2023-09-21  63011A10  NANO LABS LTD    NaN  334413.0
1402109   23234  2023-09-22  63011A10  NANO LABS LTD    NaN  334413.0
1402110   23234  2023-09-25  63011A10  NANO LABS LTD    NaN  334413.0
1402111   23234  2023-09-26  63011A10  NANO LABS LTD    NaN  334413.0
1402112   23234  2023-09-27  63011A10  NANO LABS LTD    NaN  334413.0
1402113   23234  2023-09-28  63011A10  NANO LABS LTD    NaN  334413.0
1402114   23234  2023-09-29  63011A10  NANO LABS LTD    NaN  334413.0
1402115   23234  2023-10-02  63011A10  NANO LABS LTD    NaN  334413.0
1402116   23234  2023-10-03  63011A10  NANO LABS LTD    NaN  334413.0
1402117   23234  2023-10-04  63011A10  NANO LABS LTD    NaN  334413.0
1402118   23234  2023-10-05  63011A10  NANO LABS LTD    NaN  334413.0
1402119   23234  2023-10-06  63011A10  NANO LABS LTD    NaN  334413.0
1402120   23234  2023-10-09  63011A10  NANO LABS LTD    NaN  334413.0
1402121   23234  2023-10-10  63011A10  NANO LABS LTD    NaN  334413.0
1402122   23234  2023-10-11  63011A10  NANO LABS LTD    NaN  334413.0
1402123   23234  2023-10-12  63011A10  NANO LABS LTD    NaN  334413.0
1402124   23234  2023-10-13  63011A10  NANO LABS LTD    NaN  334413.0
1402125   23234  2023-10-16  63011A10  NANO LABS LTD    NaN  334413.0
1402126   23234  2023-10-17  63011A10  NANO LABS LTD    NaN  334413.0
1402127   23234  2023-10-18  63011A10  NANO LABS LTD    NaN  334413.0
1402128   23234  2023-10-19  63011A10  NANO LABS LTD    NaN  334413.0
1402129   23234  2023-10-20  63011A10  NANO LABS LTD    NaN  334413.0
1402130   23234  2023-10-23  63011A10  NANO LABS LTD    NaN  334413.0
1402131   23234  2023-10-24  63011A10  NANO LABS LTD    NaN  334413.0
1402132   23234  2023-10-25  63011A10  NANO LABS LTD    NaN  334413.0
1402133   23234  2023-10-26  63011A10  NANO LABS LTD    NaN  334413.0
1402134   23234  2023-10-27  63011A10  NANO LABS LTD    NaN  334413.0
1402135   23234  2023-10-30  63011A10  NANO LABS LTD    NaN  334413.0
1402136   23234  2023-10-31  63011A10  NANO LABS LTD    NaN  334413.0
1402137   23234  2023-11-01  63011A10  NANO LABS LTD    NaN  334413.0
1402138   23234  2023-11-02  63011A10  NANO LABS LTD    NaN  334413.0
1402139   23234  2023-11-03  63011A10  NANO LABS LTD    NaN  334413.0
1402140   23234  2023-11-06  63011A10  NANO LABS LTD    NaN  334413.0
1402141   23234  2023-11-07  63011A10  NANO LABS LTD    NaN  334413.0
1402142   23234  2023-11-08  63011A10  NANO LABS LTD    NaN  334413.0
1402143   23234  2023-11-09  63011A10  NANO LABS LTD    NaN  334413.0
1402144   23234  2023-11-10  63011A10  NANO LABS LTD    NaN  334413.0
1402145   23234  2023-11-13  63011A10  NANO LABS LTD    NaN  334413.0
1402146   23234  2023-11-14  63011A10  NANO LABS LTD    NaN  334413.0
1402147   23234  2023-11-15  63011A10  NANO LABS LTD    NaN  334413.0
1402148   23234  2023-11-16  63011A10  NANO LABS LTD    NaN  334413.0
1402149   23234  2023-11-17  63011A10  NANO LABS LTD    NaN  334413.0
1402150   23234  2023-11-20  63011A10  NANO LABS LTD    NaN  334413.0
1402151   23234  2023-11-21  63011A10  NANO LABS LTD    NaN  334413.0
1402152   23234  2023-11-22  63011A10  NANO LABS LTD    NaN  334413.0
1402153   23234  2023-11-24  63011A10  NANO LABS LTD    NaN  334413.0
1402154   23234  2023-11-27  63011A10  NANO LABS LTD    NaN  334413.0
1402155   23234  2023-11-28  63011A10  NANO LABS LTD    NaN  334413.0
1402156   23234  2023-11-29  63011A10  NANO LABS LTD    NaN  334413.0
1402157   23234  2023-11-30  63011A10  NANO LABS LTD    NaN  334413.0
1402158   23234  2023-12-01  63011A10  NANO LABS LTD    NaN  334413.0
1402159   23234  2023-12-04  63011A10  NANO LABS LTD    NaN  334413.0
1402160   23234  2023-12-05  63011A10  NANO LABS LTD    NaN  334413.0
1402161   23234  2023-12-06  63011A10  NANO LABS LTD    NaN  334413.0
1402162   23234  2023-12-07  63011A10  NANO LABS LTD    NaN  334413.0
1402163   23234  2023-12-08  63011A10  NANO LABS LTD    NaN  334413.0
1402164   23234  2023-12-11  63011A10  NANO LABS LTD    NaN  334413.0
1402165   23234  2023-12-12  63011A10  NANO LABS LTD    NaN  334413.0
1402166   23234  2023-12-13  63011A10  NANO LABS LTD    NaN  334413.0
1402167   23234  2023-12-14  63011A10  NANO LABS LTD    NaN  334413.0
1402168   23234  2023-12-15  63011A10  NANO LABS LTD    NaN  334413.0
1402169   23234  2023-12-18  63011A10  NANO LABS LTD    NaN  334413.0
1402170   23234  2023-12-19  63011A10  NANO LABS LTD    NaN  334413.0
1402171   23234  2023-12-20  63011A10  NANO LABS LTD    NaN  334413.0
1402172   23234  2023-12-21  63011A10  NANO LABS LTD    NaN  334413.0

In [41]:
# show one example that CUSIP has 2 TICKER
filtered_data_2[filtered_data_2["CUSIP"] == "00258Y10"].sort_values(by="date")

,PERMNO,date,CUSIP,COMNAM,TICKER,NAICS,PRIMEXCH,RET,DLPDT,TRDSTAT
873549,19826,2023-01-03,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.002943,NaN,A
873550,19826,2023-01-04,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.000972,NaN,A
873551,19826,2023-01-05,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.001965,NaN,A
873552,19826,2023-01-06,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000000,NaN,A
873553,19826,2023-01-09,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000490,NaN,A
873554,19826,2023-01-10,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.000480,NaN,A
873555,19826,2023-01-11,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.000010,NaN,A
873556,19826,2023-01-12,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.002451,NaN,A
873557,19826,2023-01-13,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.000489,NaN,A
873558,19826,2023-01-17,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.000010,NaN,A
873559,19826,2023-01-18,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.006840,NaN,A
873560,19826,2023-01-19,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.004434,NaN,A
873561,19826,2023-01-20,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.002452,NaN,A
873562,19826,2023-01-23,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.006849,NaN,A
873563,19826,2023-01-24,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000985,NaN,A
873564,19826,2023-01-25,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.002953,NaN,A
873565,19826,2023-01-26,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.003435,NaN,A
873566,19826,2023-01-27,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.000489,NaN,A
873567,19826,2023-01-30,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.000489,NaN,A
873568,19826,2023-01-31,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.004454,NaN,A
873569,19826,2023-02-01,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.005457,NaN,A
873570,19826,2023-02-02,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000000,NaN,A
873571,19826,2023-02-03,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000489,NaN,A
873572,19826,2023-02-06,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000000,NaN,A
873573,19826,2023-02-07,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.005865,NaN,A
873574,19826,2023-02-08,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.008358,NaN,A
873575,19826,2023-02-09,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.008289,NaN,A
873576,19826,2023-02-10,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.007866,NaN,A
873577,19826,2023-02-13,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.003902,NaN,A
873578,19826,2023-02-14,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.006803,NaN,A
873579,19826,2023-02-15,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.011742,NaN,A
873580,19826,2023-02-16,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.019342,NaN,A
873581,19826,2023-02-17,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.005693,NaN,A
873582,19826,2023-02-21,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.014151,NaN,A
873583,19826,2023-02-22,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.010048,NaN,A
873584,19826,2023-02-23,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.003867,NaN,A
873585,19826,2023-02-24,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.000970,NaN,A
873586,19826,2023-02-27,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.009228,NaN,A
873587,19826,2023-02-28,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.001471,NaN,A
873588,19826,2023-03-01,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000982,NaN,A
873589,19826,2023-03-02,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.000981,NaN,A
873590,19826,2023-03-03,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000000,NaN,A
873591,19826,2023-03-06,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000491,NaN,A
873592,19826,2023-03-07,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.010304,NaN,A
873593,19826,2023-03-08,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.010199,NaN,A
873594,19826,2023-03-09,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.009814,NaN,A
873595,19826,2023-03-10,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000000,NaN,A
873596,19826,2023-03-13,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.004859,NaN,A
873597,19826,2023-03-14,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.008704,NaN,A
873598,19826,2023-03-15,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000000,NaN,A
873599,19826,2023-03-16,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000000,NaN,A
873600,19826,2023-03-17,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.001668,NaN,A
873601,19826,2023-03-20,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.009489,NaN,A
873602,19826,2023-03-21,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.008713,NaN,A
873603,19826,2023-03-22,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.003906,NaN,A
873604,19826,2023-03-23,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.002918,NaN,A
873605,19826,2023-03-24,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000488,NaN,A
873606,19826,2023-03-27,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.002438,NaN,A
873607,19826,2023-03-28,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.001945,NaN,A
873608,19826,2023-03-29,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.001949,NaN,A
873609,19826,2023-03-30,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000000,NaN,A
873610,19826,2023-03-31,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.002918,NaN,A
873611,19826,2023-04-03,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.009756,NaN,A
873612,19826,2023-04-04,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.004348,NaN,A
873613,19826,2023-04-05,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.004357,NaN,A
873614,19826,2023-04-06,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.002427,NaN,A
873615,19826,2023-04-10,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.000486,NaN,A
873616,19826,2023-04-11,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000973,NaN,A
873617,19826,2023-04-12,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000000,NaN,A
873618,19826,2023-04-13,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000972,NaN,A
873619,19826,2023-04-14,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.001942,NaN,A
873620,19826,2023-04-17,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.002918,NaN,A
873621,19826,2023-04-18,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000000,NaN,A
873622,19826,2023-04-19,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.009699,NaN,A
873623,19826,2023-04-20,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.011527,NaN,A
873624,19826,2023-04-21,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.002430,NaN,A
873625,19826,2023-04-24,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.001939,NaN,A
873626,19826,2023-04-25,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.003512,NaN,A
873627,19826,2023-04-26,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.000845,NaN,A
873628,19826,2023-04-27,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000000,NaN,A
873629,19826,2023-04-28,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000000,NaN,A
873630,19826,2023-05-01,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000000,NaN,A
873631,19826,2023-05-02,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000000,NaN,A
873632,19826,2023-05-03,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.000972,NaN,A
873633,19826,2023-05-04,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000010,NaN,A
873634,19826,2023-05-05,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.001449,NaN,A
873635,19826,2023-05-08,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000000,NaN,A
873636,19826,2023-05-09,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.000486,NaN,A
873637,19826,2023-05-10,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.002915,NaN,A
873638,19826,2023-05-11,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000000,NaN,A
873639,19826,2023-05-12,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000485,NaN,A
873640,19826,2023-05-15,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.003390,NaN,A
873641,19826,2023-05-16,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.005791,NaN,A
873642,19826,2023-05-17,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.004854,NaN,A
873643,19826,2023-05-18,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.004821,NaN,A
873644,19826,2023-05-19,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000961,NaN,A
873645,19826,2023-05-22,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.003880,NaN,A
873646,19826,2023-05-23,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000483,NaN,A
873647,19826,2023-05-24,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.006277,NaN,A
873648,19826,2023-05-25,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.005831,NaN,A
873649,19826,2023-05-26,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.005797,NaN,A
873650,19826,2023-05-30,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.003887,NaN,A
873651,19826,2023-05-31,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000968,NaN,A
873652,19826,2023-06-01,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.004836,NaN,A
873653,19826,2023-06-02,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.006803,NaN,A
873654,19826,2023-06-05,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.001931,NaN,A
873655,19826,2023-06-06,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.001934,NaN,A
873656,19826,2023-06-07,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.004845,NaN,A
873657,19826,2023-06-08,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.001929,NaN,A
873658,19826,2023-06-09,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000000,NaN,A
873659,19826,2023-06-12,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.009662,NaN,A
873660,19826,2023-06-13,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.008612,NaN,A
873661,19826,2023-06-14,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.006757,NaN,A
873662,19826,2023-06-15,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.004314,NaN,A
873663,19826,2023-06-16,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.023389,NaN,A
873664,19826,2023-06-20,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.013060,NaN,A
873665,19826,2023-06-21,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.019849,NaN,A
873666,19826,2023-06-22,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.000964,NaN,A
873667,19826,2023-06-23,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.011561,NaN,A
873668,19826,2023-06-26,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.032164,NaN,A
873669,19826,2023-06-27,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.013092,NaN,A
873670,19826,2023-06-28,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.122449,NaN,A
873671,19826,2023-06-29,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,-0.117273,NaN,A
873672,19826,2023-06-30,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.032956,NaN,A
873673,19826,2023-07-03,00258Y10,EAST RESOURCES ACQUISITION CO,ERES,523910.0,Q,0.081755,NaN,A
873674,19826,2023-07-05,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.124424,NaN,A
873675,19826,2023-07-06,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.056842,NaN,A
873676,19826,2023-07-07,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.146414,NaN,A
873677,19826,2023-07-10,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.012835,NaN,A
873678,19826,2023-07-11,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.047281,NaN,A
873679,19826,2023-07-12,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.022333,NaN,A
873680,19826,2023-07-13,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.015228,NaN,A
873681,19826,2023-07-14,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.057500,NaN,A
873682,19826,2023-07-17,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.029178,NaN,A
873683,19826,2023-07-18,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.096995,NaN,A
873684,19826,2023-07-19,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.113464,NaN,A
873685,19826,2023-07-20,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.006826,NaN,A
873686,19826,2023-07-21,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.012028,NaN,A
873687,19826,2023-07-24,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.029565,NaN,A
873688,19826,2023-07-25,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.000000,NaN,A
873689,19826,2023-07-26,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.013514,NaN,A
873690,19826,2023-07-27,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.033333,NaN,A
873691,19826,2023-07-28,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.012903,NaN,A
873692,19826,2023-07-31,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.017974,NaN,A
873693,19826,2023-08-01,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.040128,NaN,A
873694,19826,2023-08-02,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.035494,NaN,A
873695,19826,2023-08-03,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.025600,NaN,A
873696,19826,2023-08-04,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.027915,NaN,A
873697,19826,2023-08-07,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.004792,NaN,A
873698,19826,2023-08-08,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.069021,NaN,A
873699,19826,2023-08-09,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.034483,NaN,A
873700,19826,2023-08-10,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.028333,NaN,A
873701,19826,2023-08-11,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.046312,NaN,A
873702,19826,2023-08-14,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.131148,NaN,A
873703,19826,2023-08-15,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.101449,NaN,A
873704,19826,2023-08-16,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.011842,NaN,A
873705,19826,2023-08-17,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.002663,NaN,A
873706,19826,2023-08-18,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.013351,NaN,A
873707,19826,2023-08-21,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.035573,NaN,A
873708,19826,2023-08-22,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.019809,NaN,A
873709,19826,2023-08-23,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.016745,NaN,A
873710,19826,2023-08-24,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.028986,NaN,A
873711,19826,2023-08-25,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.028494,NaN,A
873712,19826,2023-08-28,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.284916,NaN,A
873713,19826,2023-08-29,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.031522,NaN,A
873714,19826,2023-08-30,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.010537,NaN,A
873715,19826,2023-08-31,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.029819,NaN,A
873716,19826,2023-09-01,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.005488,NaN,A
873717,19826,2023-09-05,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.010917,NaN,A
873718,19826,2023-09-06,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.007726,NaN,A
873719,19826,2023-09-07,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.090100,NaN,A
873720,19826,2023-09-08,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.083130,NaN,A
873721,19826,2023-09-11,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.033333,NaN,A
873722,19826,2023-09-12,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.045161,NaN,A
873723,19826,2023-09-13,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.022222,NaN,A
873724,19826,2023-09-14,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.076087,NaN,A
873725,19826,2023-09-15,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.009150,NaN,A
873726,19826,2023-09-18,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.075130,NaN,A
873727,19826,2023-09-19,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.015406,NaN,A
873728,19826,2023-09-20,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.033103,NaN,A
873729,19826,2023-09-21,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.012839,NaN,A
873730,19826,2023-09-22,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.043662,NaN,A
873731,19826,2023-09-25,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.041237,NaN,A
873732,19826,2023-09-26,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.039939,NaN,A
873733,19826,2023-09-27,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.067947,NaN,A
873734,19826,2023-09-28,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.027662,NaN,A
873735,19826,2023-09-29,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.028450,NaN,A
873736,19826,2023-10-02,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.058565,NaN,A
873737,19826,2023-10-03,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.041494,NaN,A
873738,19826,2023-10-04,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.067994,NaN,A
873739,19826,2023-10-05,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.060963,NaN,A
873740,19826,2023-10-06,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.007194,NaN,A
873741,19826,2023-10-09,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.027143,NaN,A
873742,19826,2023-10-10,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.027900,NaN,A
873743,19826,2023-10-11,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.062857,NaN,A
873744,19826,2023-10-12,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.016768,NaN,A
873745,19826,2023-10-13,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.056972,NaN,A
873746,19826,2023-10-16,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.017488,NaN,A
873747,19826,2023-10-17,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.015625,NaN,A
873748,19826,2023-10-18,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.041538,NaN,A
873749,19826,2023-10-19,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.082718,NaN,A
873750,19826,2023-10-20,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.000000,NaN,A
873751,19826,2023-10-23,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.017713,NaN,A
873752,19826,2023-10-24,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.014607,NaN,A
873753,19826,2023-10-25,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.029229,NaN,A
873754,19826,2023-10-26,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.047096,NaN,A
873755,19826,2023-10-27,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.014003,NaN,A
873756,19826,2023-10-30,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.008936,NaN,A
873757,19826,2023-10-31,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.001885,NaN,A
873758,19826,2023-11-01,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.027571,NaN,A
873759,19826,2023-11-02,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.003185,NaN,A
873760,19826,2023-11-03,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.052381,NaN,A
873761,19826,2023-11-06,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.025641,NaN,A
873762,19826,2023-11-07,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.014706,NaN,A
873763,19826,2023-11-08,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.014493,NaN,A
873764,19826,2023-11-09,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.002871,NaN,A
873765,19826,2023-11-10,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.021476,NaN,A
873766,19826,2023-11-13,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.016105,NaN,A
873767,19826,2023-11-14,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.102723,NaN,A
873768,19826,2023-11-15,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.009901,NaN,A
873769,19826,2023-11-16,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.036851,NaN,A
873770,19826,2023-11-17,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.017771,NaN,A
873771,19826,2023-11-20,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.034921,NaN,A
873772,19826,2023-11-21,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.004601,NaN,A
873773,19826,2023-11-22,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.097072,NaN,A
873774,19826,2023-11-24,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,-0.016854,NaN,A
873775,19826,2023-11-27,00258Y10,ABACUS LIFE INC,ABL,523910.0,Q,0.015714,NaN,A

In [42]:
Inputation_data_1 = filtered_data_2

In [43]:
# Define a function to extract the first word of the company name
def extract_first_word(name):
    return name.split()[0]


# Apply the function to fill missing TICKER values
Inputation_data_1["TICKER"] = Inputation_data_1.apply(
    lambda row: (extract_first_word(row["COMNAM"]) if pd.isna(row["TICKER"]) else row["TICKER"]),
    axis=1,
)

# # Display the rows with the previously missing TICKER values to verify
# print(Inputation_data_1[Inputation_data_1['CUSIP'] == '63011A10'].head())

<ipython-input-43-1121cbb97cc4>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Inputation_data_1['TICKER'] = Inputation_data_1.apply(

In [44]:
# Display the rows with the previously missing TICKER values to verify
Inputation_data_1[Inputation_data_1["CUSIP"] == "63011A10"]

,PERMNO,date,CUSIP,COMNAM,TICKER,NAICS,PRIMEXCH,RET,DLPDT,TRDSTAT
1401928,23234,2023-01-03,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.020870,NaN,A
1401929,23234,2023-01-04,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.005111,NaN,A
1401930,23234,2023-01-05,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.084746,NaN,A
1401931,23234,2023-01-06,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.148437,NaN,A
1401932,23234,2023-01-09,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.082569,NaN,A
1401933,23234,2023-01-10,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.025424,NaN,A
1401934,23234,2023-01-11,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.016529,NaN,A
1401935,23234,2023-01-12,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.048780,NaN,A
1401936,23234,2023-01-13,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.085271,NaN,A
1401937,23234,2023-01-17,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.171429,NaN,A
1401938,23234,2023-01-18,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.067073,NaN,A
1401939,23234,2023-01-19,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.013072,NaN,A
1401940,23234,2023-01-20,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.052980,NaN,A
1401941,23234,2023-01-23,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.069182,NaN,A
1401942,23234,2023-01-24,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.058824,NaN,A
1401943,23234,2023-01-25,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.068750,NaN,A
1401944,23234,2023-01-26,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.093960,NaN,A
1401945,23234,2023-01-27,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.029630,NaN,A
1401946,23234,2023-01-30,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.030611,NaN,A
1401947,23234,2023-01-31,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.007481,NaN,A
1401948,23234,2023-02-01,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.005149,NaN,A
1401949,23234,2023-02-02,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.009726,NaN,A
1401950,23234,2023-02-03,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.000000,NaN,A
1401951,23234,2023-02-06,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.090515,NaN,A
1401952,23234,2023-02-07,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.034455,NaN,A
1401953,23234,2023-02-08,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.032821,NaN,A
1401954,23234,2023-02-09,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.075812,NaN,A
1401955,23234,2023-02-10,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.046875,NaN,A
1401956,23234,2023-02-13,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.081967,NaN,A
1401957,23234,2023-02-14,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.000000,NaN,A
1401958,23234,2023-02-15,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.030303,NaN,A
1401959,23234,2023-02-16,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.000000,NaN,A
1401960,23234,2023-02-17,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.029412,NaN,A
1401961,23234,2023-02-21,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.026515,NaN,A
1401962,23234,2023-02-22,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.019455,NaN,A
1401963,23234,2023-02-23,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.038168,NaN,A
1401964,23234,2023-02-24,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.056905,NaN,A
1401965,23234,2023-02-27,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.032231,NaN,A
1401966,23234,2023-02-28,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.021739,NaN,A
1401967,23234,2023-03-01,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.016255,NaN,A
1401968,23234,2023-03-02,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.038152,NaN,A
1401969,23234,2023-03-03,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.008333,NaN,A
1401970,23234,2023-03-06,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.049504,NaN,A
1401971,23234,2023-03-07,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.026172,NaN,A
1401972,23234,2023-03-08,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.009018,NaN,A
1401973,23234,2023-03-09,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.017786,NaN,A
1401974,23234,2023-03-10,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.045045,NaN,A
1401975,23234,2023-03-13,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.075472,NaN,A
1401976,23234,2023-03-14,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.078947,NaN,A
1401977,23234,2023-03-15,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.019048,NaN,A
1401978,23234,2023-03-16,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.024175,NaN,A
1401979,23234,2023-03-17,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.004875,NaN,A
1401980,23234,2023-03-20,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.000000,NaN,A
1401981,23234,2023-03-21,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.049505,NaN,A
1401982,23234,2023-03-22,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.066038,NaN,A
1401983,23234,2023-03-23,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.030973,NaN,A
1401984,23234,2023-03-24,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.022831,NaN,A
1401985,23234,2023-03-27,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.037383,NaN,A
1401986,23234,2023-03-28,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.009709,NaN,A
1401987,23234,2023-03-29,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.000000,NaN,A
1401988,23234,2023-03-30,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.028846,NaN,A
1401989,23234,2023-03-31,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.028037,NaN,A
1401990,23234,2023-04-03,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.019231,NaN,A
1401991,23234,2023-04-04,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.018868,NaN,A
1401992,23234,2023-04-05,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.000000,NaN,A
1401993,23234,2023-04-06,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.009259,NaN,A
1401994,23234,2023-04-10,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.009346,NaN,A
1401995,23234,2023-04-11,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.000000,NaN,A
1401996,23234,2023-04-12,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.000000,NaN,A
1401997,23234,2023-04-13,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.043796,NaN,A
1401998,23234,2023-04-14,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.008871,NaN,A
1401999,23234,2023-04-17,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.011367,NaN,A
1402000,23234,2023-04-18,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.008850,NaN,A
1402001,23234,2023-04-19,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.026316,NaN,A
1402002,23234,2023-04-20,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.036036,NaN,A
1402003,23234,2023-04-21,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.060870,NaN,A
1402004,23234,2023-04-24,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.013889,NaN,A
1402005,23234,2023-04-25,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.013699,NaN,A
1402006,23234,2023-04-26,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.013889,NaN,A
1402007,23234,2023-04-27,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.023474,NaN,A
1402008,23234,2023-04-28,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.055096,NaN,A
1402009,23234,2023-05-01,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.148273,NaN,A
1402010,23234,2023-05-02,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.103175,NaN,A
1402011,23234,2023-05-03,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.061947,NaN,A
1402012,23234,2023-05-04,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.028302,NaN,A
1402013,23234,2023-05-05,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.004587,NaN,A
1402014,23234,2023-05-08,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.013825,NaN,A
1402015,23234,2023-05-09,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.028037,NaN,A
1402016,23234,2023-05-10,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.004545,NaN,A
1402017,23234,2023-05-11,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.013575,NaN,A
1402018,23234,2023-05-12,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.021743,NaN,A
1402019,23234,2023-05-15,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.194217,NaN,A
1402020,23234,2023-05-16,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.157820,NaN,A
1402021,23234,2023-05-17,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.106955,NaN,A
1402022,23234,2023-05-18,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.177514,NaN,A
1402023,23234,2023-05-19,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.054726,NaN,A
1402024,23234,2023-05-22,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.116826,NaN,A
1402025,23234,2023-05-23,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.036765,NaN,A
1402026,23234,2023-05-24,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.028369,NaN,A
1402027,23234,2023-05-25,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.634483,NaN,A
1402028,23234,2023-05-26,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.008439,NaN,A
1402029,23234,2023-05-30,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.042511,NaN,A
1402030,23234,2023-05-31,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.134659,NaN,A
1402031,23234,2023-06-01,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.018868,NaN,A
1402032,23234,2023-06-02,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.033654,NaN,A
1402033,23234,2023-06-05,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.000000,NaN,A
1402034,23234,2023-06-06,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.027907,NaN,A
1402035,23234,2023-06-07,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.033493,NaN,A
1402036,23234,2023-06-08,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.259259,NaN,A
1402037,23234,2023-06-09,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.007353,NaN,A
1402038,23234,2023-06-12,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.040741,NaN,A
1402039,23234,2023-06-13,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.005791,NaN,A
1402040,23234,2023-06-14,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.011650,NaN,A
1402041,23234,2023-06-15,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.096267,NaN,A
1402042,23234,2023-06-16,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.056522,NaN,A
1402043,23234,2023-06-20,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.059908,NaN,A
1402044,23234,2023-06-21,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.068627,NaN,A
1402045,23234,2023-06-22,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.047368,NaN,A
1402046,23234,2023-06-23,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.075377,NaN,A
1402047,23234,2023-06-26,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.043478,NaN,A
1402048,23234,2023-06-27,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.070313,NaN,A
1402049,23234,2023-06-28,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.012165,NaN,A
1402050,23234,2023-06-29,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.039409,NaN,A
1402051,23234,2023-06-30,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.010256,NaN,A
1402052,23234,2023-07-03,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.030457,NaN,A
1402053,23234,2023-07-05,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.034483,NaN,A
1402054,23234,2023-07-06,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.066667,NaN,A
1402055,23234,2023-07-07,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.045918,NaN,A
1402056,23234,2023-07-10,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.037433,NaN,A
1402057,23234,2023-07-11,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.055556,NaN,A
1402058,23234,2023-07-12,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.021053,NaN,A
1402059,23234,2023-07-13,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.053763,NaN,A
1402060,23234,2023-07-14,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.041364,NaN,A
1402061,23234,2023-07-17,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.093528,NaN,A
1402062,23234,2023-07-18,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.018970,NaN,A
1402063,23234,2023-07-19,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.066298,NaN,A
1402064,23234,2023-07-20,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.008876,NaN,A
1402065,23234,2023-07-21,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.049853,NaN,A
1402066,23234,2023-07-24,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.055556,NaN,A
1402067,23234,2023-07-25,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.056667,NaN,A
1402068,23234,2023-07-26,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.041257,NaN,A
1402069,23234,2023-07-27,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.096774,NaN,A
1402070,23234,2023-07-28,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.021429,NaN,A
1402071,23234,2023-07-31,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.027972,NaN,A
1402072,23234,2023-08-01,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.088435,NaN,A
1402073,23234,2023-08-02,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.087500,NaN,A
1402074,23234,2023-08-03,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.013699,NaN,A
1402075,23234,2023-08-04,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.000000,NaN,A
1402076,23234,2023-08-07,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.097222,NaN,A
1402077,23234,2023-08-08,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.061538,NaN,A
1402078,23234,2023-08-09,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.036449,NaN,A
1402079,23234,2023-08-10,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.037377,NaN,A
1402080,23234,2023-08-11,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.046875,NaN,A
1402081,23234,2023-08-14,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.057377,NaN,A
1402082,23234,2023-08-15,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.069767,NaN,A
1402083,23234,2023-08-16,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.116667,NaN,A
1402084,23234,2023-08-17,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.009434,NaN,A
1402085,23234,2023-08-18,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.009346,NaN,A
1402086,23234,2023-08-21,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.027778,NaN,A
1402087,23234,2023-08-22,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.009524,NaN,A
1402088,23234,2023-08-23,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.009615,NaN,A
1402089,23234,2023-08-24,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.019417,NaN,A
1402090,23234,2023-08-25,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.019048,NaN,A
1402091,23234,2023-08-28,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.009709,NaN,A
1402092,23234,2023-08-29,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.000000,NaN,A
1402093,23234,2023-08-30,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.028846,NaN,A
1402094,23234,2023-08-31,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.018692,NaN,A
1402095,23234,2023-09-01,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.009524,NaN,A
1402096,23234,2023-09-05,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.009615,NaN,A
1402097,23234,2023-09-06,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.002095,NaN,A
1402098,23234,2023-09-07,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.083539,NaN,A
1402099,23234,2023-09-08,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.113937,NaN,A
1402100,23234,2023-09-11,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.196850,NaN,A
1402101,23234,2023-09-12,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.068628,NaN,A
1402102,23234,2023-09-13,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.055046,NaN,A
1402103,23234,2023-09-14,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.008696,NaN,A
1402104,23234,2023-09-15,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.016579,NaN,A
1402105,23234,2023-09-18,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.025778,NaN,A
1402106,23234,2023-09-19,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.043478,NaN,A
1402107,23234,2023-09-20,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.054545,NaN,A
1402108,23234,2023-09-21,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.008621,NaN,A
1402109,23234,2023-09-22,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.043478,NaN,A
1402110,23234,2023-09-25,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.066667,NaN,A
1402111,23234,2023-09-26,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.034286,NaN,A
1402112,23234,2023-09-27,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.096340,NaN,A
1402113,23234,2023-09-28,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.086614,NaN,A
1402114,23234,2023-09-29,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.086884,NaN,A
1402115,23234,2023-10-02,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.126895,NaN,A
1402116,23234,2023-10-03,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.021127,NaN,A
1402117,23234,2023-10-04,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.007194,NaN,A
1402118,23234,2023-10-05,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.100000,NaN,A
1402119,23234,2023-10-06,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.031746,NaN,A
1402120,23234,2023-10-09,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.155738,NaN,A
1402121,23234,2023-10-10,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.021277,NaN,A
1402122,23234,2023-10-11,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.057971,NaN,A
1402123,23234,2023-10-12,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.100000,NaN,A
1402124,23234,2023-10-13,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.000000,NaN,A
1402125,23234,2023-10-16,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.145299,NaN,A
1402126,23234,2023-10-17,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.044776,NaN,A
1402127,23234,2023-10-18,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.000000,NaN,A
1402128,23234,2023-10-19,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.042857,NaN,A
1402129,23234,2023-10-20,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.052239,NaN,A
1402130,23234,2023-10-23,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.051181,NaN,A
1402131,23234,2023-10-24,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.056180,NaN,A
1402132,23234,2023-10-25,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.021277,NaN,A
1402133,23234,2023-10-26,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.020833,NaN,A
1402134,23234,2023-10-27,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.021277,NaN,A
1402135,23234,2023-10-30,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.025362,NaN,A
1402136,23234,2023-10-31,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.097026,NaN,A
1402137,23234,2023-11-01,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.045698,NaN,A
1402138,23234,2023-11-02,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.007874,NaN,A
1402139,23234,2023-11-03,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.007812,NaN,A
1402140,23234,2023-11-06,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.062992,NaN,A
1402141,23234,2023-11-07,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.007407,NaN,A
1402142,23234,2023-11-08,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.021418,NaN,A
1402143,23234,2023-11-09,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.037139,NaN,A
1402144,23234,2023-11-10,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.011029,NaN,A
1402145,23234,2023-11-13,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.085502,NaN,A
1402146,23234,2023-11-14,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.095890,NaN,A
1402147,23234,2023-11-15,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.031250,NaN,A
1402148,23234,2023-11-16,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.000000,NaN,A
1402149,23234,2023-11-17,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.006452,NaN,A
1402150,23234,2023-11-20,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.012821,NaN,A
1402151,23234,2023-11-21,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.058442,NaN,A
1402152,23234,2023-11-22,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.000000,NaN,A
1402153,23234,2023-11-24,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.082759,NaN,A
1402154,23234,2023-11-27,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.019108,NaN,A
1402155,23234,2023-11-28,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.137500,NaN,A
1402156,23234,2023-11-29,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.036232,NaN,A
1402157,23234,2023-11-30,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.041958,NaN,A
1402158,23234,2023-12-01,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.026846,NaN,A
1402159,23234,2023-12-04,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.131034,NaN,A
1402160,23234,2023-12-05,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.048781,NaN,A
1402161,23234,2023-12-06,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.075581,NaN,A
1402162,23234,2023-12-07,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.045946,NaN,A
1402163,23234,2023-12-08,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.059431,NaN,A
1402164,23234,2023-12-11,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.024725,NaN,A
1402165,23234,2023-12-12,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.013405,NaN,A
1402166,23234,2023-12-13,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.032609,NaN,A
1402167,23234,2023-12-14,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.007895,NaN,A
1402168,23234,2023-12-15,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.018568,NaN,A
1402169,23234,2023-12-18,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.043243,NaN,A
1402170,23234,2023-12-19,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.011299,NaN,A
1402171,23234,2023-12-20,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.020000,NaN,A
1402172,23234,2023-12-21,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.008746,NaN,A
1402173,23234,2023-12-22,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.040462,NaN,A
1402174,23234,2023-12-26,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.144578,NaN,A
1402175,23234,2023-12-27,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.057842,NaN,A
1402176,23234,2023-12-28,63011A10,NANO LABS LTD,NANO,334413.0,Q,0.061393,NaN,A
1402177,23234,2023-12-29,63011A10,NANO LABS LTD,NANO,334413.0,Q,-0.047316,NaN,A

In [45]:
Inputation_data_1[Inputation_data_1["CUSIP"] == "63011A10"]["TICKER"].value_counts(dropna=False)

TICKER
NANO    250
Name: count, dtype: int64

### NACIS

In [46]:
Inputation_data_2 = Inputation_data_1

In [47]:
Inputation_data_2.isnull().any()

PERMNO      False
date        False
CUSIP       False
COMNAM      False
TICKER      False
NAICS        True
PRIMEXCH    False
RET          True
DLPDT        True
TRDSTAT     False
dtype: bool

In [48]:
see_Inputation_data_2 = Inputation_data_2.groupby("CUSIP")["NAICS"].value_counts(dropna=False).reset_index()
see_Inputation_data_2.loc[see_Inputation_data_2["NAICS"].isnull() == 1].sort_values(by="count")

         CUSIP  NAICS  count
64    00168310    NaN      1
7277  78435P10    NaN      1
9505  G5140510    NaN      2
9694  G8656T10    NaN      4
9569  G6301J10    NaN      4
9531  G5500B10    NaN      8
9210  98877R10    NaN     10
1842  22275C10    NaN     13
9419  G3730L10    NaN     20
9411  G3413G10    NaN     21
9433  G3937M10    NaN     27
9266  G0232G10    NaN     27
9370  G2677P10    NaN     35
4252  45828E10    NaN     47
9743  G9513S10    NaN     50
154   00489010    NaN     57
9744  G9517U10    NaN     65
3304  35953C10    NaN     71
9672  G8192U10    NaN     76
5932  63903R10    NaN     77
9944  Y1828410    NaN    133
3874  42805010    NaN    151
9653  G7948310    NaN    152
1191  09950L30    NaN    158
9764  G9T22C10    NaN    176
9745  G9520U10    NaN    176
9751  G9821810    NaN    181
9740  G9495L12    NaN    182
7901  86366E10    NaN    185
9577  G6362F10    NaN    188
9466  G4513910    NaN    189
9343  G2104U10    NaN    190
9468  G4594M10    NaN    191
9756  G9834A10    NaN    192
9336  G1991X10    NaN    195
9613  G6S38M10    NaN    197
9360  G2415A11    NaN    199
9477  G4760B10    NaN    201
9190  98423X10    NaN    205
7012  74767N10    NaN    235
9601  G6792710    NaN    250
1285  12326C10    NaN    250
3236  35473M10    NaN    250
6616  71910P20    NaN    250
9682  G8437S11    NaN    250
9448  G4013A10    NaN    250
9357  G2311X10    NaN    250
9342  G2086M10    NaN    250
9300  G1110E10    NaN    250
9284  G0542S10    NaN    250
5078  47737L10    NaN    250
5479  53934A11    NaN    250
7594  81807M30    NaN    250
9541  G5865E10    NaN    250
9987  Y9233510    NaN    250

In [49]:
Inputation_data_2.groupby("CUSIP")["NAICS"].value_counts(dropna=False)

CUSIP     NAICS
00032Q10  325412.0    250
00036020  333415.0    250
00036110  336412.0    250
00037520  551112.0     64
          335313.0     33
                     ...
Y8897Y23  483111.0    250
Y8900D10  561499.0    206
Y9233510  NaN         250
Y9390M10  523910.0     96
Y9530810  541720.0    250
Name: count, Length: 9990, dtype: int64

In [50]:
Inputation_data_2[Inputation_data_2["CUSIP"] == "00037520"].sort_values(by="date")

,PERMNO,date,CUSIP,COMNAM,TICKER,NAICS,PRIMEXCH,RET,DLPDT,TRDSTAT
2003691,88953,2023-01-03,00037520,A B B LTD,ABB,335313.0,N,0.010506,NaN,A
2003692,88953,2023-01-04,00037520,A B B LTD,ABB,335313.0,N,0.04191,NaN,A
2003693,88953,2023-01-05,00037520,A B B LTD,ABB,335313.0,N,-0.007795,NaN,A
2003694,88953,2023-01-06,00037520,A B B LTD,ABB,335313.0,N,0.021684,NaN,A
2003695,88953,2023-01-09,00037520,A B B LTD,ABB,335313.0,N,0.00892,NaN,A
2003696,88953,2023-01-10,00037520,A B B LTD,ABB,335313.0,N,0.003659,NaN,A
2003697,88953,2023-01-11,00037520,A B B LTD,ABB,335313.0,N,0.014581,NaN,A
2003698,88953,2023-01-12,00037520,A B B LTD,ABB,335313.0,N,0.003593,NaN,A
2003699,88953,2023-01-13,00037520,A B B LTD,ABB,335313.0,N,0.00179,NaN,A
2003700,88953,2023-01-17,00037520,A B B LTD,ABB,335313.0,N,0.015485,NaN,A
2003701,88953,2023-01-18,00037520,A B B LTD,ABB,335313.0,N,-0.003226,NaN,A
2003702,88953,2023-01-19,00037520,A B B LTD,ABB,335313.0,N,-0.015299,NaN,A
2003703,88953,2023-01-20,00037520,A B B LTD,ABB,335313.0,N,0.01464,NaN,A
2003704,88953,2023-01-23,00037520,A B B LTD,ABB,335313.0,N,0.006184,NaN,A
2003705,88953,2023-01-24,00037520,A B B LTD,ABB,335313.0,N,0.001463,NaN,A
2003706,88953,2023-01-25,00037520,A B B LTD,ABB,335313.0,N,0.001461,NaN,A
2003707,88953,2023-01-26,00037520,A B B LTD,ABB,335313.0,N,0.014006,NaN,A
2003708,88953,2023-01-27,00037520,A B B LTD,ABB,335313.0,N,-0.003165,NaN,A
2003709,88953,2023-01-30,00037520,A B B LTD,ABB,335313.0,N,-0.006928,NaN,A
2003710,88953,2023-01-31,00037520,A B B LTD,ABB,335313.0,N,0.013081,NaN,A
2003711,88953,2023-02-01,00037520,A B B LTD,ABB,335313.0,N,0.013773,NaN,A
2003712,88953,2023-02-02,00037520,A B B LTD,ABB,335313.0,N,-0.039626,NaN,A
2003713,88953,2023-02-03,00037520,A B B LTD,ABB,335313.0,N,0.013557,NaN,A
2003714,88953,2023-02-06,00037520,A B B LTD,ABB,335313.0,N,-0.015121,NaN,A
2003715,88953,2023-02-07,00037520,A B B LTD,ABB,335313.0,N,0.003838,NaN,A
2003716,88953,2023-02-08,00037520,A B B LTD,ABB,335313.0,N,-0.015,NaN,A
2003717,88953,2023-02-09,00037520,A B B LTD,ABB,335313.0,N,0.001194,NaN,A
2003718,88953,2023-02-10,00037520,A B B LTD,ABB,335313.0,N,0.002982,NaN,A
2003719,88953,2023-02-13,00037520,A B B LTD,ABB,335313.0,N,0.012786,NaN,A
2003720,88953,2023-02-14,00037520,A B B LTD,ABB,335313.0,N,-0.00734,NaN,A
2003721,88953,2023-02-15,00037520,A B B LTD,ABB,335313.0,N,0.018042,NaN,A
2003722,88953,2023-02-16,00037520,A B B LTD,ABB,335313.0,N,-0.011912,NaN,A
2003723,88953,2023-02-17,00037520,A B B LTD,ABB,335313.0,N,0.004704,NaN,A
2003724,88953,2023-02-21,00037520,A B B LTD,ABB,551112.0,N,-0.0199,NaN,A
2003725,88953,2023-02-22,00037520,A B B LTD,ABB,551112.0,N,0.0,NaN,A
2003726,88953,2023-02-23,00037520,A B B LTD,ABB,551112.0,N,0.008958,NaN,A
2003727,88953,2023-02-24,00037520,A B B LTD,ABB,551112.0,N,-0.018645,NaN,A
2003728,88953,2023-02-27,00037520,A B B LTD,ABB,551112.0,N,0.010253,NaN,A
2003729,88953,2023-02-28,00037520,A B B LTD,ABB,551112.0,N,-0.00597,NaN,A
2003730,88953,2023-03-01,00037520,A B B LTD,ABB,551112.0,N,0.007808,NaN,A
2003731,88953,2023-03-02,00037520,A B B LTD,ABB,551112.0,N,0.00447,NaN,A
2003732,88953,2023-03-03,00037520,A B B LTD,ABB,551112.0,N,0.013349,NaN,A
2003733,88953,2023-03-06,00037520,A B B LTD,ABB,551112.0,N,0.002049,NaN,A
2003734,88953,2023-03-07,00037520,A B B LTD,ABB,551112.0,N,-0.018697,NaN,A
2003735,88953,2023-03-08,00037520,A B B LTD,ABB,551112.0,N,0.009229,NaN,A
2003736,88953,2023-03-09,00037520,A B B LTD,ABB,551112.0,N,0.000885,NaN,A
2003737,88953,2023-03-10,00037520,A B B LTD,ABB,551112.0,N,-0.023283,NaN,A
2003738,88953,2023-03-13,00037520,A B B LTD,ABB,551112.0,N,-0.006639,NaN,A
2003739,88953,2023-03-14,00037520,A B B LTD,ABB,551112.0,N,0.025516,NaN,A
2003740,88953,2023-03-15,00037520,A B B LTD,ABB,551112.0,N,-0.052429,NaN,A
2003741,88953,2023-03-16,00037520,A B B LTD,ABB,551112.0,N,0.017505,NaN,A
2003742,88953,2023-03-17,00037520,A B B LTD,ABB,551112.0,N,-0.017204,NaN,A
2003743,88953,2023-03-20,00037520,A B B LTD,ABB,551112.0,N,0.017818,NaN,A
2003744,88953,2023-03-21,00037520,A B B LTD,ABB,551112.0,N,0.021806,NaN,A
2003745,88953,2023-03-22,00037520,A B B LTD,ABB,551112.0,N,-0.004509,NaN,A
2003746,88953,2023-03-23,00037520,A B B LTD,ABB,551112.0,N,0.00785,NaN,A
2003747,88953,2023-03-24,00037520,A B B LTD,ABB,551112.0,N,-0.018874,NaN,A
2003748,88953,2023-03-27,00037520,A B B LTD,ABB,551112.0,N,0.009439,NaN,A
2003749,88953,2023-03-28,00037520,A B B LTD,ABB,551112.0,N,0.006223,NaN,A
2003750,88953,2023-03-29,00037520,A B B LTD,ABB,551112.0,N,0.014224,NaN,A
2003751,88953,2023-03-30,00037520,A B B LTD,ABB,551112.0,N,0.025915,NaN,A
2003752,88953,2023-03-31,00037520,A B B LTD,ABB,551112.0,N,0.019316,NaN,A
2003753,88953,2023-04-03,00037520,A B B LTD,ABB,551112.0,N,0.003499,NaN,A
2003754,88953,2023-04-04,00037520,A B B LTD,ABB,551112.0,N,-0.014817,NaN,A
2003755,88953,2023-04-05,00037520,A B B LTD,ABB,551112.0,N,-0.023592,NaN,A
2003756,88953,2023-04-06,00037520,A B B LTD,ABB,551112.0,N,-0.002718,NaN,A
2003757,88953,2023-04-10,00037520,A B B LTD,ABB,551112.0,N,0.003937,NaN,A
2003758,88953,2023-04-11,00037520,A B B LTD,ABB,551112.0,N,0.021719,NaN,A
2003759,88953,2023-04-12,00037520,A B B LTD,ABB,551112.0,N,0.017124,NaN,A
2003760,88953,2023-04-13,00037520,A B B LTD,ABB,551112.0,N,0.011321,NaN,A
2003761,88953,2023-04-14,00037520,A B B LTD,ABB,551112.0,N,0.008611,NaN,A
2003762,88953,2023-04-17,00037520,A B B LTD,ABB,551112.0,N,0.001138,NaN,A
2003763,88953,2023-04-18,00037520,A B B LTD,ABB,551112.0,N,0.006254,NaN,A
2003764,88953,2023-04-19,00037520,A B B LTD,ABB,551112.0,N,-0.008192,NaN,A
2003765,88953,2023-04-20,00037520,A B B LTD,ABB,551112.0,N,0.002848,NaN,A
2003766,88953,2023-04-21,00037520,A B B LTD,ABB,551112.0,N,0.005964,NaN,A
2003767,88953,2023-04-24,00037520,A B B LTD,ABB,551112.0,N,0.006211,NaN,A
2003768,88953,2023-04-25,00037520,A B B LTD,ABB,551112.0,N,0.028058,NaN,A
2003769,88953,2023-04-26,00037520,A B B LTD,ABB,551112.0,N,-0.028657,NaN,A
2003770,88953,2023-04-27,00037520,A B B LTD,ABB,551112.0,N,0.023883,NaN,A
2003771,88953,2023-04-28,00037520,A B B LTD,ABB,551112.0,N,-0.009605,NaN,A
2003772,88953,2023-05-01,00037520,A B B LTD,ABB,551112.0,N,-0.004711,NaN,A
2003773,88953,2023-05-02,00037520,A B B LTD,ABB,551112.0,N,0.002506,NaN,A
2003774,88953,2023-05-03,00037520,A B B LTD,ABB,551112.0,N,-0.001388,NaN,A
2003775,88953,2023-05-04,00037520,A B B LTD,ABB,551112.0,N,-0.006674,NaN,A
2003776,88953,2023-05-05,00037520,A B B LTD,ABB,551112.0,N,0.007559,NaN,A
2003777,88953,2023-05-08,00037520,A B B LTD,ABB,551112.0,N,0.004168,NaN,A
2003778,88953,2023-05-09,00037520,A B B LTD,ABB,551112.0,N,0.011898,NaN,A
2003779,88953,2023-05-10,00037520,A B B LTD,ABB,551112.0,N,-0.003008,NaN,A
2003780,88953,2023-05-11,00037520,A B B LTD,ABB,551112.0,N,0.007405,NaN,A
2003781,88953,2023-05-12,00037520,A B B LTD,ABB,551112.0,N,0.005445,NaN,A
2003782,88953,2023-05-15,00037520,A B B LTD,ABB,551112.0,N,0.003249,NaN,A
2003783,88953,2023-05-16,00037520,A B B LTD,ABB,551112.0,N,-0.011066,NaN,A
2003784,88953,2023-05-17,00037520,A B B LTD,ABB,551112.0,N,0.009007,NaN,A
2003785,88953,2023-05-18,00037520,A B B LTD,ABB,551112.0,N,0.001623,NaN,A
2003786,88953,2023-05-19,00037520,A B B LTD,ABB,551112.0,N,0.014313,NaN,A
2003787,88953,2023-05-22,00037520,A B B LTD,ABB,551112.0,N,-0.011448,NaN,A

In [51]:
# Impute missing values in 'NAICS' with -1
Inputation_data_2["NAICS"].fillna(-1, inplace=True)

<ipython-input-51-1a96cf017d62>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Inputation_data_2['NAICS'].fillna(-1, inplace=True)

In [52]:
Inputation_data_2[Inputation_data_2["CUSIP"] == "35953C10"].sort_values(by="date")

,PERMNO,date,CUSIP,COMNAM,TICKER,NAICS,PRIMEXCH,RET,DLPDT,TRDSTAT
1399928,23224,2023-01-03,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.003390,NaN,A
1399929,23224,2023-01-04,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.000000,NaN,A
1399930,23224,2023-01-05,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.020270,NaN,A
1399931,23224,2023-01-06,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.013793,NaN,A
1399932,23224,2023-01-09,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.006803,NaN,A
1399933,23224,2023-01-10,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.040541,NaN,A
1399934,23224,2023-01-11,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.025974,NaN,A
1399935,23224,2023-01-12,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.009494,NaN,A
1399936,23224,2023-01-13,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.075235,NaN,A
1399937,23224,2023-01-17,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.014577,NaN,A
1399938,23224,2023-01-18,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.011834,NaN,A
1399939,23224,2023-01-19,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.008982,NaN,A
1399940,23224,2023-01-20,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.091988,NaN,A
1399941,23224,2023-01-23,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.059783,NaN,A
1399942,23224,2023-01-24,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.034682,NaN,A
1399943,23224,2023-01-25,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.008982,NaN,A
1399944,23224,2023-01-26,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.021148,NaN,A
1399945,23224,2023-01-27,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.012346,NaN,A
1399946,23224,2023-01-30,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.024390,NaN,A
1399947,23224,2023-01-31,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.034375,NaN,A
1399948,23224,2023-02-01,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.006042,NaN,A
1399949,23224,2023-02-02,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.033435,NaN,A
1399950,23224,2023-02-03,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.005882,NaN,A
1399951,23224,2023-02-06,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.005917,NaN,A
1399952,23224,2023-02-07,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.029762,NaN,A
1399953,23224,2023-02-08,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.026012,NaN,A
1399954,23224,2023-02-09,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.026706,NaN,A
1399955,23224,2023-02-10,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.021341,NaN,A
1399956,23224,2023-02-13,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.020896,NaN,A
1399957,23224,2023-02-14,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.015244,NaN,A
1399958,23224,2023-02-15,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.015480,NaN,A
1399959,23224,2023-02-16,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.027439,NaN,A
1399960,23224,2023-02-17,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.006270,NaN,A
1399961,23224,2023-02-21,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.025237,NaN,A
1399962,23224,2023-02-22,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.029126,NaN,A
1399963,23224,2023-02-23,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.000000,NaN,A
1399964,23224,2023-02-24,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.000000,NaN,A
1399965,23224,2023-02-27,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.013333,NaN,A
1399966,23224,2023-02-28,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.029605,NaN,A
1399967,23224,2023-03-01,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.012780,NaN,A
1399968,23224,2023-03-02,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.053628,NaN,A
1399969,23224,2023-03-03,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.016667,NaN,A
1399970,23224,2023-03-06,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.003390,NaN,A
1399971,23224,2023-03-07,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.006757,NaN,A
1399972,23224,2023-03-08,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.000000,NaN,A
1399973,23224,2023-03-09,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.020134,NaN,A
1399974,23224,2023-03-10,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.027397,NaN,A
1399975,23224,2023-03-13,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.073944,NaN,A
1399976,23224,2023-03-14,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.026923,NaN,A
1399977,23224,2023-03-15,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.051383,NaN,A
1399978,23224,2023-03-16,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.020833,NaN,A
1399979,23224,2023-03-17,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.000000,NaN,A
1399980,23224,2023-03-20,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.032653,NaN,A
1399981,23224,2023-03-21,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.071730,NaN,A
1399982,23224,2023-03-22,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.035433,NaN,A
1399983,23224,2023-03-23,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.016327,NaN,A
1399984,23224,2023-03-24,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.020080,NaN,A
1399985,23224,2023-03-27,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.051181,NaN,A
1399986,23224,2023-03-28,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.033708,NaN,A
1399987,23224,2023-03-29,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.039855,NaN,A
1399988,23224,2023-03-30,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.003484,NaN,A
1399989,23224,2023-03-31,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.048951,NaN,A
1399990,23224,2023-04-03,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.010000,NaN,A
1399991,23224,2023-04-04,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.003367,NaN,A
1399992,23224,2023-04-05,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.010135,NaN,A
1399993,23224,2023-04-06,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.016722,NaN,A
1399994,23224,2023-04-10,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.081633,NaN,A
1399995,23224,2023-04-11,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.062893,NaN,A
1399996,23224,2023-04-12,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.044379,NaN,A
1399997,23224,2023-04-13,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,0.000000,NaN,A
1399998,23224,2023-04-14,35953C10,FTAI INFRASTRUCTURE INC,FIP,-1.0,Q,-0.006192,NaN,A
1399999,23224,2023-04-17,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.003115,NaN,A
1400000,23224,2023-04-18,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.018750,NaN,A
1400001,23224,2023-04-19,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.028662,NaN,A
1400002,23224,2023-04-20,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.016393,NaN,A
1400003,23224,2023-04-21,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.000000,NaN,A
1400004,23224,2023-04-24,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.026667,NaN,A
1400005,23224,2023-04-25,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.089041,NaN,A
1400006,23224,2023-04-26,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.022556,NaN,A
1400007,23224,2023-04-27,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.137868,NaN,A
1400008,23224,2023-04-28,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.001615,NaN,A
1400009,23224,2023-05-01,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.006452,NaN,A
1400010,23224,2023-05-02,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.048701,NaN,A
1400011,23224,2023-05-03,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.075085,NaN,A
1400012,23224,2023-05-04,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.015873,NaN,A
1400013,23224,2023-05-05,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.000000,NaN,A
1400014,23224,2023-05-08,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.009677,NaN,A
1400015,23224,2023-05-09,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.015974,NaN,A
1400016,23224,2023-05-10,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.009434,NaN,A
1400017,23224,2023-05-11,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.015576,NaN,A
1400018,23224,2023-05-12,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.003165,NaN,A
1400019,23224,2023-05-15,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.022436,NaN,A
1400020,23224,2023-05-16,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.006270,NaN,A
1400021,23224,2023-05-17,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.056075,NaN,A
1400022,23224,2023-05-18,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.029499,NaN,A
1400023,23224,2023-05-19,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.015198,NaN,A
1400024,23224,2023-05-22,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.070988,NaN,A
1400025,23224,2023-05-23,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.063401,NaN,A
1400026,23224,2023-05-24,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.021538,NaN,A
1400027,23224,2023-05-25,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.012579,NaN,A
1400028,23224,2023-05-26,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.025478,NaN,A
1400029,23224,2023-05-30,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.009317,NaN,A
1400030,23224,2023-05-31,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.000000,NaN,A
1400031,23224,2023-06-01,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.055385,NaN,A
1400032,23224,2023-06-02,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.049563,NaN,A
1400033,23224,2023-06-05,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.016667,NaN,A
1400034,23224,2023-06-06,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.002732,NaN,A
1400035,23224,2023-06-07,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.010899,NaN,A
1400036,23224,2023-06-08,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.000000,NaN,A
1400037,23224,2023-06-09,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.035813,NaN,A
1400038,23224,2023-06-12,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.005714,NaN,A
1400039,23224,2023-06-13,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.042614,NaN,A
1400040,23224,2023-06-14,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.002967,NaN,A
1400041,23224,2023-06-15,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.050595,NaN,A
1400042,23224,2023-06-16,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.025078,NaN,A
1400043,23224,2023-06-20,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.027523,NaN,A
1400044,23224,2023-06-21,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.035714,NaN,A
1400045,23224,2023-06-22,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.000000,NaN,A
1400046,23224,2023-06-23,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.037356,NaN,A
1400047,23224,2023-06-26,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.008955,NaN,A
1400048,23224,2023-06-27,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.023669,NaN,A
1400049,23224,2023-06-28,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.023121,NaN,A
1400050,23224,2023-06-29,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.002825,NaN,A
1400051,23224,2023-06-30,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.045326,NaN,A
1400052,23224,2023-07-03,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.024390,NaN,A
1400053,23224,2023-07-05,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.000000,NaN,A
1400054,23224,2023-07-06,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.022222,NaN,A
1400055,23224,2023-07-07,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.019886,NaN,A
1400056,23224,2023-07-10,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.002786,NaN,A
1400057,23224,2023-07-11,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.022346,NaN,A
1400058,23224,2023-07-12,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.028571,NaN,A
1400059,23224,2023-07-13,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.017647,NaN,A
1400060,23224,2023-07-14,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.017964,NaN,A
1400061,23224,2023-07-17,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.052941,NaN,A
1400062,23224,2023-07-18,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.019553,NaN,A
1400063,23224,2023-07-19,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.010959,NaN,A
1400064,23224,2023-07-20,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.036011,NaN,A
1400065,23224,2023-07-21,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.005747,NaN,A
1400066,23224,2023-07-24,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.025714,NaN,A
1400067,23224,2023-07-25,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.014663,NaN,A
1400068,23224,2023-07-26,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.002890,NaN,A
1400069,23224,2023-07-27,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.002899,NaN,A
1400070,23224,2023-07-28,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.000000,NaN,A
1400071,23224,2023-07-31,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.026012,NaN,A
1400072,23224,2023-08-01,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.014084,NaN,A
1400073,23224,2023-08-02,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.014286,NaN,A
1400074,23224,2023-08-03,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.005797,NaN,A
1400075,23224,2023-08-04,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.037464,NaN,A
1400076,23224,2023-08-07,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.022222,NaN,A
1400077,23224,2023-08-08,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.002740,NaN,A
1400078,23224,2023-08-09,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.008197,NaN,A
1400079,23224,2023-08-10,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.035230,NaN,A
1400080,23224,2023-08-11,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.008427,NaN,A
1400081,23224,2023-08-14,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.005571,NaN,A
1400082,23224,2023-08-15,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.005602,NaN,A
1400083,23224,2023-08-16,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.019718,NaN,A
1400084,23224,2023-08-17,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.008621,NaN,A
1400085,23224,2023-08-18,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.000000,NaN,A
1400086,23224,2023-08-21,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.042735,NaN,A
1400087,23224,2023-08-22,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.002976,NaN,A
1400088,23224,2023-08-23,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.023739,NaN,A
1400089,23224,2023-08-24,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.037681,NaN,A
1400090,23224,2023-08-25,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.003012,NaN,A
1400091,23224,2023-08-28,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.012012,NaN,A
1400092,23224,2023-08-29,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.023739,NaN,A
1400093,23224,2023-08-30,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.005797,NaN,A
1400094,23224,2023-08-31,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.002882,NaN,A
1400095,23224,2023-09-01,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.008621,NaN,A
1400096,23224,2023-09-05,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.017391,NaN,A
1400097,23224,2023-09-06,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.005900,NaN,A
1400098,23224,2023-09-07,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.002933,NaN,A
1400099,23224,2023-09-08,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.011696,NaN,A
1400100,23224,2023-09-11,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.000000,NaN,A
1400101,23224,2023-09-12,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.011561,NaN,A
1400102,23224,2023-09-13,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.025714,NaN,A
1400103,23224,2023-09-14,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.020528,NaN,A
1400104,23224,2023-09-15,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.014368,NaN,A
1400105,23224,2023-09-18,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.031161,NaN,A
1400106,23224,2023-09-19,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.026316,NaN,A
1400107,23224,2023-09-20,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.012012,NaN,A
1400108,23224,2023-09-21,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.015198,NaN,A
1400109,23224,2023-09-22,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.012346,NaN,A
1400110,23224,2023-09-25,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.012500,NaN,A
1400111,23224,2023-09-26,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.009259,NaN,A
1400112,23224,2023-09-27,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.015576,NaN,A
1400113,23224,2023-09-28,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.009202,NaN,A
1400114,23224,2023-09-29,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.003096,NaN,A
1400115,23224,2023-10-02,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.055901,NaN,A
1400116,23224,2023-10-03,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.046053,NaN,A
1400117,23224,2023-10-04,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.006897,NaN,A
1400118,23224,2023-10-05,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.003472,NaN,A
1400119,23224,2023-10-06,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.024390,NaN,A
1400120,23224,2023-10-09,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.017007,NaN,A
1400121,23224,2023-10-10,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.003460,NaN,A
1400122,23224,2023-10-11,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.100694,NaN,A
1400123,23224,2023-10-12,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.006309,NaN,A
1400124,23224,2023-10-13,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.006349,NaN,A
1400125,23224,2023-10-16,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.035144,NaN,A
1400126,23224,2023-10-17,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.003086,NaN,A
1400127,23224,2023-10-18,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.033846,NaN,A
1400128,23224,2023-10-19,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.015924,NaN,A
1400129,23224,2023-10-20,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.006472,NaN,A
1400130,23224,2023-10-23,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.003215,NaN,A
1400131,23224,2023-10-24,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.009677,NaN,A
1400132,23224,2023-10-25,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.012780,NaN,A
1400133,23224,2023-10-26,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.006309,NaN,A
1400134,23224,2023-10-27,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.025397,NaN,A
1400135,23224,2023-10-30,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.009772,NaN,A
1400136,23224,2023-10-31,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.006579,NaN,A
1400137,23224,2023-11-01,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.019608,NaN,A
1400138,23224,2023-11-02,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.012821,NaN,A
1400139,23224,2023-11-03,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.018987,NaN,A
1400140,23224,2023-11-06,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.006211,NaN,A
1400141,23224,2023-11-07,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.037500,NaN,A
1400142,23224,2023-11-08,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.027108,NaN,A
1400143,23224,2023-11-09,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.020710,NaN,A
1400144,23224,2023-11-10,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.006042,NaN,A
1400145,23224,2023-11-13,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.015015,NaN,A
1400146,23224,2023-11-14,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.065089,NaN,A
1400147,23224,2023-11-15,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.005556,NaN,A
1400148,23224,2023-11-16,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.000000,NaN,A
1400149,23224,2023-11-17,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.019553,NaN,A
1400150,23224,2023-11-20,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.002740,NaN,A
1400151,23224,2023-11-21,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.008242,NaN,A
1400152,23224,2023-11-22,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.024523,NaN,A
1400153,23224,2023-11-24,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.025140,NaN,A
1400154,23224,2023-11-27,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,-0.008174,NaN,A
1400155,23224,2023-11-28,35953C10,FTAI INFRASTRUCTURE INC,FIP,424710.0,Q,0.005495,NaN,A

In [53]:
Inputation_data_2.groupby("TICKER")["NAICS"].value_counts().head(500)

TICKER  NAICS
A        334516.0    206
         334515.0     44
AA       331318.0    250
AAA      525990.0    250
AAAU     525990.0    250
AACG     611699.0    250
AACI     523910.0    250
AACT     523910.0    140
AADI     325412.0    250
AADR     525990.0    250
AAGR     523910.0     16
AAL      481111.0    250
AAMC     523150.0    194
         523120.0     56
AAME     524113.0    250
AAN      532490.0    250
AAOI     334413.0    250
AAON     333415.0    250
AAP      441330.0    194
         441310.0     56
AAPB     525990.0    250
AAPD     525990.0    250
AAPL     334220.0    250
AAPU     525990.0    250
AAPY     525990.0     44
AAT      531110.0    250
AAU      213114.0    250
AAXJ     525990.0    251
AB       523940.0    209
         551112.0     41
ABAT     212390.0     70
ABB      551112.0     64
         335313.0     33
ABBV     325412.0    250
ABC      424210.0    165
ABCB     522110.0    250
ABCL     325414.0    250
ABCS     525990.0      7
ABEO     325412.0    250
ABEQ     525990.0    250
ABEV     312120.0    250
ABG      441110.0    250
ABIO     325412.0    250
ABL      523910.0    125
ABLV     551112.0     93
ABM      561720.0    250
ABNB     518210.0    250
ABOS     325414.0    250
ABR      531110.0    250
ABSI     541715.0    250
ABT      325412.0    181
         551112.0     69
ABTS     541511.0     29
ABUS     325412.0    250
ABVC     551112.0    250
ABVX     621999.0     49
AC       523910.0    250
ACA      333111.0    250
ACAB     523910.0    250
ACAC     561499.0    250
ACAD     325412.0    250
ACAH     523910.0    232
ACAX     523910.0    236
ACB      325411.0    250
ACBA     523910.0    250
ACCD     621610.0    250
ACCO     424120.0    250
ACDC     213112.0    250
ACEL     711510.0    250
ACES     525990.0    250
ACET     325412.0    250
ACGL     524210.0    250
ACGN     325414.0    149
ACHC     621999.0    250
ACHL     325412.0    250
ACHR     336411.0    250
ACHV     325412.0    250
ACI      445110.0    250
ACIC     524126.0     96
ACIO     525990.0    250
ACIU     541715.0    250
ACIW     513210.0    193
         511210.0     57
ACLS     333248.0    193
         333249.0     57
ACLX     325412.0    250
ACM      541330.0    250
ACMR     334413.0    250
ACN      541611.0    250
ACNB     522110.0    250
ACNT     331210.0    250
ACON     561499.0    250
ACOR     325414.0    250
ACP      525910.0    250
ACR      531110.0    250
ACRE     531110.0    252
ACRS     325412.0    250
ACRV     325412.0    193
        -1.0          57
ACRX     325412.0    250
ACSI     525990.0    250
ACST     325412.0    250
ACT      524113.0    251
ACTG     533110.0    250
ACTV     525990.0    250
ACU      332215.0    250
ACV      525990.0    250
ACVA     561499.0    250
ACVF     525990.0    250
ACWF     525990.0     39
ACWI     525990.0    250
ACWV     525990.0    250
ACWX     525990.0    250
ACXP     325411.0    250
ADAG     325412.0    250
ADAP     541715.0    250
ADBE     511210.0    250
ADC      531110.0    250
ADCT     325412.0    250
ADD      238990.0    250
ADEA     512199.0    250
ADES     423730.0    250
ADEX     523910.0    250
ADFI     525990.0    250
ADI      334413.0    250
ADIL     325412.0    250
ADIV     525990.0    251
ADM      311221.0    250
ADMA     325414.0    250
ADME     525990.0    250
ADMP     325412.0    171
ADN      455219.0    194
         452319.0     56
ADNT     336360.0    250
ADOC     523910.0    250
ADP      518210.0    250
ADPT     541715.0    250
ADPV     525990.0    250
ADRA     523910.0     28
ADRT     523910.0    250
ADSE     523910.0    250
ADSK     511210.0    250
ADT      561621.0    250
ADTH     541511.0    250
ADTN     334210.0    250
ADTX     621498.0    250
ADUS     621610.0    250
ADV      541810.0    250
ADVE     525990.0     69
ADVM     325414.0    250
ADX      525910.0    253
ADXN     325412.0    250
AE       424720.0    250
AEAE     523910.0    250
AEE      221118.0    250
AEF      525910.0    250
AEG      522299.0    126
         551112.0     63
         524113.0     61
AEHA     523910.0     30
AEHL     327120.0    250
AEHR     334515.0    250
AEI      531210.0    250
AEIS     334419.0    250
AEL      524113.0    250
AEM      212221.0    250
AEMB     525990.0    250
AEMD     334516.0    250
AENT     423990.0    127
AENZ     541330.0    235
AEO      448110.0    250
AEON     523910.0    112
AEP      221118.0    250
AER      532490.0    250
AERC     333413.0      7
AERT     523910.0     36
AES      221118.0    250
AESI     213115.0    206
AESR     525990.0    250
AETH     525990.0     63
AEVA     523910.0    250
AEY      423510.0    250
AEYE     512199.0    209
         541511.0     41
AEZS     325412.0    250
AFAR     523910.0    250
AFB      525910.0    250
AFBI     522110.0    250
AFCG     531210.0    250
AFG      524210.0    250
AFIB     339113.0    250
AFIF     525990.0    250
AFK      525990.0    250
AFL      524114.0    250
AFLG     525990.0    250
AFMC     525990.0    250
AFMD     424210.0    250
AFRI     541910.0    204
         561499.0     46
AFRM     522299.0    193
         522298.0     57
AFSM     525990.0    250
AFT      525910.0    250
AFTY     525990.0    250
AFYA     561499.0    250
AG       212220.0    193
         212222.0     57
AGAE     512110.0    250
AGBA     561499.0    250
AGCO     333111.0    250
AGD      525910.0    250
AGE      541715.0    250
AGEN     541720.0    250
AGFY     423820.0    250
AGG      525990.0    250
AGGH     525990.0    250
AGGY     525990.0    250
AGI      212221.0    250
AGIH     525990.0    250
AGIO     325412.0    250
AGL      524114.0    250
AGLE     325412.0    227
AGM      522298.0    500
AGMH     541511.0    250
AGNC     531110.0    250
AGNG     525990.0    250
AGO      524126.0    250
AGOX     525990.0    250
AGQ      525990.0    250
AGQI     525990.0     27
AGR      221118.0    250
AGRH     525990.0    250
AGRI     561499.0    250
AGRO     551112.0    250
AGRX     325412.0    250
AGS      114210.0    250
AGTI     532490.0    250
AGX      517911.0    250
AGYS     423430.0    250
AGZ      525990.0    250
AGZD     525990.0    250
AHCO     561499.0    250
AHG      522298.0    250
AHH      531312.0    250
AHI      541511.0    250
AHLT     525990.0     85
AHOY     525990.0    250
AHT      531110.0    250
AHYB     525990.0    250
AI       511210.0    250
AIA      525990.0    251
AIB      523910.0    250
AIDB     525990.0    152
AIEQ     525990.0    250
AIF      525990.0    250
AIG      524126.0    250
AIH      551112.0    250
AIHS     522291.0    250
AIM      325412.0    250
AIMD     325412.0    250
AIN      313210.0    250
AINC     523910.0    250
AIO      525910.0    250
AIP      334413.0    250
AIQ      525990.0    250
AIR      336412.0    250
AIRC     531110.0    250
AIRE     531210.0     48
AIRG     334220.0    250
AIRI     336412.0    250
AIRL     525990.0     15
AIRR     525990.0    250
AIRS     621111.0    250
AIRT     492110.0    250
AISP     523910.0      5
AIT      423840.0    250
AIU      523910.0    250
AIV      531110.0    250
AIVI     525990.0    250
AIVL     525990.0    250
AIXI    -1.0         205
AIYY     525990.0     23
AIZ      524210.0    250
AJG      524210.0    250
AJX      531110.0    250
AKA      561499.0    250
AKAM     511210.0    250
AKAN     325411.0    250
AKBA     325411.0    250
AKLI     523910.0    250
AKO      312111.0    500
AKR      531110.0    250
AKRO     424210.0    250
AKTS     334220.0    250
AKTX     541715.0    250
AKYA     541715.0    250
AL       532490.0    250
ALAR     551112.0    235
ALB      325211.0    250
ALBT     541611.0    250
ALC      525910.0    250
ALCC     523910.0    250
ALCE     523910.0      4
ALCO     111320.0    250
ALCY     523910.0    131
ALDX     325412.0    250
ALE      221118.0    250
ALEC     541715.0    250
ALEX     531210.0    250
ALG      333111.0    250
ALGM     334413.0    250
ALGN     339113.0    250
ALGS     541715.0    250
ALGT     481111.0    250
ALHC     524114.0    250
ALIM     325412.0    250
ALIT     518210.0    250
ALK      481111.0    250
ALKS     325412.0    250
ALKT     541512.0    250
ALL      524126.0    250
ALLE     561621.0    250
ALLG     523910.0    250
ALLK     424210.0    250
ALLO     541715.0    250
ALLR     325412.0    250
ALLT     541511.0    250
ALLY     522110.0    250
ALNT     334515.0     90
ALNY     325412.0    250
ALOT     334118.0    250
ALPA     561499.0    133
ALPN     325412.0    250
ALPP     541511.0    250
ALRM     561621.0    250
ALRN     541720.0    250
ALRS     522110.0    250
ALSA     523910.0    250
ALSN     423690.0    250
ALT      325412.0    250
ALTG     561499.0    250
ALTI     523910.0    249
ALTL     525990.0    250
ALTO     325199.0    250
ALTR     513210.0    193
         511210.0     57
ALTU     523910.0    250
ALTY     525990.0    250
ALUM     525990.0     59
ALUR     523910.0    105
ALV      336390.0    250
ALVO     523910.0    250
ALVR     325412.0    250
ALX      531110.0    250
ALXO     621399.0    250
ALYA     541512.0    250
ALZN     541720.0    250
AM       486210.0    250
AMAL     522110.0    250
AMAO     523910.0    210
AMAT     333249.0    237
         333248.0     13
AMAX     525990.0    250
AMBA     334413.0    250
AMBC     523120.0    250
AMBI     523910.0    208
AMBO     611699.0    250
AMBP     332431.0    250
AMC      512131.0    250
AMCI     523910.0     27
AMCR     453998.0    250
AMCX     449210.0    193
         443142.0     57
AMD      334413.0    250
AMDS     525990.0     91
AMDY     525990.0     72
AME      334513.0    250
AMED     621610.0    250
AMEH     621999.0    250
AMFI    -1.0           1
AMG      523120.0    237
         523150.0     13
AMGN     325414.0    250
AMH      531110.0    250
AMID     525990.0    250
AMK      523930.0    250
AMKR     334413.0    250
AMLI     213114.0    245
AMLP     525990.0    250
AMLX     424210.0    250
AMN      561311.0    250
AMNB     522110.0    250
AMOM     525990.0    250
AMOT     334515.0    160
AMP      523940.0    188
         523930.0     62
AMPD     525990.0    155
AMPE     325412.0    250
AMPG     334310.0    250
AMPH     325412.0    250
AMPL     541511.0    250
AMPS     221118.0    250
AMPX     336320.0    250
AMPY     211120.0    250
AMR      212111.0    250
AMRC     238210.0    250
AMRK     423940.0    250
AMRN     523910.0    250
AMRX     424210.0    250
AMS      532283.0    250
AMSC     335312.0    250
AMSF     524126.0    251
AMST     511210.0    250
AMSWA    513210.0    194
         511210.0     56
AMT      531110.0    250
AMTB     522110.0    250
AMTD     561499.0    250
AMTX     325120.0    194
         325199.0     56
AMV      423120.0     91
AMWD     337110.0    250
AMWL     513210.0    194
         511210.0     56
AMX      551112.0    250
AMZA     525990.0    250
AMZD     525990.0    250
AMZN     454110.0    250
AMZP     525990.0     42
AMZU     525990.0    250
AMZY     525990.0    111
AN       441110.0    250
ANAB     541715.0    250
ANDE     115114.0    250
ANEB     561499.0    250
ANET     334118.0    250
ANEW     525990.0    250
ANF      448140.0    250
ANGH     523910.0    250
ANGI     541890.0    250
ANGL     525990.0    250
ANGN     325412.0    104
ANGO     339112.0    250
ANIK     339112.0    250
ANIP     325412.0    250
ANIX     325414.0    250
ANL      551112.0     64
ANNX     541720.0    250
ANPC     621511.0     96
ANSS     513210.0    193
         511210.0     57
ANTE     541810.0    250
ANTX     621399.0    250
ANVS     541715.0    250
ANY      523910.0    250
ANZU     523910.0    187
AOA      525990.0    250
AOD      525990.0    250
AOGO     523910.0    250
AOK      525990.0    250
AOM      525990.0    250
AOMR     531110.0    250
AON      524210.0    250
AONC     523910.0     70
AOR      525990.0    250
AORT     339112.0    250
AOS      335220.0    250
AOSL     334413.0    250
AOTG     525990.0    250
AOUT     332992.0    250
AP       333914.0    250
APA      211120.0    250
APAC     523910.0    250
APAM     523940.0    194
         523930.0     57
APCA     523910.0    250
APCB     525990.0    167
APCX     561499.0    250
APD      325612.0    250
APDN     541715.0    250
APEI     611310.0    250
APG      523150.0    193
         523120.0     57
APGE     541910.0    118
APH      334417.0    250
API      513199.0    194
         511199.0     56
APIE     525990.0    167
APLD     334511.0    250
APLE     721110.0    212
         531110.0     39
APLM     523910.0    190
APLS     325412.0    250
APLT     325412.0    250
APLY     525990.0    178
APM      424210.0    250
APMU     525990.0    167
APO      523940.0    183
         523930.0     67
APOG     327215.0    250
Name: count, dtype: int64

In [54]:
Inputation_data_2.isnull().any()

PERMNO      False
date        False
CUSIP       False
COMNAM      False
TICKER      False
NAICS       False
PRIMEXCH    False
RET          True
DLPDT        True
TRDSTAT     False
dtype: bool

In [55]:
# # strategies for missing/null values

# # Drop the 'DLPDT' column
# selected_data = selected_data.drop(columns=['DLPDT'])

# # Impute missing values in 'COMNAM' with 'Unknown'
# selected_data['COMNAM'].fillna('Unknown', inplace=True)

# # Drop rows with missing 'TICKER'
# selected_data = selected_data.dropna(subset=['TICKER'])

# # Impute missing values in 'NAICS' with -1
# selected_data['NAICS'].fillna(-1, inplace=True)

# # Impute missing values in 'PRIMEXCH' with the most frequent value
# selected_data['PRIMEXCH'].fillna(selected_data['PRIMEXCH'].mode()[0], inplace=True)

# # Drop rows with missing 'RET'
# selected_data = selected_data.dropna(subset=['RET'])

# print(selected_data.head())

### RET

In [56]:
Inputation_data_3 = Inputation_data_2

In [57]:
Inputation_data_3.isnull().any()

PERMNO      False
date        False
CUSIP       False
COMNAM      False
TICKER      False
NAICS       False
PRIMEXCH    False
RET          True
DLPDT        True
TRDSTAT     False
dtype: bool

In [58]:
see_Inputation_data_3 = Inputation_data_3.groupby("CUSIP")["RET"].value_counts(dropna=False).reset_index()
see_Inputation_data_3.loc[see_Inputation_data_3["RET"].isnull() == 1].sort_values(by="count")

            CUSIP  RET  count
12966    00168310  NaN      1
2069315  G7527111  NaN      1
2046149  G5211011  NaN      1
1982006  98420Q30  NaN      1
1859362  92189F73  NaN      1
1854433  92189F40  NaN      1
1723427  87124110  NaN      1
1686571  84445C10  NaN      1
1607388  78486Q10  NaN      1
1527016  74933X30  NaN      1
1249851  60256630  NaN      1
1168518  53228M10  NaN      1
866882   45257L10  NaN      1
2094265  H1718210  NaN      1
49911    00777C20  NaN      1
82226    02043Q10  NaN      1
426744   23816M20  NaN      1
256848   10501E20  NaN      1
139763   03836J20  NaN      1
211933   09063M20  NaN      1
141533   03881F10  NaN      1
1654567  82669G10  NaN      2
531937   29082810  NaN      2
2009250  G1176510  NaN      2
94369    02155X20  NaN      2
1384979  69242L10  NaN      2
1386827  69324R10  NaN      2
320822   15130G70  NaN      2
854475   44916E10  NaN      4
1371703  68386J20  NaN      4
487540   26853E10  NaN      4
694514   35147130  NaN      4
1115499  48669G10  NaN      5
38821    00702410  NaN      6
1951725  96951B10  NaN      7
1240363  59071710  NaN      7
2065277  G7114V10  NaN      8
2092080  G989A610  NaN     10

In [59]:
# Convert 'RET' column to numeric, coercing errors to NaN
Inputation_data_3.loc[:, "RET_numeric"] = pd.to_numeric(Inputation_data_3["RET"], errors="coerce")

# Identify non-numeric values
non_numeric_values = Inputation_data_3[Inputation_data_3["RET_numeric"].isna() & Inputation_data_3["RET"].notna()]

print("Non-numeric values in 'RET' column:")
print(non_numeric_values[["RET"]])

<ipython-input-59-e7f0ba2fd04d>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Inputation_data_3.loc[:,'RET_numeric'] = pd.to_numeric(Inputation_data_3['RET'], errors='coerce')

Non-numeric values in 'RET' column:
        RET
599558    C
874661    C
967951    C
987824    C
1033592   C
...      ..
1573465   C
1573480   C
1573487   C
2153873   C
2217576   C

[792 rows x 1 columns]

In [60]:
Inputation_data_3

,PERMNO,date,CUSIP,COMNAM,TICKER,NAICS,PRIMEXCH,RET,DLPDT,TRDSTAT,RET_numeric
0,10026,2023-01-03,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,0.011823,NaN,A,0.011823
1,10026,2023-01-04,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,-0.001716,NaN,A,-0.001716
2,10026,2023-01-05,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,-0.010713,NaN,A,-0.010713
3,10026,2023-01-06,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,0.020321,NaN,A,0.020321
4,10026,2023-01-09,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,-0.019851,NaN,A,-0.019851
...,...,...,...,...,...,...,...,...,...,...,...
2354825,93436,2023-12-22,88160R10,TESLA INC,TSLA,336110.0,Q,-0.007701,NaN,A,-0.007701
2354826,93436,2023-12-26,88160R10,TESLA INC,TSLA,336110.0,Q,0.016116,NaN,A,0.016116
2354827,93436,2023-12-27,88160R10,TESLA INC,TSLA,336110.0,Q,0.018822,NaN,A,0.018822
2354828,93436,2023-12-28,88160R10,TESLA INC,TSLA,336110.0,Q,-0.031594,NaN,A,-0.031594
2354829,93436,2023-12-29,88160R10,TESLA INC,TSLA,336110.0,Q,-0.018564,NaN,A,-0.018564

In [61]:
Inputation_data_3.dtypes

PERMNO           int64
date            object
CUSIP           object
COMNAM          object
TICKER          object
NAICS          float64
PRIMEXCH        object
RET             object
DLPDT           object
TRDSTAT         object
RET_numeric    float64
dtype: object

In [62]:
Inputation_data_3["RET"].describe().T

count     2239304.0
unique     247970.0
top             0.0
freq        47661.0
Name: RET, dtype: float64

Missing Return Codes

RET(t)	| Reason For Missing Return  
-66.0	| more than 10 periods between time t and the time of the preceding price t'  
-77.0	| not trading on the current exchange at time t  
-88.0	| no return, array index t not within range of BEGRET and ENDRET  
-99.0	| missing return due to missing price at time t

In [63]:
Inputation_data_3[Inputation_data_3["RET"] == -66.0]

Empty DataFrame
Columns: [PERMNO, date, CUSIP, COMNAM, TICKER, NAICS, PRIMEXCH, RET, DLPDT, TRDSTAT, RET_numeric]
Index: []

In [64]:
Inputation_data_3[Inputation_data_3["RET"] == -77.0]

Empty DataFrame
Columns: [PERMNO, date, CUSIP, COMNAM, TICKER, NAICS, PRIMEXCH, RET, DLPDT, TRDSTAT, RET_numeric]
Index: []

In [65]:
Inputation_data_3[Inputation_data_3["RET"] == -88.0]

Empty DataFrame
Columns: [PERMNO, date, CUSIP, COMNAM, TICKER, NAICS, PRIMEXCH, RET, DLPDT, TRDSTAT, RET_numeric]
Index: []

In [66]:
Inputation_data_3[Inputation_data_3["RET"] == -99.0]

Empty DataFrame
Columns: [PERMNO, date, CUSIP, COMNAM, TICKER, NAICS, PRIMEXCH, RET, DLPDT, TRDSTAT, RET_numeric]
Index: []

In [67]:
# Convert 'RET' column to numeric, coercing errors to NaN
Inputation_data_3["RET"] = pd.to_numeric(Inputation_data_3["RET"], errors="coerce")

<ipython-input-67-16551bbf2eaf>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Inputation_data_3['RET'] = pd.to_numeric(Inputation_data_3['RET'], errors='coerce')

In [68]:
see_Inputation_data_3 = Inputation_data_3.groupby("CUSIP")["RET"].value_counts(dropna=False).reset_index()
see_Inputation_data_3.loc[see_Inputation_data_3["RET"].isnull() == 1].sort_values(by="count")

            CUSIP  RET  count
1195     00039J30  NaN      1
1538450  75607T10  NaN      1
1557078  76550410  NaN      1
1573378  78423T20  NaN      1
1574835  78433H68  NaN      1
...           ...  ...    ...
38818    00702410  NaN      6
1240320  59071710  NaN      7
1951638  96951B10  NaN      7
2065160  G7114V10  NaN      8
2091957  G989A610  NaN     11

[827 rows x 3 columns]

In [69]:
Inputation_data_3[(Inputation_data_3["CUSIP"] == "G989A610")]

,PERMNO,date,CUSIP,COMNAM,TICKER,NAICS,PRIMEXCH,RET,DLPDT,TRDSTAT,RET_numeric
1394687,23199,2023-01-03,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.047131,NaN,A,0.047131
1394688,23199,2023-01-04,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.043053,NaN,A,0.043053
1394689,23199,2023-01-05,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.013133,NaN,A,-0.013133
1394690,23199,2023-01-06,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.001901,NaN,A,-0.001901
1394691,23199,2023-01-09,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.001905,NaN,A,0.001905
1394692,23199,2023-01-10,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.085551,NaN,A,-0.085551
1394693,23199,2023-01-11,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.060291,NaN,A,0.060291
1394694,23199,2023-01-12,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.005882,NaN,A,-0.005882
1394695,23199,2023-01-13,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.013807,NaN,A,-0.013807
1394696,23199,2023-01-17,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.018000,NaN,A,0.018000
1394697,23199,2023-01-18,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.027505,NaN,A,-0.027505
1394698,23199,2023-01-19,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.014141,NaN,A,-0.014141
1394699,23199,2023-01-20,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.012295,NaN,A,-0.012295
1394700,23199,2023-01-23,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.053942,NaN,A,0.053942
1394701,23199,2023-01-24,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.027559,NaN,A,-0.027559
1394702,23199,2023-01-25,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.010121,NaN,A,-0.010121
1394703,23199,2023-01-26,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.010225,NaN,A,0.010225
1394704,23199,2023-01-27,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.008097,NaN,A,-0.008097
1394705,23199,2023-01-30,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.036735,NaN,A,-0.036735
1394706,23199,2023-01-31,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.000000,NaN,A,0.000000
1394707,23199,2023-02-01,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.023305,NaN,A,-0.023305
1394708,23199,2023-02-02,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.032538,NaN,A,-0.032538
1394709,23199,2023-02-03,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.121076,NaN,A,-0.121076
1394710,23199,2023-02-06,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.043367,NaN,A,0.043367
1394711,23199,2023-02-07,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.029340,NaN,A,-0.029340
1394712,23199,2023-02-08,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.075567,NaN,A,-0.075567
1394713,23199,2023-02-09,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.076294,NaN,A,0.076294
1394714,23199,2023-02-10,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.060759,NaN,A,-0.060759
1394715,23199,2023-02-13,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.029650,NaN,A,-0.029650
1394716,23199,2023-02-14,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.058333,NaN,A,0.058333
1394717,23199,2023-02-15,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.023622,NaN,A,0.023622
1394718,23199,2023-02-16,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.041026,NaN,A,-0.041026
1394719,23199,2023-02-17,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.016043,NaN,A,-0.016043
1394720,23199,2023-02-21,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.035326,NaN,A,-0.035326
1394721,23199,2023-02-22,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.021127,NaN,A,0.021127
1394722,23199,2023-02-23,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.180690,NaN,A,0.180690
1394723,23199,2023-02-24,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.065421,NaN,A,-0.065421
1394724,23199,2023-02-27,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.112500,NaN,A,0.112500
1394725,23199,2023-02-28,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.024719,NaN,A,-0.024719
1394726,23199,2023-03-01,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.048387,NaN,A,0.048387
1394727,23199,2023-03-02,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.024176,NaN,A,0.024176
1394728,23199,2023-03-03,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.068670,NaN,A,0.068670
1394729,23199,2023-03-06,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.046185,NaN,A,-0.046185
1394730,23199,2023-03-07,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.014737,NaN,A,-0.014737
1394731,23199,2023-03-08,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.034188,NaN,A,0.034188
1394732,23199,2023-03-09,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.020661,NaN,A,-0.020661
1394733,23199,2023-03-10,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.059072,NaN,A,0.059072
1394734,23199,2023-03-13,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.011952,NaN,A,-0.011952
1394735,23199,2023-03-14,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.010081,NaN,A,0.010081
1394736,23199,2023-03-15,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.001996,NaN,A,-0.001996
1394737,23199,2023-03-16,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.006000,NaN,A,-0.006000
1394738,23199,2023-03-17,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.002012,NaN,A,-0.002012
1394739,23199,2023-03-20,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.114919,NaN,A,0.114919
1394740,23199,2023-03-21,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.027125,NaN,A,0.027125
1394741,23199,2023-03-22,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.012324,NaN,A,-0.012324
1394742,23199,2023-03-23,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.044546,NaN,A,-0.044546
1394743,23199,2023-03-24,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.054085,NaN,A,0.054085
1394744,23199,2023-03-27,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.026549,NaN,A,-0.026549
1394745,23199,2023-03-28,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.003636,NaN,A,-0.003636
1394746,23199,2023-03-29,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.008212,NaN,A,-0.008212
1394747,23199,2023-03-30,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.011960,NaN,A,0.011960
1394748,23199,2023-03-31,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.018182,NaN,A,0.018182
1394749,23199,2023-04-03,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.085714,NaN,A,0.085714
1394750,23199,2023-04-04,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.087171,NaN,A,0.087171
1394751,23199,2023-04-05,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.178502,NaN,A,-0.178502
1394752,23199,2023-04-06,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.049741,NaN,A,-0.049741
1394753,23199,2023-04-10,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.007752,NaN,A,-0.007752
1394754,23199,2023-04-11,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.035156,NaN,A,-0.035156
1394755,23199,2023-04-12,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.082996,NaN,A,-0.082996
1394756,23199,2023-04-13,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.105960,NaN,A,0.105960
1394757,23199,2023-04-14,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.027944,NaN,A,0.027944
1394758,23199,2023-04-17,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.104854,NaN,A,0.104854
1394759,23199,2023-04-18,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.049209,NaN,A,0.049209
1394760,23199,2023-04-19,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.045226,NaN,A,0.045226
1394761,23199,2023-04-20,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.028846,NaN,A,0.028846
1394762,23199,2023-04-21,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.024922,NaN,A,-0.024922
1394763,23199,2023-04-24,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.124601,NaN,A,0.124601
1394764,23199,2023-04-25,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.046875,NaN,A,-0.046875
1394765,23199,2023-04-26,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.001490,NaN,A,0.001490
1394766,23199,2023-04-27,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,1.976191,NaN,A,1.976191
1394767,23199,2023-04-28,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,4.410500,NaN,A,4.410500
1394768,23199,2023-05-01,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.523889,NaN,A,-0.523889
1394769,23199,2023-05-02,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.028921,NaN,A,0.028921
1394770,23199,2023-05-03,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.599698,NaN,A,0.599698
1394771,23199,2023-05-04,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.793868,NaN,A,-0.793868
1394772,23199,2023-05-05,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.371281,NaN,A,-0.371281
1394773,23199,2023-05-08,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.020928,NaN,A,0.020928
1394774,23199,2023-05-09,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.115865,NaN,A,-0.115865
1394775,23199,2023-05-10,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.040323,NaN,A,-0.040323
1394776,23199,2023-05-11,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.040966,NaN,A,-0.040966
1394777,23199,2023-05-12,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.302848,NaN,A,-0.302848
1394778,23199,2023-05-15,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,NaN,NaN,A,NaN
1394779,23199,2023-05-16,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,NaN,NaN,A,NaN
1394780,23199,2023-05-17,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,NaN,NaN,A,NaN
1394781,23199,2023-05-18,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,NaN,NaN,A,NaN
1394782,23199,2023-05-19,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,NaN,NaN,A,NaN
1394783,23199,2023-05-22,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,NaN,NaN,A,NaN
1394784,23199,2023-05-23,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,NaN,NaN,A,NaN
1394785,23199,2023-05-24,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,NaN,NaN,A,NaN
1394786,23199,2023-05-25,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,NaN,NaN,A,NaN
1394787,23199,2023-05-26,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,NaN,NaN,A,NaN
1394788,23199,2023-05-30,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,NaN,NaN,A,NaN
1394789,23199,2023-05-31,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.111861,NaN,A,-0.111861
1394790,23199,2023-06-01,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.079262,NaN,A,-0.079262
1394791,23199,2023-06-02,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.154481,NaN,A,-0.154481
1394792,23199,2023-06-05,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.185495,NaN,A,0.185495
1394793,23199,2023-06-06,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.063529,NaN,A,-0.063529
1394794,23199,2023-06-07,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.003769,NaN,A,0.003769
1394795,23199,2023-06-08,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.038798,NaN,A,-0.038798
1394796,23199,2023-06-09,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.016927,NaN,A,-0.016927
1394797,23199,2023-06-12,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.029139,NaN,A,-0.029139
1394798,23199,2023-06-13,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.034106,NaN,A,0.034106
1394799,23199,2023-06-14,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.027704,NaN,A,-0.027704
1394800,23199,2023-06-15,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.008141,NaN,A,-0.008141
1394801,23199,2023-06-16,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.025992,NaN,A,-0.025992
1394802,23199,2023-06-20,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.028090,NaN,A,-0.028090
1394803,23199,2023-06-21,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.018786,NaN,A,-0.018786
1394804,23199,2023-06-22,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.017673,NaN,A,-0.017673
1394805,23199,2023-06-23,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.065967,NaN,A,-0.065967
1394806,23199,2023-06-26,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.056180,NaN,A,-0.056180
1394807,23199,2023-06-27,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.020408,NaN,A,-0.020408
1394808,23199,2023-06-28,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.019097,NaN,A,-0.019097
1394809,23199,2023-06-29,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.380531,NaN,A,0.380531
1394810,23199,2023-06-30,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.203846,NaN,A,0.203846
1394811,23199,2023-07-03,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.141640,NaN,A,-0.141640
1394812,23199,2023-07-05,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.086849,NaN,A,-0.086849
1394813,23199,2023-07-06,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.093750,NaN,A,-0.093750
1394814,23199,2023-07-07,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.077961,NaN,A,0.077961
1394815,23199,2023-07-10,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.009736,NaN,A,0.009736
1394816,23199,2023-07-11,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.026171,NaN,A,-0.026171
1394817,23199,2023-07-12,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.018388,NaN,A,0.018388
1394818,23199,2023-07-13,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.015278,NaN,A,0.015278
1394819,23199,2023-07-14,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.027360,NaN,A,-0.027360
1394820,23199,2023-07-17,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.011252,NaN,A,0.011252
1394821,23199,2023-07-18,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.022253,NaN,A,-0.022253
1394822,23199,2023-07-19,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.113798,NaN,A,0.113798
1394823,23199,2023-07-20,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.043423,NaN,A,-0.043423
1394824,23199,2023-07-21,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.010681,NaN,A,0.010681
1394825,23199,2023-07-24,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.025099,NaN,A,-0.025099
1394826,23199,2023-07-25,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.014905,NaN,A,-0.014905
1394827,23199,2023-07-26,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.006878,NaN,A,-0.006878
1394828,23199,2023-07-27,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.038781,NaN,A,-0.038781
1394829,23199,2023-07-28,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.027378,NaN,A,0.027378
1394830,23199,2023-07-31,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.001403,NaN,A,-0.001403
1394831,23199,2023-08-01,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.007022,NaN,A,-0.007022
1394832,23199,2023-08-02,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.043847,NaN,A,-0.043847
1394833,23199,2023-08-03,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.008876,NaN,A,0.008876
1394834,23199,2023-08-04,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.004399,NaN,A,0.004399
1394835,23199,2023-08-07,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.045255,NaN,A,-0.045255
1394836,23199,2023-08-08,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.010703,NaN,A,-0.010703
1394837,23199,2023-08-09,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.026275,NaN,A,-0.026275
1394838,23199,2023-08-10,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.004762,NaN,A,-0.004762
1394839,23199,2023-08-11,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.038277,NaN,A,-0.038277
1394840,23199,2023-08-14,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.019900,NaN,A,0.019900
1394841,23199,2023-08-15,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.043902,NaN,A,-0.043902
1394842,23199,2023-08-16,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.020408,NaN,A,-0.020408
1394843,23199,2023-08-17,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.052083,NaN,A,-0.052083
1394844,23199,2023-08-18,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.150183,NaN,A,0.150183
1394845,23199,2023-08-21,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.052548,NaN,A,-0.052548
1394846,23199,2023-08-22,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.003361,NaN,A,-0.003361
1394847,23199,2023-08-23,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.011804,NaN,A,-0.011804
1394848,23199,2023-08-24,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.006826,NaN,A,0.006826
1394849,23199,2023-08-25,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.010169,NaN,A,-0.010169
1394850,23199,2023-08-28,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.025685,NaN,A,0.025685
1394851,23199,2023-08-29,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.025042,NaN,A,-0.025042
1394852,23199,2023-08-30,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.018836,NaN,A,-0.018836
1394853,23199,2023-08-31,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.013962,NaN,A,-0.013962
1394854,23199,2023-09-01,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.007080,NaN,A,0.007080
1394855,23199,2023-09-05,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.005272,NaN,A,-0.005272
1394856,23199,2023-09-06,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.005300,NaN,A,-0.005300
1394857,23199,2023-09-07,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.014210,NaN,A,-0.014210
1394858,23199,2023-09-08,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.012613,NaN,A,-0.012613
1394859,23199,2023-09-11,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.005474,NaN,A,-0.005474
1394860,23199,2023-09-12,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.009174,NaN,A,-0.009174
1394861,23199,2023-09-13,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.018519,NaN,A,0.018519
1394862,23199,2023-09-14,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.020000,NaN,A,0.020000
1394863,23199,2023-09-15,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.030303,NaN,A,-0.030303
1394864,23199,2023-09-18,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.001838,NaN,A,0.001838
1394865,23199,2023-09-19,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.003670,NaN,A,-0.003670
1394866,23199,2023-09-20,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.003683,NaN,A,-0.003683
1394867,23199,2023-09-21,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.049908,NaN,A,-0.049908
1394868,23199,2023-09-22,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.033074,NaN,A,-0.033074
1394869,23199,2023-09-25,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.080483,NaN,A,-0.080483
1394870,23199,2023-09-26,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.004376,NaN,A,-0.004376
1394871,23199,2023-09-27,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.026374,NaN,A,0.026374
1394872,23199,2023-09-28,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.072805,NaN,A,0.072805
1394873,23199,2023-09-29,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.023952,NaN,A,0.023952
1394874,23199,2023-10-02,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.011696,NaN,A,-0.011696
1394875,23199,2023-10-03,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.065089,NaN,A,-0.065089
1394876,23199,2023-10-04,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.040084,NaN,A,0.040084
1394877,23199,2023-10-05,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.044625,NaN,A,-0.044625
1394878,23199,2023-10-06,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.023355,NaN,A,-0.023355
1394879,23199,2023-10-09,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.084783,NaN,A,0.084783
1394880,23199,2023-10-10,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.084168,NaN,A,-0.084168
1394881,23199,2023-10-11,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.041576,NaN,A,0.041576
1394882,23199,2023-10-12,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.010504,NaN,A,-0.010504
1394883,23199,2023-10-13,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.027601,NaN,A,0.027601
1394884,23199,2023-10-16,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.026859,NaN,A,0.026859
1394885,23199,2023-10-17,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.040242,NaN,A,0.040242
1394886,23199,2023-10-18,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.083172,NaN,A,-0.083172
1394887,23199,2023-10-19,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.090717,NaN,A,0.090717
1394888,23199,2023-10-20,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.077369,NaN,A,-0.077369
1394889,23199,2023-10-23,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.058700,NaN,A,0.058700
1394890,23199,2023-10-24,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.093069,NaN,A,0.093069

In [70]:
Inputation_data_3[Inputation_data_3["CUSIP"] == "G989A610"]["RET"].value_counts(dropna=False)

RET
 NaN         11
-0.020408     2
 0.000000     2
 0.018519     1
-0.010169     1
 0.025685     1
-0.025042     1
-0.018836     1
-0.013962     1
 0.007080     1
-0.005272     1
-0.005300     1
-0.014210     1
-0.012613     1
-0.005474     1
-0.009174     1
 0.020000     1
-0.011804     1
-0.030303     1
 0.001838     1
-0.003670     1
-0.003683     1
-0.049908     1
-0.033074     1
-0.080483     1
-0.004376     1
 0.026374     1
 0.072805     1
 0.023952     1
-0.011696     1
 0.006826     1
 0.047131     1
 0.040084     1
-0.003361     1
 0.011252     1
-0.022253     1
 0.113798     1
-0.043423     1
 0.010681     1
-0.025099     1
-0.014905     1
-0.006878     1
-0.038781     1
 0.027378     1
-0.001403     1
-0.007022     1
-0.043847     1
 0.008876     1
 0.004399     1
-0.045255     1
-0.010703     1
-0.026275     1
-0.004762     1
-0.038277     1
 0.019900     1
-0.043902     1
-0.052083     1
 0.150183     1
-0.052548     1
-0.065089     1
-0.044625     1
 0.015278     1
 0.024096     1
-0.011628     1
-0.009412     1
 0.064133     1
-0.042411     1
 0.030303     1
 0.013575     1
-0.020089     1
 0.045558     1
-0.002179     1
-0.043668     1
-0.020548     1
-0.032634     1
-0.014118     1
-0.018433     1
 0.002387     1
 0.030952     1
-0.016166     1
-0.016432     1
-0.035800     1
-0.004950     1
-0.032338     1
 0.020566     1
-0.005038     1
-0.063291     1
 0.054054     1
-0.005128     1
 0.009390     1
 0.033333     1
-0.023355     1
-0.101449     1
 0.084783     1
-0.084168     1
 0.041576     1
-0.010504     1
 0.027601     1
 0.026859     1
 0.040242     1
-0.083172     1
 0.090717     1
-0.077369     1
 0.058700     1
 0.093069     1
 0.068548     1
 0.004785     1
-0.122642     1
 0.012903     1
-0.057325     1
 0.056306     1
-0.072495     1
 0.022988     1
-0.011236     1
-0.002273     1
-0.013667     1
 0.004619     1
-0.004598     1
-0.034642     1
-0.027360     1
-0.026171     1
 0.018388     1
 0.034188     1
-0.016043     1
-0.035326     1
 0.021127     1
 0.180690     1
-0.065421     1
 0.112500     1
-0.024719     1
 0.048387     1
 0.024176     1
 0.068670     1
-0.046185     1
-0.014737     1
-0.020661     1
-0.008212     1
 0.059072     1
-0.011952     1
 0.010081     1
-0.001996     1
-0.006000     1
-0.002012     1
 0.114919     1
 0.027125     1
-0.012324     1
-0.044546     1
 0.054085     1
-0.026549     1
-0.041026     1
 0.023622     1
 0.058333     1
-0.029650     1
-0.013133     1
-0.001901     1
 0.001905     1
-0.085551     1
 0.060291     1
-0.005882     1
-0.013807     1
 0.018000     1
-0.027505     1
-0.014141     1
-0.012295     1
 0.053942     1
-0.027559     1
-0.010121     1
 0.010225     1
-0.008097     1
-0.036735     1
-0.023305     1
-0.032538     1
-0.121076     1
 0.043367     1
-0.029340     1
-0.075567     1
 0.076294     1
-0.060759     1
-0.003636     1
 0.011960     1
 0.043053     1
-0.025992     1
-0.111861     1
-0.079262     1
-0.154481     1
 0.185495     1
-0.063529     1
 0.003769     1
-0.038798     1
-0.016927     1
-0.029139     1
 0.034106     1
-0.027704     1
-0.008141     1
-0.028090     1
 0.018182     1
-0.018786     1
-0.017673     1
-0.065967     1
-0.056180     1
-0.019097     1
 0.380531     1
 0.203846     1
-0.141640     1
-0.086849     1
-0.093750     1
 0.077961     1
 0.009736     1
-0.302848     1
-0.040966     1
-0.040323     1
-0.115865     1
 0.085714     1
 0.087171     1
-0.178502     1
-0.049741     1
-0.007752     1
-0.035156     1
-0.082996     1
 0.105960     1
 0.027944     1
 0.104854     1
 0.049209     1
 0.045226     1
 0.028846     1
-0.024922     1
 0.124601     1
-0.046875     1
 0.001490     1
 1.976191     1
 4.410500     1
-0.523889     1
 0.028921     1
 0.599698     1
-0.793868     1
-0.371281     1
 0.020928     1
-0.025773     1
Name: count, dtype: int64

In [71]:
Inputation_data_3["RET"].value_counts()

RET
 0.000000    61932
-0.019608      614
-0.020000      555
-0.038462      554
-0.028571      542
             ...
 0.068274        1
 0.192188        1
-0.054501        1
 0.182869        1
 0.059344        1
Name: count, Length: 172848, dtype: int64

In [72]:
# # Drop rows with NaN values in 'RET' column
# Inputation_data_3 = Inputation_data_3.dropna(subset=['RET'])

In [73]:
# First forward fill, then backward fill
Inputation_data_3["RET"] = Inputation_data_3["RET"].ffill().bfill()

<ipython-input-73-fc6448243e94>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Inputation_data_3['RET'] = Inputation_data_3['RET'].ffill().bfill()

In [74]:
see_Inputation_data_3 = Inputation_data_3.groupby("CUSIP")["RET"].value_counts(dropna=False).reset_index()
see_Inputation_data_3.loc[see_Inputation_data_3["RET"].isnull() == 1].sort_values(by="count")

Empty DataFrame
Columns: [CUSIP, RET, count]
Index: []

In [75]:
Inputation_data_3[(Inputation_data_3["CUSIP"] == "G989A610")]

,PERMNO,date,CUSIP,COMNAM,TICKER,NAICS,PRIMEXCH,RET,DLPDT,TRDSTAT,RET_numeric
1394687,23199,2023-01-03,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.047131,NaN,A,0.047131
1394688,23199,2023-01-04,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.043053,NaN,A,0.043053
1394689,23199,2023-01-05,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.013133,NaN,A,-0.013133
1394690,23199,2023-01-06,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.001901,NaN,A,-0.001901
1394691,23199,2023-01-09,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.001905,NaN,A,0.001905
1394692,23199,2023-01-10,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.085551,NaN,A,-0.085551
1394693,23199,2023-01-11,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.060291,NaN,A,0.060291
1394694,23199,2023-01-12,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.005882,NaN,A,-0.005882
1394695,23199,2023-01-13,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.013807,NaN,A,-0.013807
1394696,23199,2023-01-17,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.018000,NaN,A,0.018000
1394697,23199,2023-01-18,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.027505,NaN,A,-0.027505
1394698,23199,2023-01-19,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.014141,NaN,A,-0.014141
1394699,23199,2023-01-20,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.012295,NaN,A,-0.012295
1394700,23199,2023-01-23,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.053942,NaN,A,0.053942
1394701,23199,2023-01-24,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.027559,NaN,A,-0.027559
1394702,23199,2023-01-25,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.010121,NaN,A,-0.010121
1394703,23199,2023-01-26,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.010225,NaN,A,0.010225
1394704,23199,2023-01-27,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.008097,NaN,A,-0.008097
1394705,23199,2023-01-30,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.036735,NaN,A,-0.036735
1394706,23199,2023-01-31,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.000000,NaN,A,0.000000
1394707,23199,2023-02-01,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.023305,NaN,A,-0.023305
1394708,23199,2023-02-02,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.032538,NaN,A,-0.032538
1394709,23199,2023-02-03,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.121076,NaN,A,-0.121076
1394710,23199,2023-02-06,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.043367,NaN,A,0.043367
1394711,23199,2023-02-07,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.029340,NaN,A,-0.029340
1394712,23199,2023-02-08,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.075567,NaN,A,-0.075567
1394713,23199,2023-02-09,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.076294,NaN,A,0.076294
1394714,23199,2023-02-10,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.060759,NaN,A,-0.060759
1394715,23199,2023-02-13,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.029650,NaN,A,-0.029650
1394716,23199,2023-02-14,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.058333,NaN,A,0.058333
1394717,23199,2023-02-15,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.023622,NaN,A,0.023622
1394718,23199,2023-02-16,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.041026,NaN,A,-0.041026
1394719,23199,2023-02-17,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.016043,NaN,A,-0.016043
1394720,23199,2023-02-21,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.035326,NaN,A,-0.035326
1394721,23199,2023-02-22,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.021127,NaN,A,0.021127
1394722,23199,2023-02-23,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.180690,NaN,A,0.180690
1394723,23199,2023-02-24,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.065421,NaN,A,-0.065421
1394724,23199,2023-02-27,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.112500,NaN,A,0.112500
1394725,23199,2023-02-28,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.024719,NaN,A,-0.024719
1394726,23199,2023-03-01,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.048387,NaN,A,0.048387
1394727,23199,2023-03-02,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.024176,NaN,A,0.024176
1394728,23199,2023-03-03,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.068670,NaN,A,0.068670
1394729,23199,2023-03-06,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.046185,NaN,A,-0.046185
1394730,23199,2023-03-07,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.014737,NaN,A,-0.014737
1394731,23199,2023-03-08,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.034188,NaN,A,0.034188
1394732,23199,2023-03-09,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.020661,NaN,A,-0.020661
1394733,23199,2023-03-10,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.059072,NaN,A,0.059072
1394734,23199,2023-03-13,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.011952,NaN,A,-0.011952
1394735,23199,2023-03-14,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.010081,NaN,A,0.010081
1394736,23199,2023-03-15,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.001996,NaN,A,-0.001996
1394737,23199,2023-03-16,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.006000,NaN,A,-0.006000
1394738,23199,2023-03-17,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.002012,NaN,A,-0.002012
1394739,23199,2023-03-20,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.114919,NaN,A,0.114919
1394740,23199,2023-03-21,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.027125,NaN,A,0.027125
1394741,23199,2023-03-22,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.012324,NaN,A,-0.012324
1394742,23199,2023-03-23,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.044546,NaN,A,-0.044546
1394743,23199,2023-03-24,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.054085,NaN,A,0.054085
1394744,23199,2023-03-27,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.026549,NaN,A,-0.026549
1394745,23199,2023-03-28,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.003636,NaN,A,-0.003636
1394746,23199,2023-03-29,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.008212,NaN,A,-0.008212
1394747,23199,2023-03-30,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.011960,NaN,A,0.011960
1394748,23199,2023-03-31,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.018182,NaN,A,0.018182
1394749,23199,2023-04-03,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.085714,NaN,A,0.085714
1394750,23199,2023-04-04,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.087171,NaN,A,0.087171
1394751,23199,2023-04-05,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.178502,NaN,A,-0.178502
1394752,23199,2023-04-06,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.049741,NaN,A,-0.049741
1394753,23199,2023-04-10,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.007752,NaN,A,-0.007752
1394754,23199,2023-04-11,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.035156,NaN,A,-0.035156
1394755,23199,2023-04-12,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.082996,NaN,A,-0.082996
1394756,23199,2023-04-13,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.105960,NaN,A,0.105960
1394757,23199,2023-04-14,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.027944,NaN,A,0.027944
1394758,23199,2023-04-17,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.104854,NaN,A,0.104854
1394759,23199,2023-04-18,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.049209,NaN,A,0.049209
1394760,23199,2023-04-19,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.045226,NaN,A,0.045226
1394761,23199,2023-04-20,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.028846,NaN,A,0.028846
1394762,23199,2023-04-21,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.024922,NaN,A,-0.024922
1394763,23199,2023-04-24,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.124601,NaN,A,0.124601
1394764,23199,2023-04-25,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.046875,NaN,A,-0.046875
1394765,23199,2023-04-26,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.001490,NaN,A,0.001490
1394766,23199,2023-04-27,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,1.976191,NaN,A,1.976191
1394767,23199,2023-04-28,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,4.410500,NaN,A,4.410500
1394768,23199,2023-05-01,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.523889,NaN,A,-0.523889
1394769,23199,2023-05-02,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.028921,NaN,A,0.028921
1394770,23199,2023-05-03,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.599698,NaN,A,0.599698
1394771,23199,2023-05-04,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.793868,NaN,A,-0.793868
1394772,23199,2023-05-05,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.371281,NaN,A,-0.371281
1394773,23199,2023-05-08,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.020928,NaN,A,0.020928
1394774,23199,2023-05-09,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.115865,NaN,A,-0.115865
1394775,23199,2023-05-10,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.040323,NaN,A,-0.040323
1394776,23199,2023-05-11,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.040966,NaN,A,-0.040966
1394777,23199,2023-05-12,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.302848,NaN,A,-0.302848
1394778,23199,2023-05-15,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.302848,NaN,A,NaN
1394779,23199,2023-05-16,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.302848,NaN,A,NaN
1394780,23199,2023-05-17,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.302848,NaN,A,NaN
1394781,23199,2023-05-18,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.302848,NaN,A,NaN
1394782,23199,2023-05-19,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.302848,NaN,A,NaN
1394783,23199,2023-05-22,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.302848,NaN,A,NaN
1394784,23199,2023-05-23,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.302848,NaN,A,NaN
1394785,23199,2023-05-24,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.302848,NaN,A,NaN
1394786,23199,2023-05-25,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.302848,NaN,A,NaN
1394787,23199,2023-05-26,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.302848,NaN,A,NaN
1394788,23199,2023-05-30,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.302848,NaN,A,NaN
1394789,23199,2023-05-31,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.111861,NaN,A,-0.111861
1394790,23199,2023-06-01,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.079262,NaN,A,-0.079262
1394791,23199,2023-06-02,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.154481,NaN,A,-0.154481
1394792,23199,2023-06-05,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.185495,NaN,A,0.185495
1394793,23199,2023-06-06,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.063529,NaN,A,-0.063529
1394794,23199,2023-06-07,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.003769,NaN,A,0.003769
1394795,23199,2023-06-08,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.038798,NaN,A,-0.038798
1394796,23199,2023-06-09,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.016927,NaN,A,-0.016927
1394797,23199,2023-06-12,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.029139,NaN,A,-0.029139
1394798,23199,2023-06-13,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.034106,NaN,A,0.034106
1394799,23199,2023-06-14,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.027704,NaN,A,-0.027704
1394800,23199,2023-06-15,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.008141,NaN,A,-0.008141
1394801,23199,2023-06-16,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.025992,NaN,A,-0.025992
1394802,23199,2023-06-20,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.028090,NaN,A,-0.028090
1394803,23199,2023-06-21,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.018786,NaN,A,-0.018786
1394804,23199,2023-06-22,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.017673,NaN,A,-0.017673
1394805,23199,2023-06-23,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.065967,NaN,A,-0.065967
1394806,23199,2023-06-26,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.056180,NaN,A,-0.056180
1394807,23199,2023-06-27,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.020408,NaN,A,-0.020408
1394808,23199,2023-06-28,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.019097,NaN,A,-0.019097
1394809,23199,2023-06-29,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.380531,NaN,A,0.380531
1394810,23199,2023-06-30,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.203846,NaN,A,0.203846
1394811,23199,2023-07-03,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.141640,NaN,A,-0.141640
1394812,23199,2023-07-05,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.086849,NaN,A,-0.086849
1394813,23199,2023-07-06,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.093750,NaN,A,-0.093750
1394814,23199,2023-07-07,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.077961,NaN,A,0.077961
1394815,23199,2023-07-10,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.009736,NaN,A,0.009736
1394816,23199,2023-07-11,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.026171,NaN,A,-0.026171
1394817,23199,2023-07-12,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.018388,NaN,A,0.018388
1394818,23199,2023-07-13,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.015278,NaN,A,0.015278
1394819,23199,2023-07-14,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.027360,NaN,A,-0.027360
1394820,23199,2023-07-17,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.011252,NaN,A,0.011252
1394821,23199,2023-07-18,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.022253,NaN,A,-0.022253
1394822,23199,2023-07-19,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.113798,NaN,A,0.113798
1394823,23199,2023-07-20,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.043423,NaN,A,-0.043423
1394824,23199,2023-07-21,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.010681,NaN,A,0.010681
1394825,23199,2023-07-24,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.025099,NaN,A,-0.025099
1394826,23199,2023-07-25,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.014905,NaN,A,-0.014905
1394827,23199,2023-07-26,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.006878,NaN,A,-0.006878
1394828,23199,2023-07-27,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.038781,NaN,A,-0.038781
1394829,23199,2023-07-28,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.027378,NaN,A,0.027378
1394830,23199,2023-07-31,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.001403,NaN,A,-0.001403
1394831,23199,2023-08-01,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.007022,NaN,A,-0.007022
1394832,23199,2023-08-02,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.043847,NaN,A,-0.043847
1394833,23199,2023-08-03,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.008876,NaN,A,0.008876
1394834,23199,2023-08-04,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.004399,NaN,A,0.004399
1394835,23199,2023-08-07,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.045255,NaN,A,-0.045255
1394836,23199,2023-08-08,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.010703,NaN,A,-0.010703
1394837,23199,2023-08-09,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.026275,NaN,A,-0.026275
1394838,23199,2023-08-10,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.004762,NaN,A,-0.004762
1394839,23199,2023-08-11,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.038277,NaN,A,-0.038277
1394840,23199,2023-08-14,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.019900,NaN,A,0.019900
1394841,23199,2023-08-15,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.043902,NaN,A,-0.043902
1394842,23199,2023-08-16,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.020408,NaN,A,-0.020408
1394843,23199,2023-08-17,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.052083,NaN,A,-0.052083
1394844,23199,2023-08-18,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.150183,NaN,A,0.150183
1394845,23199,2023-08-21,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.052548,NaN,A,-0.052548
1394846,23199,2023-08-22,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.003361,NaN,A,-0.003361
1394847,23199,2023-08-23,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.011804,NaN,A,-0.011804
1394848,23199,2023-08-24,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.006826,NaN,A,0.006826
1394849,23199,2023-08-25,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.010169,NaN,A,-0.010169
1394850,23199,2023-08-28,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.025685,NaN,A,0.025685
1394851,23199,2023-08-29,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.025042,NaN,A,-0.025042
1394852,23199,2023-08-30,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.018836,NaN,A,-0.018836
1394853,23199,2023-08-31,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.013962,NaN,A,-0.013962
1394854,23199,2023-09-01,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.007080,NaN,A,0.007080
1394855,23199,2023-09-05,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.005272,NaN,A,-0.005272
1394856,23199,2023-09-06,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.005300,NaN,A,-0.005300
1394857,23199,2023-09-07,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.014210,NaN,A,-0.014210
1394858,23199,2023-09-08,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.012613,NaN,A,-0.012613
1394859,23199,2023-09-11,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.005474,NaN,A,-0.005474
1394860,23199,2023-09-12,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.009174,NaN,A,-0.009174
1394861,23199,2023-09-13,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.018519,NaN,A,0.018519
1394862,23199,2023-09-14,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.020000,NaN,A,0.020000
1394863,23199,2023-09-15,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.030303,NaN,A,-0.030303
1394864,23199,2023-09-18,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.001838,NaN,A,0.001838
1394865,23199,2023-09-19,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.003670,NaN,A,-0.003670
1394866,23199,2023-09-20,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.003683,NaN,A,-0.003683
1394867,23199,2023-09-21,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.049908,NaN,A,-0.049908
1394868,23199,2023-09-22,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.033074,NaN,A,-0.033074
1394869,23199,2023-09-25,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.080483,NaN,A,-0.080483
1394870,23199,2023-09-26,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.004376,NaN,A,-0.004376
1394871,23199,2023-09-27,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.026374,NaN,A,0.026374
1394872,23199,2023-09-28,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.072805,NaN,A,0.072805
1394873,23199,2023-09-29,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.023952,NaN,A,0.023952
1394874,23199,2023-10-02,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.011696,NaN,A,-0.011696
1394875,23199,2023-10-03,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.065089,NaN,A,-0.065089
1394876,23199,2023-10-04,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.040084,NaN,A,0.040084
1394877,23199,2023-10-05,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.044625,NaN,A,-0.044625
1394878,23199,2023-10-06,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.023355,NaN,A,-0.023355
1394879,23199,2023-10-09,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.084783,NaN,A,0.084783
1394880,23199,2023-10-10,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.084168,NaN,A,-0.084168
1394881,23199,2023-10-11,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.041576,NaN,A,0.041576
1394882,23199,2023-10-12,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.010504,NaN,A,-0.010504
1394883,23199,2023-10-13,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.027601,NaN,A,0.027601
1394884,23199,2023-10-16,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.026859,NaN,A,0.026859
1394885,23199,2023-10-17,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.040242,NaN,A,0.040242
1394886,23199,2023-10-18,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.083172,NaN,A,-0.083172
1394887,23199,2023-10-19,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.090717,NaN,A,0.090717
1394888,23199,2023-10-20,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,-0.077369,NaN,A,-0.077369
1394889,23199,2023-10-23,G989A610,TOP FINANCIAL GROUP LTD,TOP,333514.0,Q,0.058700,NaN,A,0.058700

In [76]:
Inputation_data_3[Inputation_data_3["CUSIP"] == "G989A610"]["RET"].value_counts(dropna=False)

RET
-0.302848    12
-0.020408     2
 0.000000     2
 0.047131     1
-0.009174     1
-0.010169     1
 0.025685     1
-0.025042     1
-0.018836     1
-0.013962     1
 0.007080     1
-0.005272     1
-0.005300     1
-0.014210     1
-0.012613     1
-0.005474     1
 0.020000     1
 0.018519     1
-0.030303     1
 0.001838     1
-0.003670     1
-0.003683     1
-0.049908     1
-0.033074     1
-0.080483     1
-0.004376     1
 0.026374     1
 0.072805     1
 0.023952     1
-0.011696     1
 0.006826     1
-0.011804     1
 0.040084     1
-0.003361     1
 0.011252     1
-0.022253     1
 0.113798     1
-0.043423     1
 0.010681     1
-0.025099     1
-0.014905     1
-0.006878     1
-0.038781     1
 0.027378     1
-0.001403     1
-0.007022     1
-0.043847     1
 0.008876     1
 0.004399     1
-0.045255     1
-0.010703     1
-0.026275     1
-0.004762     1
-0.038277     1
 0.019900     1
-0.043902     1
-0.052083     1
 0.150183     1
-0.052548     1
-0.065089     1
-0.044625     1
 0.015278     1
 0.024096     1
-0.011628     1
-0.009412     1
 0.064133     1
-0.042411     1
 0.030303     1
 0.013575     1
-0.020089     1
 0.045558     1
-0.002179     1
-0.043668     1
-0.020548     1
-0.032634     1
-0.014118     1
-0.018433     1
 0.002387     1
 0.030952     1
-0.016166     1
-0.016432     1
-0.035800     1
-0.004950     1
-0.032338     1
 0.020566     1
-0.005038     1
-0.063291     1
 0.054054     1
-0.005128     1
 0.009390     1
 0.033333     1
-0.023355     1
-0.101449     1
 0.084783     1
-0.084168     1
 0.041576     1
-0.010504     1
 0.027601     1
 0.026859     1
 0.040242     1
-0.083172     1
 0.090717     1
-0.077369     1
 0.058700     1
 0.093069     1
 0.068548     1
 0.004785     1
-0.122642     1
 0.012903     1
-0.057325     1
 0.056306     1
-0.072495     1
 0.022988     1
-0.011236     1
-0.002273     1
-0.013667     1
 0.004619     1
-0.004598     1
-0.034642     1
-0.027360     1
-0.026171     1
 0.018388     1
 0.034188     1
-0.016043     1
-0.035326     1
 0.021127     1
 0.180690     1
-0.065421     1
 0.112500     1
-0.024719     1
 0.048387     1
 0.024176     1
 0.068670     1
-0.046185     1
-0.014737     1
-0.020661     1
 0.043053     1
 0.059072     1
-0.011952     1
 0.010081     1
-0.001996     1
-0.006000     1
-0.002012     1
 0.114919     1
 0.027125     1
-0.012324     1
-0.044546     1
 0.054085     1
-0.026549     1
-0.041026     1
 0.023622     1
 0.058333     1
-0.029650     1
-0.013133     1
-0.001901     1
 0.001905     1
-0.085551     1
 0.060291     1
-0.005882     1
-0.013807     1
 0.018000     1
-0.027505     1
-0.014141     1
-0.012295     1
 0.053942     1
-0.027559     1
-0.010121     1
 0.010225     1
-0.008097     1
-0.036735     1
-0.023305     1
-0.032538     1
-0.121076     1
 0.043367     1
-0.029340     1
-0.075567     1
 0.076294     1
-0.060759     1
-0.003636     1
-0.008212     1
 0.011960     1
-0.040966     1
-0.079262     1
-0.154481     1
 0.185495     1
-0.063529     1
 0.003769     1
-0.038798     1
-0.016927     1
-0.029139     1
 0.034106     1
-0.027704     1
-0.008141     1
-0.025992     1
-0.028090     1
-0.018786     1
-0.017673     1
-0.065967     1
-0.056180     1
-0.019097     1
 0.380531     1
 0.203846     1
-0.141640     1
-0.086849     1
-0.093750     1
 0.077961     1
 0.009736     1
-0.111861     1
-0.040323     1
 0.018182     1
-0.115865     1
 0.085714     1
 0.087171     1
-0.178502     1
-0.049741     1
-0.007752     1
-0.035156     1
-0.082996     1
 0.105960     1
 0.027944     1
 0.104854     1
 0.049209     1
 0.045226     1
 0.028846     1
-0.024922     1
 0.124601     1
-0.046875     1
 0.001490     1
 1.976191     1
 4.410500     1
-0.523889     1
 0.028921     1
 0.599698     1
-0.793868     1
-0.371281     1
 0.020928     1
-0.025773     1
Name: count, dtype: int64

In [77]:
Inputation_data_3.isnull().any()

PERMNO         False
date           False
CUSIP          False
COMNAM         False
TICKER         False
NAICS          False
PRIMEXCH       False
RET            False
DLPDT           True
TRDSTAT        False
RET_numeric     True
dtype: bool

## Drop Duplicated Rows

In [78]:
filtered_data_3 = Inputation_data_3[
    [
        "PERMNO",
        "date",
        "CUSIP",
        "COMNAM",
        "TICKER",
        "NAICS",
        "PRIMEXCH",
        "RET",
        "TRDSTAT",
    ]
]

In [79]:
filtered_data_3

,PERMNO,date,CUSIP,COMNAM,TICKER,NAICS,PRIMEXCH,RET,TRDSTAT
0,10026,2023-01-03,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,0.011823,A
1,10026,2023-01-04,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,-0.001716,A
2,10026,2023-01-05,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,-0.010713,A
3,10026,2023-01-06,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,0.020321,A
4,10026,2023-01-09,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,-0.019851,A
...,...,...,...,...,...,...,...,...,...
2354825,93436,2023-12-22,88160R10,TESLA INC,TSLA,336110.0,Q,-0.007701,A
2354826,93436,2023-12-26,88160R10,TESLA INC,TSLA,336110.0,Q,0.016116,A
2354827,93436,2023-12-27,88160R10,TESLA INC,TSLA,336110.0,Q,0.018822,A
2354828,93436,2023-12-28,88160R10,TESLA INC,TSLA,336110.0,Q,-0.031594,A
2354829,93436,2023-12-29,88160R10,TESLA INC,TSLA,336110.0,Q,-0.018564,A

In [80]:
filtered_data_3.isnull().any()

PERMNO      False
date        False
CUSIP       False
COMNAM      False
TICKER      False
NAICS       False
PRIMEXCH    False
RET         False
TRDSTAT     False
dtype: bool

In [81]:
# Group by 'TICKER' and 'EXCHANGE' and count occurrences
grouped = filtered_data_3.groupby(["TICKER", "PRIMEXCH"]).size().reset_index(name="count")

# Filter groups with more than one occurrence
duplicates = grouped[grouped["count"] > 1]

# Display duplicate combinations
print(duplicates)

     TICKER PRIMEXCH  count
0         A        N    250
1        AA        N    250
2       AAA        R    250
3      AAAU        B    250
4      AACG        Q    250
...     ...      ...    ...
9626   ZVSA        Q    250
9627    ZWS        N    250
9628   ZYME        Q    250
9629   ZYXI        Q    250
9630    ZZZ        Q      2

[9620 rows x 3 columns]

In [82]:
duplicates["count"].describe()

count    9620.000000
mean      232.784511
std        53.677174
min         2.000000
25%       250.000000
50%       250.000000
75%       250.000000
max       502.000000
Name: count, dtype: float64

In [83]:
duplicates.sort_values(by="count")

     TICKER PRIMEXCH  count
9630    ZZZ        Q      2
6454   OYST        Q      2
6544   PCSB        Q      2
3261   FLYX        A      2
5883   NBBK        Q      2
...     ...      ...    ...
207     AGM        N    500
5165    LEN        N    500
3868    GTN        N    500
1179    BRK        N    500
4162    HVT        N    502

[9620 rows x 3 columns]

In [85]:
filtered_data_3["date"].nunique()

250

In [86]:
# # Display a sample of duplicate combinations to investigate
# sample_duplicates = duplicates.head(10)
# print(sample_duplicates)

# Investigate details of a specific duplicate combination
example_ticker = "HVT"
example_exchange = "N"
duplicate_details = filtered_data_3[
    (filtered_data_3["TICKER"] == example_ticker) & (filtered_data_3["PRIMEXCH"] == example_exchange)
]
print(duplicate_details)

         PERMNO        date     CUSIP                     COMNAM TICKER  \
4753      10294  2023-01-03  41959620  HAVERTY FURNITURE COS INC    HVT
4754      10294  2023-01-04  41959620  HAVERTY FURNITURE COS INC    HVT
4755      10294  2023-01-05  41959620  HAVERTY FURNITURE COS INC    HVT
4756      10294  2023-01-06  41959620  HAVERTY FURNITURE COS INC    HVT
4757      10294  2023-01-09  41959620  HAVERTY FURNITURE COS INC    HVT
...         ...         ...       ...                        ...    ...
1608113   41217  2023-12-22  41959610  HAVERTY FURNITURE COS INC    HVT
1608114   41217  2023-12-26  41959610  HAVERTY FURNITURE COS INC    HVT
1608115   41217  2023-12-27  41959610  HAVERTY FURNITURE COS INC    HVT
1608116   41217  2023-12-28  41959610  HAVERTY FURNITURE COS INC    HVT
1608117   41217  2023-12-29  41959610  HAVERTY FURNITURE COS INC    HVT

            NAICS PRIMEXCH       RET TRDSTAT
4753     443141.0        N  0.003125       A
4754     443141.0        N  0.008527       A
4755     443141.0        N -0.008130       A
4756     443141.0        N  0.058689       A
4757     443141.0        N -0.000619       A
...           ...      ...       ...     ...
1608113  443141.0        N -0.002545       A
1608114  443141.0        N  0.009073       A
1608115  443141.0        N  0.012925       A
1608116  443141.0        N  0.003329       A
1608117  443141.0        N -0.018524       A

[502 rows x 9 columns]

In [87]:
# Check for duplicate dates within each TICKER-PRIMEXCH group
duplicates_dates = filtered_data_3.duplicated(subset=["TICKER", "PRIMEXCH", "date"], keep=False)

# Display entries with duplicate dates
duplicate_dates_details = filtered_data_3[duplicates_dates]
duplicate_dates_details

,PERMNO,date,CUSIP,COMNAM,TICKER,NAICS,PRIMEXCH,RET,TRDSTAT
1026,10065,2023-02-09,00621210,ADAMS EXPRESS CO,ADX,525910.0,N,-0.004444,A
1027,10065,2023-02-09,00621210,ADAMS EXPRESS CO,ADX,525910.0,N,-0.004444,A
1028,10065,2023-02-09,00621210,ADAMS EXPRESS CO,ADX,525910.0,N,-0.004444,A
1223,10065,2023-11-17,00621210,ADAMS EXPRESS CO,ADX,525910.0,N,0.005653,A
1224,10065,2023-11-17,00621210,ADAMS EXPRESS CO,ADX,525910.0,N,0.005653,A
...,...,...,...,...,...,...,...,...,...
2321922,93117,2023-08-11,19842X10,COLUMBIA SELIG PREM TECH GR FD,STK,525910.0,N,-0.009571,A
2322810,93131,2023-01-03,29082810,EMCLAIRE FINANCIAL CORP,EMCF,522110.0,Q,-0.022199,A
2322811,93131,2023-01-03,29082810,EMCLAIRE FINANCIAL CORP,EMCF,522110.0,Q,-0.022199,A
2341068,93306,2023-12-20,44332N10,H WORLD GROUP LTD,HTHT,721110.0,Q,-0.009524,A
2341069,93306,2023-12-20,44332N10,H WORLD GROUP LTD,HTHT,721110.0,Q,-0.009524,A

In [88]:
filtered_data_3[(filtered_data_3["date"] == "2023-02-09") & (filtered_data_3["CUSIP"] == "00621210")]

,PERMNO,date,CUSIP,COMNAM,TICKER,NAICS,PRIMEXCH,RET,TRDSTAT
1026,10065,2023-02-09,00621210,ADAMS EXPRESS CO,ADX,525910.0,N,-0.004444,A
1027,10065,2023-02-09,00621210,ADAMS EXPRESS CO,ADX,525910.0,N,-0.004444,A
1028,10065,2023-02-09,00621210,ADAMS EXPRESS CO,ADX,525910.0,N,-0.004444,A

In [90]:
# Drop duplicate rows based on all columns
filtered_data_3 = filtered_data_3.drop_duplicates()
filtered_data_3

,PERMNO,date,CUSIP,COMNAM,TICKER,NAICS,PRIMEXCH,RET,TRDSTAT
0,10026,2023-01-03,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,0.011823,A
1,10026,2023-01-04,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,-0.001716,A
2,10026,2023-01-05,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,-0.010713,A
3,10026,2023-01-06,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,0.020321,A
4,10026,2023-01-09,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,-0.019851,A
...,...,...,...,...,...,...,...,...,...
2354825,93436,2023-12-22,88160R10,TESLA INC,TSLA,336110.0,Q,-0.007701,A
2354826,93436,2023-12-26,88160R10,TESLA INC,TSLA,336110.0,Q,0.016116,A
2354827,93436,2023-12-27,88160R10,TESLA INC,TSLA,336110.0,Q,0.018822,A
2354828,93436,2023-12-28,88160R10,TESLA INC,TSLA,336110.0,Q,-0.031594,A
2354829,93436,2023-12-29,88160R10,TESLA INC,TSLA,336110.0,Q,-0.018564,A

In [91]:
filtered_data_3

,PERMNO,date,CUSIP,COMNAM,TICKER,NAICS,PRIMEXCH,RET,TRDSTAT
0,10026,2023-01-03,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,0.011823,A
1,10026,2023-01-04,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,-0.001716,A
2,10026,2023-01-05,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,-0.010713,A
3,10026,2023-01-06,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,0.020321,A
4,10026,2023-01-09,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,-0.019851,A
...,...,...,...,...,...,...,...,...,...
2354825,93436,2023-12-22,88160R10,TESLA INC,TSLA,336110.0,Q,-0.007701,A
2354826,93436,2023-12-26,88160R10,TESLA INC,TSLA,336110.0,Q,0.016116,A
2354827,93436,2023-12-27,88160R10,TESLA INC,TSLA,336110.0,Q,0.018822,A
2354828,93436,2023-12-28,88160R10,TESLA INC,TSLA,336110.0,Q,-0.031594,A
2354829,93436,2023-12-29,88160R10,TESLA INC,TSLA,336110.0,Q,-0.018564,A

## Stock Filter
The only filters we applied is to only use tickers with at least 128 days of returns history at the time they are sampled, and removing tickers that had data issues with their adjusted closing prices as observed (tickers that had more than 10 days of over 100% or under -50% returns were removed, as these all had issues with their historical price data).

In [92]:
# Filter data based on minimum days of history and data quality
min_days = 128
gain_threshold = 1.0
loss_threshold = -0.5
max_bad_days = 10

# Ensure each ticker has at least 128 days of returns
ticker_counts = filtered_data_3["TICKER"].value_counts()
valid_tickers = ticker_counts[ticker_counts >= min_days].index
filtered_data = filtered_data_3[filtered_data_3["TICKER"].isin(valid_tickers)]

# Filter stocks with more than 10 bad days
bad_days_count = filtered_data.groupby("TICKER")["RET"].apply(
    lambda x: ((x > gain_threshold) | (x < loss_threshold)).sum()
)
good_stocks = bad_days_count[bad_days_count <= max_bad_days].index
filtered_data = filtered_data[filtered_data["TICKER"].isin(good_stocks)]

In [93]:
filtered_data

,PERMNO,date,CUSIP,COMNAM,TICKER,NAICS,PRIMEXCH,RET,TRDSTAT
0,10026,2023-01-03,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,0.011823,A
1,10026,2023-01-04,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,-0.001716,A
2,10026,2023-01-05,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,-0.010713,A
3,10026,2023-01-06,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,0.020321,A
4,10026,2023-01-09,46603210,J & J SNACK FOODS CORP,JJSF,311930.0,Q,-0.019851,A
...,...,...,...,...,...,...,...,...,...
2354825,93436,2023-12-22,88160R10,TESLA INC,TSLA,336110.0,Q,-0.007701,A
2354826,93436,2023-12-26,88160R10,TESLA INC,TSLA,336110.0,Q,0.016116,A
2354827,93436,2023-12-27,88160R10,TESLA INC,TSLA,336110.0,Q,0.018822,A
2354828,93436,2023-12-28,88160R10,TESLA INC,TSLA,336110.0,Q,-0.031594,A
2354829,93436,2023-12-29,88160R10,TESLA INC,TSLA,336110.0,Q,-0.018564,A

In [ ]:
# import pandas as pd

# # Assuming filtered_data_3 is already loaded and preprocessed

# # 1. Filter tickers with at least 128 days of returns history
# # Count the number of days each ticker has returns data
# returns_count = filtered_data_3.groupby('TICKER').size()

# # Identify tickers with at least 128 days of returns history
# tickers_with_sufficient_data = returns_count[returns_count >= 128].index

# # Filter the data to include only these tickers
# filtered_data_sufficient_history = filtered_data_3[filtered_data_3['TICKER'].isin(tickers_with_sufficient_data)]

# # 2. Remove tickers with more than 10 days of problematic returns
# # Define the thresholds for problematic returns
# gain_threshold = 1.0  # 100% gain
# loss_threshold = -0.5  # -50% loss
# max_bad_days = 10

# # Count the number of problematic days for each ticker
# bad_days_count = filtered_data_sufficient_history.groupby('TICKER')['RET'].apply(
#     lambda x: ((x > gain_threshold) | (x < loss_threshold)).sum()
# )

# # Identify tickers with more than 10 problematic days
# tickers_with_data_issues = bad_days_count[bad_days_count > max_bad_days].index

# # Filter the data to exclude these tickers
# final_filtered_data = filtered_data_sufficient_history[~filtered_data_sufficient_history['TICKER'].isin(tickers_with_data_issues)]

# # Display the filtered data
# print(final_filtered_data.head())
# print(f"Number of unique tickers after filtering: {final_filtered_data['TICKER'].nunique()}")

In [ ]:
# final_filtered_data

## Save data

In [94]:
# Save filtered data
filtered_data.to_csv("/content/gdrive/My Drive/Capstone/d.Shuo/filtered_data.csv", index=False)

In [ ]:
# # Define the threshold for gains and losses
# gain_threshold = 1.0  # 100%
# loss_threshold = -0.5  # -50%
# max_bad_days = 10

# # Group by ticker and calculate the number of bad days for each stock
# bad_days_count = Inputation_data_3.groupby('TICKER')['RET'].apply(lambda x: ((x > gain_threshold) | (x < loss_threshold)).sum())

# # Filter out stocks with more than 10 bad days
# good_stocks = bad_days_count[bad_days_count <= max_bad_days].index

# # Filter the Inputation_data_3 to include only the good stocks
# filtered_data = Inputation_data_3[Inputation_data_3['TICKER'].isin(good_stocks)]

# filtered_data

In [ ]:
# test

In [ ]:
# raw_data=filtered_data

In [ ]:
# # Filter data based on minimum days of history and data quality
# min_days = 128
# gain_threshold = 1.0
# loss_threshold = -0.5
# max_bad_days = 10

# # Ensure each ticker has at least 128 days of returns
# ticker_counts = raw_data['TICKER'].value_counts()
# valid_tickers = ticker_counts[ticker_counts >= min_days].index
# filtered_data = raw_data[raw_data['TICKER'].isin(valid_tickers)]

# # Filter stocks with more than 10 bad days
# bad_days_count = filtered_data.groupby('TICKER')['RET'].apply(lambda x: ((x > gain_threshold) | (x < loss_threshold)).sum())
# good_stocks = bad_days_count[bad_days_count <= max_bad_days].index
# filtered_data = filtered_data[filtered_data['TICKER'].isin(good_stocks)]

# # Save filtered data
# filtered_data.to_csv('filtered_data.csv', index=False)

In [ ]:
# import torch
# import torch.nn as nn
# import torch.optim as optim

# class TransformerModel(nn.Module):
#     def __init__(self, n_blocks, d_model, n_heads, d_ff, dropout):
#         super(TransformerModel, self).__init__()
#         self.encoder_layer = nn.TransformerEncoderLayer(d_model, n_heads, d_ff, dropout)
#         self.transformer_encoder = nn.TransformerEncoder(self.encoder_layer, num_layers=n_blocks)
#         self.fc = nn.Linear(d_model, 1)  # Adjust the output layer as needed

#     def forward(self, src):
#         output = self.transformer_encoder(src)
#         output = self.fc(output)
#         return output

# # Hyperparameters
# n_blocks = 6
# d_model = 256
# n_heads = 16
# d_ff = 1024
# dropout = 0.1

# # Initialize model
# model = TransformerModel(n_blocks, d_model, n_heads, d_ff, dropout)
# criterion = nn.L1Loss()
# optimizer = optim.Adam(model.parameters(), lr=5e-5)

In [ ]:
# from torch.utils.data import DataLoader, Dataset

# class FinancialDataset(Dataset):
#     def __init__(self, data):
#         self.data = data

#     def __len__(self):
#         return len(self.data)

#     def __getitem__(self, idx):
#         return self.data[idx]

# # Create dataset and dataloader
# train_data = FinancialDataset(filtered_data.values)
# train_loader = DataLoader(train_data, batch_size=32, shuffle=True)

# num_epochs = 1
# # Training loop
# for epoch in range(num_epochs):
#     model.train()
#     for batch in train_loader:
#         inputs = batch[:, :-1]  # Adjust indexing based on your data
#         targets = batch[:, -1]

#         optimizer.zero_grad()
#         outputs = model(inputs)
#         loss = criterion(outputs, targets)
#         loss.backward()
#         optimizer.step()

#     print(f'Epoch {epoch + 1}, Loss: {loss.item()}')